### ISSUE TITLE
ON Build issue

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#102]
Error:Failed to find: it.feio.android:omninotes_commons:1.0.3-SNAPSHOT

I am using the feature/material-design repo, the gradle thing is working properly it downloaded all the dependencies just didn't find this one.

I am new to android studio and gradle so it might be a foolish question, bear with me :)

**Comment by federicoiosue** [comment]
You're perfectly right. It's because I still didn't updated the repository and I'm working on the sync feature. 

For now just revert the dependency to the previous 1.0.2 version.

**Comment by thewhitetulip** [comment]
Okay, thanks for the response
