### ISSUE TITLE
Grid View

### ISSUE THREAD

**Issue by bendersteed** [federicoiosue/Omni-Notes#103]
Great application, made me ditch Google Keep for good.
What I miss though is a grid view on the notes list. There is too much unused space on tablets with the default list view.

**Comment by thewhitetulip** [comment]
https://github.com/federicoiosue/Omni-Notes/issues/44

**Comment by federicoiosue** [comment]
Nothing on this for now. I'll open a new issue (or reopen this) when I'll have more time to work on the requested feature.

**Comment by Sam15L** [comment]
Any updates regarding this? @federicoiosue

**Comment by federicoiosue** [comment]
Still working on the 6.1.0 update, that really has so much changes under the hood that need to be monitored before public release.
After that I'll work on a new major version that will be focused on UI, to bring some refresh to the base design of the app.
