### ISSUE TITLE
Text on masked note turns encrypted after remove password

### ISSUE THREAD

**Issue by c3686872** [federicoiosue/Omni-Notes#104]
Hi. I'm reporting a serious bug that puts in risk all masked notes. For example, i create a note then i mask it, if i go to the settings and remove the password the text on the notes that were masked turns encrypted so it's lost. I took screenshots:

![screenshot_2015-01-14-05-56-00](https://cloud.githubusercontent.com/assets/10525803/5734762/0a6b2cd8-9bb3-11e4-94db-8e937e44b168.png)

![screenshot_2015-01-14-05-56-14](https://cloud.githubusercontent.com/assets/10525803/5734777/3de0d946-9bb3-11e4-8502-2732247c37ea.png)

![screenshot_2015-01-14-03-51-19](https://cloud.githubusercontent.com/assets/10525803/5734774/2c192a7e-9bb3-11e4-8cc5-02ae269ee283.png)

![screenshot_2015-01-14-05-56-49](https://cloud.githubusercontent.com/assets/10525803/5734781/4aa30f78-9bb3-11e4-96a8-89e58c3ad6cc.png)

Hope you can fix it, the app is amazing i just think it should be more secure in terms of encrypting the database file, some people take notes of sensitive data and it may be in risk if someone with knowledge steals the phone or some malicious app steals the file or something.

**Comment by federicoiosue** [comment]
That's a notable issue.
I'll work on it immediately
