### ISSUE TITLE
Keyboard appears on navigation drawer

### ISSUE THREAD

**Issue by Micks29** [federicoiosue/Omni-Notes#109]
Sometimes my keyboard appears on navigation drawer after have been in the settings but it's a random behavior, not happen each time.

![screenshot_2015-01-19-14-50-24](https://cloud.githubusercontent.com/assets/6850125/5801446/5487b76e-9feb-11e4-875a-00e0972fd35b.png)

**Comment by federicoiosue** [comment]
Hi @Micks29 it's a know and already solved issue #105 
But thanks for reporting: it's better more than less!

**Comment by Micks29** [comment]
Ooops sorry. Bug fixed indeed, thanks!
