### ISSUE TITLE
Possible to refactor date/reminder functionality?

### ISSUE THREAD

**Issue by sb56637** [federicoiosue/Omni-Notes#111]
Hi there, thanks a lot for creating this extremely useful and clean app. I wonder if it it would be possible to re-work the date and reminder functionality a bit? In my use case, most of my todo items just have a due date, with no time. But when I do set a time, I usually don't need a reminder, as I frequently check my list. But then again, there are a few extremely important or time-sensitive issues where I do need a reminder. So I would prefer an option for each task to have a picker "Due date" and "Due time", both being optional. Then, when adding a reminder, maybe it could use relative times by default, such as "1 day before the event" or "30 minutes before the event" or "Right at the due date and time". It would still be useful to be able to add additional reminders for specific dates and times too.

Additionally, it would be nice to have recurring due dates. So when I check the item as completed, it could re-schedule the due date to the next repeat date. And if the previous tweak regarding relative reminder dates/times was implemented, these would come along for free every time relative to the new Due date.

Thanks a lot for your time and hard work!

**Comment by federicoiosue** [comment]
Hi,

about the first part I can tell you that it seems to me a very nice and advanced behavior but for now I'm not going to do any changes to the current reminder feature due to the few time I can spend on it.

Recurrent reminders are instead on the roadmap but they'll probabily be implemented in the Pro version of the application (with the location-based reminders).

**Comment by federicoiosue** [comment]
Recurrent reminder have been added.
The first part of the request will not be implemented for now.
