### ISSUE TITLE
Widget size issue

### ISSUE THREAD

**Issue by Micks29** [federicoiosue/Omni-Notes#116]
Bar & icons are too big with Material Design, should to be more slim, see the difference between latest stable and beta versions: 
<a href="http://www.hostingpics.net/viewer.php?id=525552Screenshot20150126144846.png"><img src="http://img4.hostingpics.net/thumbs/mini_525552Screenshot20150126144846.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=767758Screenshot20150126145024.png"><img src="http://img4.hostingpics.net/thumbs/mini_767758Screenshot20150126145024.png" alt="Upload images" /></a>

**Comment by federicoiosue** [comment]
It's fine, actually the toolbar in Lollipop has a major height than the previously used actionbar element

**Comment by Micks29** [comment]
Too bad, I prefer previous height.
