### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by notice501** [federicoiosue/Omni-Notes#118]
Error:A problem occurred configuring project ':omniNotes'.
> Could not resolve all dependencies for configuration ':omniNotes:_debugCompile'.
   > Could not resolve com.android.support:appcompat-v7:21.0.3.
     Required by:
         Omni-Notes:omniNotes:unspecified
         Omni-Notes:omniNotes:unspecified > com.afollestad:material-dialogs:0.5.6
      > Could not GET 'https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.pom'. Received status code 400 from server: Bad Request
      > Could not GET 'https://github.com/federicoiosue/repository/raw/master/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.pom'. Received status code 400 from server: Bad Request
   > Could not resolve com.google.android.gms:play-services-identity:6.5.87.
     Required by:
         Omni-Notes:omniNotes:unspecified
      > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-identity/6.5.87/play-services-identity-6.5.87.pom'. Received status code 400 from server: Bad Request
      > Could not GET 'https://github.com/federicoiosue/repository/raw/master/com/google/android/gms/play-services-identity/6.5.87/play-services-identity-6.5.87.pom'. Received status code 400 from server: Bad Request
   > Could not resolve com.android.support:support-annotations:21.0.3.
     Required by:
         Omni-Notes:omniNotes:unspecified > com.getbase:floatingactionbutton:1.1.0
      > Could not GET 'https://jcenter.bintray.com/com/android/support/support-annotations/21.0.3/support-annotations-21.0.3.pom'. Received status code 400 from server: Bad Request
      > Could not GET 'https://github.com/federicoiosue/repository/raw/master/com/android/support/support-annotations/21.0.3/support-annotations-21.0.3.pom'. Received status code 400 from server: Bad Request
   > Could not resolve com.android.support:support-annotations:21.0.3.
     Required by:
         Omni-Notes:omniNotes:unspecified > com.afollestad:material-dialogs:0.5.6
      > Could not GET 'https://jcenter.bintray.com/com/android/support/support-annotations/21.0.3/support-annotations-21.0.3.pom'. Received status code 400 from server: Bad Request
      > Could not GET 'https://github.com/federicoiosue/repository/raw/master/com/android/support/support-annotations/21.0.3/support-annotations-21.0.3.pom'. Received status code 400 from server: Bad Request
   > Could not resolve com.android.support:recyclerview-v7:21.0.3.
     Required by:
         Omni-Notes:omniNotes:unspecified > com.afollestad:material-dialogs:0.5.6
      > Could not GET 'https://jcenter.bintray.com/com/android/support/recyclerview-v7/21.0.3/recyclerview-v7-21.0.3.pom'. Received status code 400 from server: Bad Request
      > Could not GET 'https://github.com/federicoiosue/repository/raw/master/com/android/support/recyclerview-v7/21.0.3/recyclerview-v7-21.0.3.pom'. Received status code 400 from server: Bad Request
   > Could not resolve com.android.support:appcompat-v7:21.0.3.
     Required by:
         Omni-Notes:omniNotes:unspecified > it.feio.android:simplegallery:1.1.0
      > Could not GET 'https://jcenter.bintray.com/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.pom'. Received status code 400 from server: Bad Request
      > Could not GET 'https://github.com/federicoiosue/repository/raw/master/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.pom'. Received status code 400 from server: Bad Request

**Comment by notice501** [comment]
I resolved by add another maven repo

**Comment by HanderWei** [comment]
Could you tell me how to resolve it?
```
Error:Failed to find: com.afollestad:material-dialogs:0.5.6
```
