### ISSUE TITLE
Message notifications

### ISSUE THREAD

**Issue by antoinesaliba** [federicoiosue/Omni-Notes#119]
What do you think of the idea of changing the way notifications are presented within the app? For example, when a note is updated and you go back to the main page, there is a notification that says "Note updated". When all notification such as this example are present, it cover the menu bar and makes it a little annoying when trying to quickly navigate through different options that are available only through the menu bar. My idea would be to just have the notification be in the menu bar itself and momentarily replace the name of the directory you are in such as "Notes" or "Trash and also temporarily changing the color of the menu bar?

**Comment by Micks29** [comment]
Nice idea!
Or it's possible to use toast notifications.

**Comment by federicoiosue** [comment]
Toast notifications are not contextuals, I removed that long time ago.

I shortened the display time for notifications but I actually like them where they currently are (I moved them there recently, there used to be shown **under** the old ActionBar before).

Another attempt (maybe the best solution to keep the current aestethic without the annoying behavior) could be to mimic the Toolbar icons ho make evidence of the fact that you can interact with the Toolbar actions even when the message is displayed.
