### ISSUE TITLE
Feature: Merge two or notes into one

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#121]
It would be nice if you can merge notes into one

**Comment by federicoiosue** [comment]
You already can!

**Comment by federicoiosue** [comment]
Or maybe not...

**Comment by thewhitetulip** [comment]
I agree, it is good to keep the old note too because in case the user doesn't like what he wants then he can manually delete the old note or the merged note :)

**Comment by thewhitetulip** [comment]
Well, I think giving a dialog can be good, that way we provide an option of deleting the old notes, because yesterday I was clearing up old notes, it was a tedious job! 

providing a dialog would really be good

I didn't look properly since I didn't stumble upon the merge feature :person_frowning: , but it is a blessing really if you are merging many notes into one and you don't again have to select all of them just to delete them.

**Comment by thewhitetulip** [comment]
I had another question about the omninotesweb, 
do you plan to sync vides and pictures for free?

**Comment by federicoiosue** [comment]
I'd like to have a full sync for free. 
This to give users the same core features than bigger closed-source apps in an open-source flavored alternative :grinning:

**Comment by thewhitetulip** [comment]
I can understand the purpose, but hosting images and video on a serve is going to cost you very much,  

http://www.theverge.com/2013/11/5/5039216/everpix-life-and-death-inside-the-worlds-best-photo-startup

It won't be that much though, but still photo and video does cost, on the contrary text isn't much of an issue in this case, giving full sync free for text might not cost that much, I am not sure.

also I haven't considered the donations factor :)

also I want the schema used for the android app, could you please direct me to the table creation code?

**Comment by federicoiosue** [comment]
We're mixing issue Suraj.
Please move your comments about sync in an appropriate issue or will be too much difficult to track a topic.
Thanks.

**Comment by thewhitetulip** [comment]
haha valid point,

**Comment by federicoiosue** [comment]
Implemented in version 5.0.0 Beta 15
