### ISSUE TITLE
Continual Crashes

### ISSUE THREAD

**Issue by mhylton** [federicoiosue/Omni-Notes#123]
I installed the newest update today and every time I enter a new note the app crashes.  I enter the note and then use the Android back button and that's when it crashes.  I get an Android message "Something went wrong in Omni Notes.  Send automated report (which I've done 3 times as 3 different crashes).

**Comment by Micks29** [comment]
Same here, otherwise language is in English default and I can't acces to settings (bug report sent).

**Comment by federicoiosue** [comment]
Thanks for reporting.
I've released just now a new fix version that should correct the described issues.

@Micks29 I don't know why buy I can't find the exact error in your log, what tool are you using to read the logcat?

**Comment by Micks29** [comment]
@federicoiosue, I'm using Logcat Externe especially for per-app logcat.
