### ISSUE TITLE
Password message notifications unreadable on Kitkat

### ISSUE THREAD

**Issue by Micks29** [federicoiosue/Omni-Notes#127]
Message notifications related with password popup are unreadable on Kitkat, see difference with Lollipop on screenshots below: 
Android Kitkat 4.4.4
<a href="http://www.hostingpics.net/viewer.php?id=424731Screenshot20150223173429.png"><img src="http://img11.hostingpics.net/thumbs/mini_424731Screenshot20150223173429.png" alt="Upload images" /></a>

Android Lollipop 5.0.2
<a href="http://www.hostingpics.net/viewer.php?id=275838Screenshot20150223165901.png"><img src="http://img11.hostingpics.net/thumbs/mini_275838Screenshot20150223165901.png" alt="Upload images" /></a>

**Comment by federicoiosue** [comment]
Fixed, thanks
