### ISSUE TITLE
In notes list showing wrong time of reminder

### ISSUE THREAD

**Issue by musko** [federicoiosue/Omni-Notes#128]
I change in note reminder date and time but in list of notes showing wrong time. Date showing correctly.﻿

![screenshot_2015-03-17-15-13-09](https://cloud.githubusercontent.com/assets/7783470/6689272/6ae62e6e-ccb9-11e4-9c75-0ea6529ae54e.png)
![screenshot_2015-03-17-15-12-58](https://cloud.githubusercontent.com/assets/7783470/6689271/6acfc6ce-ccb9-11e4-83f2-07dbdcb9c60b.png)

**Comment by federicoiosue** [comment]
Hi, it seems to me that you're comparing the reminder date with the last-modification date.

You'll get the notification date in the notes list just when you're into the reminder navigation screen

**Comment by musko** [comment]
Exactly. I confirm. That's different time. One is reminder, correctly seeing in reminder list. And in list of notes is last modification date.

Sorry for that.

Please close.
