### ISSUE TITLE
Cannot see title or contents after IME opened

### ISSUE THREAD

**Issue by samever7** [federicoiosue/Omni-Notes#129]
Should be a compatibility issue.

See image below:

Before open IME:
http://ww1.sinaimg.cn/bmiddle/53af587cjw1eqatirkgdpj20m80zkgmb.jpg

After:
http://ww4.sinaimg.cn/bmiddle/53af587cjw1eqatitdw0bj20m80zkaca.jpg

**Comment by samever7** [comment]
Cannot modify this backlog?  Image cannot display here with only a URL, should be a <img>?

**Comment by federicoiosue** [comment]
Hi, could you please check if the issue is still there using the lastest version 5.0.0 Beta 13?
