### ISSUE TITLE
Actions from notification don't work

### ISSUE THREAD

**Issue by Micks29** [federicoiosue/Omni-Notes#130]
Both actions from notification available don't work on my device (CM11 - Samsung Galaxy S2), logcat below:
https://drive.google.com/file/d/0BzclyNLW7ON6YVJTaXlFWmhzNDA/view?usp=sharing
EDIT: same issue on CM12 Android LP 5.0.2, clean install (wipe + format).

**Comment by Micks29** [comment]
How can I help you for find a fix for this annoying bug?

**Comment by federicoiosue** [comment]
Fixed thanks! 444cb744422c54be6953717ec07822a1bbc4254f
