### ISSUE TITLE
Crashes sometimes corrupt notes, left with empty notes I cannot delete

### ISSUE THREAD

**Issue by jgbreezer** [federicoiosue/Omni-Notes#131]
Sometimes when Omni Notes crashes (whether from widget or from the app, often just after I've started using it to edit a note after a while not using it), it will lose the whole note I was just editing. I am left with an empty note which (Omni Notes normally does not allow) that I cannot (yet, via normal move-to-trash process) delete.

Is the original note data likely to be anywhere I can recover it? Is there a way to backup the notes other than using a backup program like Helium?

**Comment by federicoiosue** [comment]
Hi @jgbreezer, which app version are you currently using?

There was an issue when you switched back to ON after a while not using it that caused a behavior similar to the one you described but I'm pretty sure it should be fixed on the last beta releases.

**Comment by jgbreezer** [comment]
I'm on 4.7.2.

**Comment by federicoiosue** [comment]
As stated before the latest code should have been addressed the issue.

Please try it, it should work correctly, thanks for reporting!
