### ISSUE TITLE
Crash on tablet

### ISSUE THREAD

**Issue by Micks29** [federicoiosue/Omni-Notes#133]
I'm not able to create a note on a tablet, app crashes when perform actions via FAB. Bug reports automatically sent.
About tablet: Samsung Galaxy Tab2 - Android Jelly Bean 4.1.2 - Unrooted.
ON Beta 15

**Comment by federicoiosue** [comment]
Ouch. It's a hateful issue witha Samsung's component.

I vaguely remeber to having addressed it long time ago in some way, I'll try to find out a way.

**Comment by federicoiosue** [comment]
https://code.google.com/p/android/issues/detail?id=60055

**Comment by Micks29** [comment]
Fixed on beta 20, thanks!
