### ISSUE TITLE
Colored navigation items

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#137]
From this idea: https://plus.google.com/106409563988263138955/posts/NygTR4QnsaK

**Comment by federicoiosue** [comment]
Done

![device-2015-04-07-025102 resized](https://cloud.githubusercontent.com/assets/487104/7015279/945da8f8-dcd1-11e4-9f8d-e02ccfb859cd.png)

**Comment by Micks29** [comment]
Great and you're welcome!
