### ISSUE TITLE
Remove hardware menu button access

### ISSUE THREAD

**Issue by Micks29** [federicoiosue/Omni-Notes#138]
Menu from my hardware button still buggy (see screenshots below), I think the best way is to remove access to this hardware button because it's no longer exist anyway: [Google kills hardware menu button] (http://www.androidbeat.com/2013/12/google-kills-hardware-menu-button-android-4-4-kitkat/). 
<a href="http://www.hostingpics.net/viewer.php?id=514114Screenshot20150408134027.png"><img src="http://img11.hostingpics.net/thumbs/mini_514114Screenshot20150408134027.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=858230Screenshot20150408134035.png"><img src="http://img11.hostingpics.net/thumbs/mini_858230Screenshot20150408134035.png" alt="Upload images" /></a>

**Comment by federicoiosue** [comment]
I tried to trigger the overflow menu on the toolbar when the physical menu button was pressed but both AppCompact and the framework itself have some bugs that make this goal too much complex.

Due to the fact that all the device producers are removing this button (even Samsung is replacing it with the "recent apps" menu) I'll simply block its usage.

**Comment by Micks29** [comment]
It's perfect, thanks again!

**Comment by Micks29** [comment]
@federicoiosue, hardware button is back on beta 25. See screenshots below:
<a href="http://www.hostingpics.net/viewer.php?id=595806Screenshot20150517122012.png"><img src="http://img15.hostingpics.net/thumbs/mini_595806Screenshot20150517122012.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=167612Screenshot20150517122025.png"><img src="http://img15.hostingpics.net/thumbs/mini_167612Screenshot20150517122025.png" alt="Upload images" /></a>
