### ISSUE TITLE
[REQ] Use a different gradient of colorization on status bar in slide-in menu

### ISSUE THREAD

**Issue by LeonardKoenig** [federicoiosue/Omni-Notes#139]
Finally I found out what nagged me so bad with the immersion mode:
The status bar is not using a darker color (see pic below).

Additionally some other things I've noticed:
- I'm still not convinced regarding the hiding of the navigation; specially as there is no consistency yet:
 - ..._HIDE_NAVIGATION is not used in the settings but it is in the changelog
 - Sometimes it looks weird as content is (almost) drawn behind the navigation buttons. This is a bit distracting
 - Finally: Other apps do not do that either, it's a bit hard to get used to, if ON is the only app doing that.
- I prefer the lower position of the (+) Button in GKeep
- the aforementioned "slide-in"-menu is sliding in a bit more, almost reaching the vertical bar of the '+'. Just for consistency (it's like that in any GApp).

But really liking the app and looking forward to the web-sync :D

![diff](https://cloud.githubusercontent.com/assets/7831843/7063226/2ecf4ce6-dea5-11e4-940e-b421fe2c7397.png)

**Comment by federicoiosue** [comment]
Hi Leonard,

 * I actually like the way the current navigation bar works due to the fact that it gives me some more usefull space when scrollable content is displayed behind it. Notes list and Info section have scrollable background and they deserve to have more space, other screens do not need it.
 * It seems that the FAB position depends from device, what's yours?
 * I've enlarged it a bit, anyway this is a subjective choice until you stay into the 320dp to allow devices with smaller screens to see some content behind it.

**Comment by LeonardKoenig** [comment]
Hi Federico,

- the transparent navbar probably is just a very subjective opinion. I know the reasons for it – but it distracts me anyhow. Is it possible to implement an option for that? I know, we don't want to make the app bloated though :D 
- Mine is a Xperia T mint (720 x 1280; 4.75"; 320dpi).

[Google says](http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button):

> The floating action button should be placed 16dp min from the edge on mobile and 24dp min on tablet/desktop.

- I didn't find anything concerning this alignment [here](http://www.google.com/design/spec/layout/metrics-keylines.html) but Google at least aligns it a bit more further to the right, which I prefer^^.

But back to my main point:
Is it possible to darken the status bar when the slide-in element is drawn? This I think would definitely be an improvement ;-)

**Comment by federicoiosue** [comment]
I've added a wontfix label to eventually search this proposal later.

For now this is a change I won't implement.

**Comment by LeonardKoenig** [comment]
I just want to make sure we are not misunderstanding ourselves:
I mainly talk about the status bar and not about the navbar ;-).

I've actually no idea at all how this is implemented so I do not know whether this is difficult or not, but shouldnt it be easy to not "overlap" the status bar?

**Comment by federicoiosue** [comment]
Sorry, I was still thinking about navbar. 
The status bar is now semi transparent.

**Comment by LeonardKoenig** [comment]
That's cool. Thanks :-)

**Comment by federicoiosue** [comment]
I suppose I simply missed it during the materializing transition

**Comment by LeonardKoenig** [comment]
It's just a small detail and I knew something nagged me – so I compared screenshots and only found it that way^^
Now it looks really nice :D
