### ISSUE TITLE
No Trash Icon

### ISSUE THREAD

**Issue by craig-s** [federicoiosue/Omni-Notes#140]
If you have no deleted notes, there is no Trash icon in the navigation drawer. Fine. However, when you then delete a note, there is still no Trash icon until you close the app and reopen it again.

**Comment by federicoiosue** [comment]
It appears to work fine to me. Could you provide some steps to reproduce?

**Comment by craig-s** [comment]
Sorry, you are right.

That isn't the problem at all. The problem is with the archiving of
uncategorized items.

1. I have one uncategorized item
2. I use the navigation drawer to filter by uncategorized
3. I Swipe the note to archive it.

The note it still present in the current filtered view, with an archived
icon

4. When I Swipe it (actually, as soon as I touch it) , the note disappears.
I assumed it went to Trash, but it was still in Archive - just NOT shown in
the filtered list this time.

If I pull out the navigation drawer and select the same filter
(uncategorized) again, the archived note is shown again - with an archived
icon. And I can swipe this and archive it again. This process can restore
repeated.

So, sorry, that is what misled me.

**Comment by federicoiosue** [comment]
Actually you were right Craig, the original issue exist.

I'll check for both of them, thanks for reporting!

**Comment by federicoiosue** [comment]
Fixed both the issues thanks.

From now on the swiping action from inside "Uncategorized" navigation scree will be no more allowed.
