### ISSUE TITLE
Navigation drawer too wide on HDPI devices

### ISSUE THREAD

**Issue by Micks29** [federicoiosue/Omni-Notes#141]
Since beta 17 it's worse, see screenshot below:
<a href="http://www.hostingpics.net/viewer.php?id=843170Screenshot20150410094601.png"><img src="http://img11.hostingpics.net/thumbs/mini_843170Screenshot20150410094601.png" alt="Upload images" /></a>
It will be great to definitively find a fix, [this commit] (https://github.com/BioHaZard1/XDA-One/commit/9977cb94aa50262d0f1b065503454b462e7fe686) (thanks to BioHaZard1) can help you I think.
About device: Samsung Galaxy S2 (480x800, 4.30", 240 dpi)

**Comment by federicoiosue** [comment]
Fixed, thanks

**Comment by Micks29** [comment]
Indeed it's perfect on beta 18, thanks!

**Comment by Micks29** [comment]
@federicoiosue, navigation drawer again buggy since beta 23. See difference between previous and latest versions on these screenshots below:
<a href="http://www.hostingpics.net/viewer.php?id=586854Screenshot20150416190051.png"><img src="http://img15.hostingpics.net/thumbs/mini_586854Screenshot20150416190051.png" alt="Upload images" /></a>
Previous version

<a href="http://www.hostingpics.net/viewer.php?id=402353Screenshot20150430182010.png"><img src="http://img15.hostingpics.net/thumbs/mini_402353Screenshot20150430182010.png" alt="Upload images" /></a>
Latest version (beta 23)
