### ISSUE TITLE
Translucent statut bar missing in Settings

### ISSUE THREAD

**Issue by Micks29** [federicoiosue/Omni-Notes#147]
On Android 4.4.4 we have a nice translucent status bar on main screen and Info tab but it missing on Settings tab (and sub-tabs: Data, Interface, Behaviors et Notifications), see screenshots below:
<a href="http://www.hostingpics.net/viewer.php?id=411133Screenshot20150420175012.png"><img src="http://img15.hostingpics.net/thumbs/mini_411133Screenshot20150420175012.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=672001Screenshot20150420175004.png"><img src="http://img15.hostingpics.net/thumbs/mini_672001Screenshot20150420175004.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=474740Screenshot20150420175022.png"><img src="http://img15.hostingpics.net/thumbs/mini_474740Screenshot20150420175022.png" alt="Upload images" /></a>

**Comment by federicoiosue** [comment]
It's a wanted behavior. Translucency is used only when some content scrolls under the system bars. 

In addition to this it has a cost in terms of computation and code lines, that's why is not implemented in settings.

**Comment by Micks29** [comment]
I've some content which scrolls under the system bars on my device (small screen: 4.30") and in Lollipop Settings tab and sub-tabs have a darker statut bar.
But if it's hard to implement forget this (aesthetic) request, it's not a big deal anyway!
