### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by craig-s** [federicoiosue/Omni-Notes#154]
I can only ever see this feature useful if you can choose to include / exclude such items from the list while in a Category. 
You have NOTES for all notes, and ARCHIVE for just the archived notes, but while limiting the list to one category, archived notes are always included - cluttering up the list. If you could, while in a category list, choose to include, exclude or limit the list to just archived items - the archive feature might be worth using.

**Comment by federicoiosue** [comment]
Duplicate of #73
