### ISSUE TITLE
Assigned Category

### ISSUE THREAD

**Issue by craig-s** [federicoiosue/Omni-Notes#155]
When selecting to view ALL NOTES from the navigation drawer, and a note is viewed, there is no way to see the current category allocated to it. 
There is a colour, but this can be used for multiple categories.
When a 'real' category is selected as a filter from the navigation drawer, and a note is viewed - taping the category icon lists the categories and highlights the one being filtered on (for which the note belongs).
This functionality should also be used when viewing ALL NOTES, but not using the filter category -  using the currently assigned category.

**Comment by federicoiosue** [comment]
I'm sorry, I really didn't understand what you meant Craig.

**Comment by craig-s** [comment]
From the Navigation Drawer I select 'Notes', so that ALL my notes are included in the List View. I tap on a note (any one) and the app displays the note details. Fine.
How can I tell what the category for this note is ?
If you reply 'by the colour', then consider the situation where I have two categories with the same (or similar) colour,

**Comment by federicoiosue** [comment]
I got your point.

Could be an acceptable solution to have the category related with actually opened note highlighter as in picture?

![selezione_021](https://cloud.githubusercontent.com/assets/487104/7622068/2da49370-f9cc-11e4-8dc3-c78ae67fd902.jpg)

**Comment by craig-s** [comment]
That would be perfect :-)

**Comment by federicoiosue** [comment]
Done, I'll release this on the next beta.
Thanks for the advice!
