### ISSUE TITLE
"Empty trash" doesn't work. 

### ISSUE THREAD

**Issue by jonbarh** [federicoiosue/Omni-Notes#156]
Hi, thanks for your hard work.

"Empty trash" doesn't work.

1. "Confirm deleting all trashed notes?" -----> Ok
2. Trash seems empty ------> "Nothing here!"
3. Make a new note and send it to trash bin.
4. At the top of page, count of deleted notes shows more than this one.
5. The trash is still full with all the previous deleted notes.
:/

Motorola Moto E 4.4.4
Updated to 5.0.0 Beta 22

**Comment by federicoiosue** [comment]
Hi, thanks for reporting.

Actually the number you see on the top is just a counter of **selected** notes. 
I forgot to reset it once notes have been deleted (archive, categorize and trash procedure are different and they were already ok).

**Comment by jonbarh** [comment]
Maybe I didn't explain myself quite well, sorry about.
I made a video for you.
https://youtu.be/ZuIPP5IdfDQ

Also, I forgot to send you a screen capture about overlaping icons in landscape mode.

![overlaping icons](https://cloud.githubusercontent.com/assets/12173190/7399717/eccd7dea-eeb7-11e4-9ce8-74f0c29f25b9.png)

Really like your app.

**Comment by federicoiosue** [comment]
Great explanatory video!

Yes, I got the point and solved the issues (both).
I'll release a fix version asap.

Thanks!

**Comment by jonbarh** [comment]
Your are welcome,
Thanks to you.
