### ISSUE TITLE
Search - Strange Behaviour

### ISSUE THREAD

**Issue by craig-s** [federicoiosue/Omni-Notes#157]
Viewing ALL NOTES
Select SEARCH
Enter search text
- List is filtered
Tap a note to view it
- note displayed
Press BACK
ALL NOTES are displayed WITHOUT a filter but the search subheading is still present with an empty search value. 

Either all notes should be displayed, as is now, without the Search subheading 

Or

The same Filter should remain in effect and the presented Search subheading remain - but with the filter value being used. 

I think the second option should be used.

**Comment by federicoiosue** [comment]
It's a known bug appearing when "instant search" is on,
Fixed,
