### ISSUE TITLE
Phone numbers clickable issue

### ISSUE THREAD

**Issue by Micks29** [federicoiosue/Omni-Notes#158]
When I tap on URLs and e-mail addresses nothing happen on beta 23.
And it's possible to bring the same thing for number phone (e.g when I tap on number phone, my phone app opens)?

**Comment by federicoiosue** [comment]
Actually you should double-touch to perform actions on links.

Does your phone numbers appears underlined? Because not all phone numbers formats are recognized and your case could be one of these.

**Comment by Micks29** [comment]
Oh sorry, indeed double tap works very well for URLs and e-mail addresses!

Yes phone numbers are just underlined. In France format for phone numbers is: xx xx xx xx xx (or +33 x xx xx xx xx for international format), can you add compatibility for this format?

**Comment by federicoiosue** [comment]
If phone numbers are underlined then they should be correctly recognized
and double-touchable too

Il giorno sab 2 mag 2015 14:27 Micks29 <notifications@github.com> ha
scritto:

**Comment by federicoiosue** [comment]
European numbers should all be OK. 
We've got similar number formats for all countries.

**Comment by Micks29** [comment]
You've definitely right, after remove space between each number it's ok!
Sorry for this invalid report.
