### ISSUE TITLE
Hide a note or a category from main view

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#162]
There are few notes which I keep for archival purposes, like a list of birthdays of friends, I don't want to see it in main view, or there is some other note, what I want is
1. The note or notes should not be shown in main view
2. The notes should be shown in the category view

**Comment by federicoiosue** [comment]
Currently if you archive a categorized note this will not be shown anymore inside the main navigation screen but it'll be still available both from inside the category and archived sections. 

You meant something more than this?

**Comment by thewhitetulip** [comment]
Archive is something we do to keep stuff that you don't want to delete but aren't that useless.

I want a mechanism where we can hide a note from main view, there are few notes you take for reading some day in the future, although be can do archive, but it would be awesome to hide the notes

**Comment by federicoiosue** [comment]
I'd like to keep a KISS philosophy as much as possible, so, for now I think that the active/archived/trashed system is enough.
