### ISSUE TITLE
Toast confirmation when a reminder is added

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#163]
On a lollipop when you set an alarm then it shows a toast saying, "An alarm set for 6 hours", we can show such a toast in ON too, saying "A reminder has been set for 7 hours" and if it set for more than 24 hours then "A reminder has been set for 21/5/2015"

**Comment by federicoiosue** [comment]
Done.

Whenever a reminder is set (even on snooze or on reminder modification from notification action) a Toast is shown. 
It contains only the reminder time, no prettified formats.
