### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by craig-s** [federicoiosue/Omni-Notes#167]
I'm not sure if this is deliberate behaviour or not, but when searching from either ARCHIVE or UNCATEGORIZED - the search is made across ALL notes.

For specific categories, the search is limited to those notes belonging to that category - which is great. But surely, a search in ARCHIVE should be limited to notes that have been archived ?

What do you think ?

**Comment by federicoiosue** [comment]
Searches in **archive** and **uncategorized** also should do a vertical search into themselves as categories already do.

I'll change the behavior in that way.
