### ISSUE TITLE
Failed to find `material-dialogs`

### ISSUE THREAD

**Issue by HanderWei** [federicoiosue/Omni-Notes#168]

**Comment by igorgo** [comment]
It seems the pakage was removed from a repository. There is a new version on https://github.com/afollestad, but this doesn't support some methods used in Omni-Notes.

In  `Omni-Notes\omniNotes\build.gradle` I added
```Gradle
repositories {
    maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
}
```
and changed the version
```Gradle
//  compile 'com.afollestad:material-dialogs:0.5.6'
    compile 'com.afollestad:material-dialogs:0.7.4.1'
```

Then I changed all calls of the `callback` method to `.callback(new MaterialDialog.ButtonCallback()`. and added the `null` argument to calls of `customView`, `adapter` methods.

**Comment by mcqueen12** [comment]
"added the null argument to calls of customView and adapter methods."

Can you write more about this arguments?

**Comment by igorgo** [comment]
i beg your pardon, I made a mistake. The `null` value applies only to the second argument of the ` adapter(ListAdapter adapter, ListCallback callback)` method of `MaterialDialog.Builder`.

And in the `customView(View view,  boolean wrapInScrollView)` method, I used `false` as the value of the second argument.

**Comment by mcqueen12** [comment]
Можете скинуть куда-нибудь проект, который компилируется и открывается apk?) Буду благодарен)

**Comment by igorgo** [comment]
https://github.com/igorgo/Omni-Notes

**Comment by mcqueen12** [comment]
Thank you!
