### ISSUE TITLE
Toast with every reminder

### ISSUE THREAD

**Issue by Tsunamii** [federicoiosue/Omni-Notes#172]
I set a daily reminder for 2 of my notes but everytime the alarm goes of there is a toast at the bottom saying "alarm set for ..."

Shouldn't that toast only be shown when the reminder is set initially not everytime time it is triggered?

**Comment by federicoiosue** [comment]
It's wanted, just to clarify when that reminder will be fired again.

**Comment by Tsunamii** [comment]
ok good to know. feels kinda unnecessary for timed/daily reminders
