### ISSUE TITLE
Cursor is missing and lists being covered by keyboard

### ISSUE THREAD

**Issue by jonbarh** [federicoiosue/Omni-Notes#173]
Hi, Federico

Today I did notice that when tapping on text the cursor did not appears at all.
Also, at least in my case, when keyboard rises it covers the text. It would be great that the text line that is being edited was displayed over the keyboard (including the suggestion bar).

Thanks

Android 4.4.4
Motorola Moto E
Multiling O Keyboard

**Comment by Micks29** [comment]
@federicoiosue,
Cursor is here on my device but not indicator of where it is, this bug happen in content field in the check list only. See screenshots below for better understand what I want mean:
<a href="http://www.hostingpics.net/viewer.php?id=118718Screenshot20150618135016.png"><img src="http://img11.hostingpics.net/thumbs/mini_118718Screenshot20150618135016.png" alt="Upload images" /></a>
In tilte field it's ok cursor indicator is here.
<a href="http://www.hostingpics.net/viewer.php?id=345287Screenshot20150618135036.png"><img src="http://img11.hostingpics.net/thumbs/mini_345287Screenshot20150618135036.png" alt="Upload images" /></a>
In content field cursor indicator is missing. 
It's annoying to not see where the cursor indicator is
