### ISSUE TITLE
Card Height

### ISSUE THREAD

**Issue by craig-s** [federicoiosue/Omni-Notes#174]
When using the Expanded View, Locked Notes  are padded out to be the same height as other notes. However, when using the Reduced View they are not. The card height is smaller than the others making the list look inconsistent.

**Comment by federicoiosue** [comment]
Actually that's totally dependent on content as far as I see, so everything works as intended.

**Comment by craig-s** [comment]
Ah... yea, maybe as intended. But... 

Locked notes display no content - only the title. I have a note that is locked, and when I use the Expanded View only the title is displayed (at the top) and the update date with the lock icon at the bottom. The rest is blank space - padding the card out to the regular size (on my device, 17mm).

Using the Reduced View, the same note displays the same details, but is not padded with spaces. However, it's height is smaller (9mm on my device) than ALL the other unlocked notes (which take up 12mm on my device). 

Yes, I do realise you try to dynamically set the height of the notes in reduced view - but this is NEVER utilised (in practice) for normal notes.
Is it ?
The size is ONLY smaller if the note has a title and NO content at all - or NO title and content of one line or less.

If this is what you intended, then fine. But to me, it seems funny to see notes of varying height in the list view (unless you are trying to display the whole note within limitations). 

Thanks
