### ISSUE TITLE
Reminder allows past date to be set

### ISSUE THREAD

**Issue by vineethaindukuri** [federicoiosue/Omni-Notes#180]
![screenshot_2015-06-27-18-44-19](https://cloud.githubusercontent.com/assets/10041601/8394792/e26f4c7e-1cfd-11e5-97a7-72a6172fb246.png)

The system allowed me to set a reminder to a past date (June 24th) , when the reminder creation time was on June 27th. I am thinking that the reminder system, should allow only future reminders. Is there any use case for creating past reminders?

Thanks,
Vineetha

**Comment by federicoiosue** [comment]
Actually not, but acting like that will simply do nothing more that adding a reminder date to that not with no system alarms.
