### ISSUE TITLE
option to recover backup in an appending way, not overriding

### ISSUE THREAD

**Issue by flashlab** [federicoiosue/Omni-Notes#181]
Is it possible to import data without erase the current data :smiley:

**Comment by federicoiosue** [comment]
The next beta will have a totally rewritten backup/restore part (json will be used to prepare to cloud features) where merge will be the standard behavior (due to the fact that merging notes asynchronously created on different devices will be a necessity)

**Comment by flashlab** [comment]
So we will have  cloud storage finally?  Glad to hear that~
