### ISSUE TITLE
Unable to build Omni notes 5.0.3

### ISSUE THREAD

**Issue by psuryatej** [federicoiosue/Omni-Notes#182]
I am using Android Studio to build the code..
The initial Error .. I am facing is given below

Error:A problem occurred configuring project ':omniNotes'.
> Could not resolve all dependencies for configuration ':omniNotes:_debugCompile'.
   > Could not find com.afollestad:material-dialogs:0.5.6.

To resolve the above error, I have updated build.gradle to look for
compile 'com.afollestad:material-dialogs:0.7.6.0'    (latest version)

But, I am getting the new error as follows 

C:\Android\Projects\Omni-Notes-5.0.2\omniNotes\src\main\java\it\feio\android\omninotes\DetailFragment.java
Error:(1195, 5) error: method adapter in class Builder cannot be applied to given types;
required: ListAdapter,ListCallback
found: NavDrawerCategoryAdapter
reason: actual and formal argument lists differ in length
Error:(2133, 48) error: incompatible types: bad return type in lambda expression
missing return value

C:\Android\Projects\Omni-Notes-5.0.2\omniNotes\src\main\java\it\feio\android\omninotes\ListFragment.java
Error:(1319, 45) error: cannot find symbol class Callback
Error:(1316, 17) error: method adapter in class Builder cannot be applied to given types;
required: ListAdapter,ListCallback
found: NavDrawerCategoryAdapter
reason: actual and formal argument lists differ in length
Error:(1427, 60) error: incompatible types: bad return type in lambda expression
missing return value

Can you please advise on how to fix this ? Thanks in advance

**Comment by federicoiosue** [comment]
Checkout the lastest develop branch commits
