### ISSUE TITLE
Add button over undo link

### ISSUE THREAD

**Issue by jonbarh** [federicoiosue/Omni-Notes#183]
Only in landscape mode: when removing a note and the undo message is displayed, the link to "undo" action is covered by de add buttom.

![screenshot_2015-07-06-19-23-22](https://cloud.githubusercontent.com/assets/12173190/8528816/f9b78ad0-2415-11e5-8de3-64eda771904d.png)

:)

**Comment by federicoiosue** [comment]
I've not been able to reproduce the issue.

When I try to archive/trash/remove category from a note or more (I tried these operations from inside "Notes", "Archive" and a category) everything works as expected: the undo bar appears and the fab disappears; when you press undo or interact with the underlaying layout the undo bar disappears while the fab comes up again.

**Comment by klawdhfzasjhaa** [comment]
I have another overlapping problem:

I use Cyanogenmod 13.0 and I reduced the ppi.
![screenshot_20170218-144551](https://cloud.githubusercontent.com/assets/2808094/23106618/68eef72c-f6f0-11e6-8c07-07b58fe6b47d.jpg)

**Comment by federicoiosue** [comment]
The last one have been fixed thanks to #403

**Comment by federicoiosue** [comment]
The last one have been fixed thanks to #403
