### ISSUE TITLE
Cloud saving

### ISSUE THREAD

**Issue by jaimejimbo** [federicoiosue/Omni-Notes#185]
It would be great to use some cloud file system to save notes. I mean, like having a git on dropbox that saves all changes and allow to go backwards. I have lost my notes twice because an error of my terminal.

**Comment by jaimejimbo** [comment]
I know that there is an option to backup the notes, but I mean that it could be automatic when closing a note(for example) and do it in the dropbox/drive folder.

**Comment by federicoiosue** [comment]
Duplicate of https://github.com/federicoiosue/Omni-Notes/issues/55
