### ISSUE TITLE
Keyboard does not automatically open for password dialog

### ISSUE THREAD

**Issue by mmoura11s** [federicoiosue/Omni-Notes#186]
Federico,

When Data > Password is set and app is locked I expect, when opening the app, the password dialog to open, focus the textbox and bring up the keyboard so I can type the password. 
However, when the app is opened, the textbox has the cursor typing point but the keyboard is not automatically opened, which makes me have to tap the textbox itself to have it pop up.

Keep up the great work ;)

Android 4.2.2
Google Keyboard

**Comment by federicoiosue** [comment]
Fix is coming with 5.1 Beta! Thanks for reporting!
