### ISSUE TITLE
Poor performance with long notes

### ISSUE THREAD

**Issue by jaimejimbo** [federicoiosue/Omni-Notes#187]
When writing a long note, system starts lagging. I suppose this is due to the fact that all note is loaded to ram. It would be better to load only a portion wrapping actual position. But perhaps it would make reading laggy.

**Comment by federicoiosue** [comment]
Is lagging where? Into notes' list?

**Comment by federicoiosue** [comment]
No more feedback on this, I'll close it for now.

**Comment by jaimejimbo** [comment]
I had to change my phone and note it seems to work fine
