### ISSUE TITLE
Adding a contributors text file

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#188]
How about adding a text file to write everyone who contributed to the app just like the way brackets.io does

**Comment by federicoiosue** [comment]
The information is already available here https://github.com/federicoiosue/Omni-Notes/graphs/contributors, I'd like to avoid keeping track manually of things like that.

**Comment by thewhitetulip** [comment]
But those contributors are only the ones who have contributed code, what about the design changes or things like that

**Comment by federicoiosue** [comment]
Tracking feedbacks would be quite impossible, at least for me. And I would not see the point.

But you could add the file and I could link it from README of you believe could be useful

**Comment by thewhitetulip** [comment]
I think you can create a contributors file and every time someone makes any kind of contribution that person will submit a pull request to add their name in the file, you would not have to do anything. problem solved.

**Comment by federicoiosue** [comment]
Closed by 6ee238ea7fdbd3163d68bd82bc584603c5fc1655
