### ISSUE TITLE
[REQUEST] Add support for the Paperwork API 

### ISSUE THREAD

**Issue by stevenroose** [federicoiosue/Omni-Notes#195]
[Paperwork](https://github.com/twostairs/paperwork) is an open-source self-hosted note-keeping web application, comparable to Evernote and Google Keep.
The web application is getting quite mature and it has a lot of users. However, the developers have little experience with Android, so there is no Android application (yet), neither is there one on the roadmap for the near future.
Since Omni Notes is already a very mature and feature-full Note Taking application, it might be beneficial for both parties to provide synchronization functionality into Omni Notes in the form of the paperwork API.
Their API is [well-documented](http://docs.paperwork.apiary.io/) so it won't be too much a hassle to implement.

twostairs/paperwork#379 is the issue over at Paperwork about an Android application.

**Comment by federicoiosue** [comment]
They seem to have an Android application actually. Even if in early development stage.

Cloud sync improvements for ON reside here #122

**Comment by stevenroose** [comment]
@federicoiosue They do not, actually. Someone made a prototype independently and then abandoned it.
But ok, will post my request in that issue, thanks!

**Comment by federicoiosue** [comment]
No need for that @stevenroose, I'll keep this issue open.

**Comment by stevenroose** [comment]
Cool, thanks.
I'll crosspost my comment on #122 here maybe

I'm seeing a lot of arguments for Dropbox and ownCloud support. Together with Google Drive, those are the three major cloud storage providers, so supporting them will surely give all ON users a place to backup their notes.

I'd like to make an additional suggestion, though. Paperworks is a self-hosted note-taking application for the web and it's been gaining popularity recently. Needless to say, it's users would like to have an Android application.
This might be an opportunity for ON to gain the interest of a very active community with a lot of tech-savvy folks and developers.

If you want to stick with a single sync option, Paperworks is not the way to go, but if you are implementing several, I think Paperworks would be a great addition!

**Comment by stevenroose** [comment]
I think that you will easily find folks over at Paperwork that would like to help you out with this, btw.

**Comment by synchrone** [comment]
There are conceptual issues. Like e.g Paperwork has a different idea about the text. As far as I see from here it's HTML, while ON sticks to plaintext, and really you wouldn't like to edit HTML from your mobile, would you? 
<img> support alone would be kind of tricky to implement, and then there's <place your image inside the note> button, which basically just puts a relative URL to Paperwork server inside your note.

We need to propose a sensible compatibility workflow before trying to implement this.

**Comment by mrusme** [comment]
@federicoiosue hey there! I'm the founder of Paperwork. Maybe we could chat about this anytime soon again? Have some news to share regarding the API.

**Comment by sbrl** [comment]
What's the status of this? I'd love to use paperwork (since there isn't anything else half decent out there that does the job without any problems), but if it doesn't have an android app that's deal-breaker for me. I'd be happy to do a few PRs here and there too - I know PHP and other languages, but not Java.

**Comment by federicoiosue** [comment]
@sbrl This is the official Omni Notes desktop cross-platform application: https://github.com/federicoiosue/omni-notes-desktop
