### ISSUE TITLE
Possibility to sort check lists

### ISSUE THREAD

**Issue by malnvenshorn** [federicoiosue/Omni-Notes#196]
Hi,

I haven't discovered the possibility to sort check lists, e.g. to sort them by name or, more important to me, to put unchecked items to the top of the list. It would also be nice to have an option to automatically sort the entries according to the selected method.

**Comment by federicoiosue** [comment]
@malnvenshorn would be great if you could open again this issue on the apposite project to help me to keep track of the issues: https://github.com/federicoiosue/CheckListView/issues
