### ISSUE TITLE
HELP MY PLEASE

### ISSUE THREAD

**Issue by joseliko7** [federicoiosue/Omni-Notes#197]
Error to Export APK

Error:Execution failed for task ':omniNotes:proguardRelease'.
> java.io.FileNotFoundException: C:\Users\Jose\Desktop\APP\omniNotes\..\bin\seeds.txt (The system can not find the path specified)

**Comment by federicoiosue** [comment]
It should be ok now

**Comment by joseliko7** [comment]
Ok Thanks!
