### ISSUE TITLE
No build instructions for Developers

### ISSUE THREAD

**Issue by yvolk** [federicoiosue/Omni-Notes#20]
I've cloned the repository using AIDE (sorry,  Eclipse is not available now. ..) in order to build and test the application on the device.  But build ended with lots of errors. 
I found a  list of dependencies in the Readme.md file, but I don't know,  which version of each dependency to fetch and whether this is the only reason for build errors...
Please provide any sort of build file: at least, it will allow to figure out correct build settings and exact dependencies. 

I think that lack of such instructions for developers is a reason for:
1. Having a single contributor to the project. 
2. Absence of this application in the f-droid Open Source repository.  
BTW recently I found out that number of downloads of my Open Source application via f-droid is 2 times more than via Google Play...

**Comment by Mosrite** [comment]
I would love to see the app on F-Droid!

**Comment by federicoiosue** [comment]
@Mosrite that's not possibile due to a couple of dependencies on closed-source Google's library
