### ISSUE TITLE
Sharing notes bug

### ISSUE THREAD

**Issue by malnvenshorn** [federicoiosue/Omni-Notes#204]
Hi,

if I try to share notes with an attached image, e.g. send them to whatsapp, only the image will be shared and not the content itself. For notes without an image it works perfectly.

**Comment by federicoiosue** [comment]
@malnvenshorn could you please provide some more data (ex. app version, os version, device...)?

I tried with lates 5.1.3 and it worked.

**Comment by malnvenshorn** [comment]
I'm using the latest version (5.1.3). Device is an Galaxy S3 Mini VE with Android 4.2.2 running. 
I have to revise my above statement it works with whatsapp, but the problem exists for telegram.

**Comment by federicoiosue** [comment]
It depends on how Telegram manages received data, it's not an ON related issue
