### ISSUE TITLE
No notifications 

### ISSUE THREAD

**Issue by kc853** [federicoiosue/Omni-Notes#206]
Hi,  for whatever reason I don't get any notifications for my notes. Even if I keep screen and ON alive till notification time. Vibration and sound are set. 

Regards.

**Comment by federicoiosue** [comment]
Could be helpful to provide a log here.

Could you please try to:
 - Set a reminder (event the next minute you set it)
 - Wait for reminder time
 - Provide logcat if nothing happens

**Comment by kc853** [comment]
Is there a built in logging function? Or do I need to get the logcat via Usb?

**Comment by federicoiosue** [comment]
Could be related with #220 ?
