### ISSUE TITLE
Can't open links with Google+ app

### ISSUE THREAD

**Issue by RiddleDude** [federicoiosue/Omni-Notes#210]
### Issue
You can't open links in Google+ app in following locations:
  + App tour (last slide when starting freshly installed app)
  + Under ``settings -> beta``

### Possible solution
From my understanding Google+ app can't open those links because they are shortened in ``gplus_community`` string to https://goo.gl/eF6qqF and ``beta_link`` to http://goo.gl/zBZQLr
If you would replace shortened links with full URLs it should work

**Comment by Domuska** [comment]
For me the link hidden in the picture of the last slide of the app tour (on a fresh install) works correctly, it shows up the app chooser and Google+ is able to open the link. The link under

` settings -> beta`

is not actually an URL to Google+ but to the Play Store, so Google+ should not open it in any case. ;)

**Comment by federicoiosue** [comment]
You are right its not clear, the problem is that I always try to avoid string changes due to the difficulties in keeping updated translations, so sometime I try to reuse olds phrases with results like this one.

**Comment by federicoiosue** [comment]
![selezione_053](https://cloud.githubusercontent.com/assets/487104/10651094/b4a6e24c-784d-11e5-9513-6d1fdb65378c.png)
![selezione_054_1](https://cloud.githubusercontent.com/assets/487104/10651095/b4a9608a-784d-11e5-894f-9029e4213e6d.png)
