### ISSUE TITLE
Checklist improvement idea - add checklist anywhere

### ISSUE THREAD

**Issue by RiddleDude** [federicoiosue/Omni-Notes#211]
### Idea
Possibility to add checklist anywhere in regular note.
Currently you can **transform** regular note into checklist by clicking ``Enable checklist``. This adds check-box to any row in the note. What if you could enable it *on demand*, e.g. final note would be:
> Ingredients for chocolate cake: (now you make a list)
> [ ] Chocolate
> [x] Cake
> Recipe: (make a list again)
> [ ] Open chocolate
> [ ] Make cake

I actually haven't seen an app that could do this. There usually is just ``create list`` or ``create note ``, this hybrid functionality seems a nice touch

**Comment by federicoiosue** [comment]
@RiddleDude  would be great if you could open again this issue on the apposite project to help me to keep track of the issues: https://github.com/federicoiosue/CheckListView/issues
