### ISSUE TITLE
Checklist improvement idea - ordered, unordered lists

### ISSUE THREAD

**Issue by RiddleDude** [federicoiosue/Omni-Notes#212]
### Idea
Possibility to insert ordered and different notation unordered lists
### Example in plain text
Ordered list notation:
```
1. [ ] Pigeon
2. [ ] Walrus
3. [ ] Shark
```
Alternative unordered list notation with ``-``, ``+`` or ``*``, that you could set in settings
```
- [ ] Pigeon (or)
+ [ ] Walrus (or)
* [ ] Shark (or)
[ ] Tiger
```

**Comment by federicoiosue** [comment]
@RiddleDude  would be great if you could open again this issue on the apposite project to help me to keep track of the issues: https://github.com/federicoiosue/CheckListView/issues
