### ISSUE TITLE
Backup/Restore broken on Marshmallow

### ISSUE THREAD

**Issue by najodleglejszy** [federicoiosue/Omni-Notes#216]
every time I'm trying to create or restore a backup, the toast saying something went wrong pops up and the app restarts. I'm using Sony Xperia Z3 compact on Marshmallow.

**Comment by federicoiosue** [comment]
Could you provide a log?

Did the app confirmed you that a backup was been sent to the developer?

**Comment by najodleglejszy** [comment]
yes, the toast notified me of sending the error to the developer. and unfortunately I have no idea how to get the log.

**Comment by najodleglejszy** [comment]
OK, I figured it out. I had to manually grant permission for Omni to access the storage. working fine now.

**Comment by federicoiosue** [comment]
This was due to some sort of customization you had or what?

Il giorno dom 1 nov 2015 03:24 najodleglejszy <notifications@github.com> ha
scritto:

**Comment by najodleglejszy** [comment]
no, Omni Notes didn't ask for the permission to access storage on the first run I think, and Android defaulted to denying it.

**Comment by federicoiosue** [comment]
It's quite strange, permissions are declared and accepted on installation
time, except if you're on marshmallow!

Il giorno dom 1 nov 2015 10:15 najodleglejszy <notifications@github.com> ha
scritto:

**Comment by najodleglejszy** [comment]
I am using Marshmallow, as I mentioned in the first post.

**Comment by federicoiosue** [comment]
Sorry you're perfectly right.. I missed that! 
Well, I still not moved to the new permissions runtime so I suppose what you described is actually what will happen to anyone using ON on very recent devices. 

I'll make the upgrade asap

**Comment by federicoiosue** [comment]
Should work correctly from version 5.2.0 Beta 4

**Comment by cacula** [comment]
i had the same issue as najodleglejszy. i updated to beta 4 today. now i am asked to grant permssion to read. but when i say "allow" i get a dialog that says "screen overlay detected - to change this permission setting, you first have to turn off the screen overlay from settings > apps".
in this setting it says that omninotes is not allowed to draw over apps. and i also cannot change this setting. when i leave the setting dialog and return to omninotes i get a "permission not granted" dialog.
i tried again but its always the same.  when i try to grant the read permission for omninotes via system settings i get the same screen overlay" dialog.
in other apps where i get asked to grant read permission i do not get this "screen overlay" dialog.

btw: thanks for this wonderfull app - very appreciated :-)

**Comment by federicoiosue** [comment]
@cacula could you please provide a screenshot?

**Comment by federicoiosue** [comment]
@cacula I think that's not actually a misbehavior. Effectively the option you were talking about exists and works as the dialog you got described.

The only strange thing is that when you're into ON's options there should not be need of overlying any other app.
