### ISSUE TITLE
Notes swiped from category labeling

### ISSUE THREAD

**Issue by AidanRB** [federicoiosue/Omni-Notes#218]
When a note is in a category and the user is in that category, swiping the note to the side results in "Note removed from category notes" instead of category name.

**Comment by federicoiosue** [comment]
I get a "Category removed from notes", is that what you mean?

**Comment by zzumba** [comment]
would be nice if we can put notes directly to the recycling bin by swiping in a categorie. instead of only removing it from the categorie.
