### ISSUE TITLE
Org mode support

### ISSUE THREAD

**Issue by Immortalin** [federicoiosue/Omni-Notes#235]
It would be awesome if omni-notes can read/write to org mode format files.

**Comment by mourningsun75** [comment]
+1

**Comment by dasheng523** [comment]
+1

**Comment by alexppg** [comment]
Hey, will this be developed? It would be awesome. There's this library that orgzly uses: https://github.com/orgzly/org-java

**Comment by federicoiosue** [comment]
Not on the readmap, but I'll add a label to request contributors.
