### ISSUE TITLE
In Todo lists "add new" button should be at the top of the list (or configurable)

### ISSUE THREAD

**Issue by ssergiienko** [federicoiosue/Omni-Notes#240]
It's very inconvenient to scroll to the end of large list each time when user need to add new item.
Also, if this will be implemented, new items must appear at the top too, so user can see what he add to list.

P.S. Thanks for nice app!

**Comment by federicoiosue** [comment]
Linked on the [right project issue tracker](https://github.com/federicoiosue/CheckListView/issues/11)
