### ISSUE TITLE
Information about tracking

### ISSUE THREAD

**Issue by daleigh** [federicoiosue/Omni-Notes#244]
First of all: Thank you for this great app! I really enjoy using it!

I noticed the app is tracking user behavior. Privacy conscious users might like to be informed of that beforehand. They also might want to know exactly what kind of data is being collected (and why) or even have an option to turn the tracker off.

**Comment by federicoiosue** [comment]
You're perfectly right!

  

Actually all the analytic data are sent throught the open-source
[Piwik](http://piwik.org/) software to a web application that I use to manage
the necessitity of translations and to gain some informations about what
features users use often within the app to apply some development related
considerations.

  

I'll eventually add a disclaimer to check user desire about that.

  

Thanks for your feedback!

> On Jan 20 2016, at 1:14 pm, daleigh &lt;notifications@github.com&gt; wrote:  

>

> First of all: Thank you for this great app! I really enjoy using it!

>

> I noticed the app is tracking user behavior Privacy conscious users might
like to be informed of that beforehand They also might want to know exactly
what kind of data is being collected (and why) or even have an option to turn
the tracker off

>

> —  
Reply to this email directly or [view it on
GitHub](https://github.com/federicoiosue/Omni-Notes/issues/244).![](https://gi
thub.com/notifications/beacon/AAduwOsopvqXnRhVPlOyPB2OBMNgbwbCks5pb3GigaJpZM4H
IjfG.gif)

**Comment by daleigh** [comment]
Thank you for the quick reply! That sounds perfectly reasonable, I'm sure only very few people would have concerns about that. 

As I am new to github: Should I close the issue now? Or only once the disclaimer is in place?

**Comment by federicoiosue** [comment]
I'll close directly by committing the modification :)

> On Jan 20 2016, at 2:40 pm, daleigh &lt;notifications@github.com&gt; wrote:  

>

> Thank you for the quick reply! That sounds perfectly reasonable, I'm sure
only very few people would have concerns about that.

>

> As I am new to github: Should I close the issue now? Or only once the
disclaimer is in place?

>

> —  
Reply to this email directly or [view it on
GitHub](https://github.com/federicoiosue/Omni-Notes/issues/244#issuecomment-17
3207370).![](https://github.com/notifications/beacon/AAduwJFwcRk_TwqAjPDu14KLJ
0OEnER0ks5pb4XjgaJpZM4HIjfG.gif)

**Comment by federicoiosue** [comment]
Closed on 76fad9c88c870a61b82b7d2fba08bb90b1ba8fb0
