### ISSUE TITLE
feature request: after clicking on "+ icon, one can add a "markdown note"

### ISSUE THREAD

**Issue by zaxebo1** [federicoiosue/Omni-Notes#252]
thanks for giving such a best open source note taking app.

**I will like to suggest that - as currently in omninotes, we can click on "+" icon to add a new Photo,Checklist, Textnote. Can a feature be implemented to add a "markdown note/mdnote" too** .

currently mdreader   https://play.google.com/store/apps/details?id=com.npaul.mdreader is an **Open Source app** , which implements adding a markdown based note. It also supports some pandoc extensions to markdown syntax. 
markdownX ( https://play.google.com/store/apps/details?id=com.ryeeeeee.markdownx ) is a closed source , but **material design based** markdown note taking app
textie ( https://play.google.com/store/apps/details?id=com.rstudio.textie ) is also there.

markdown is a lightweight markup language with plain text formatting syntax  ( https://en.wikipedia.org/wiki/Markdown ), so that one can define bold, heading, underline, list, hyperlink etc in lightweight asciitext itself.

As mdreader is open source , so probably it will be easier to implement the same functionality in my loving OmniNote too.

**Comment by zaxebo1** [comment]
in the open source "mdreader" app ( https://play.google.com/store/apps/details?id=com.npaul.mdreader ) , one can enter the normal ASCII text(not the wordprocessing like richtext) as it is in Omninote. Later when  that person clicks appropriate button , then that ASCII text is previewed by **rendering* it as simple html (with bold,underline etc). One can also export the rendered html preview as html/image file in textie app/markdownX app.

**Comment by Coehill** [comment]
Additionally, it would be helpful to be able to convert existing notes to Markdown.

**Comment by federicoiosue** [comment]
Currently the missing markdown support in Omni Notes is [this](https://github.com/federicoiosue/Omni-Notes/issues/735#issuecomment-1986032977).

Of course everything can be done but a big rewrite like that would have a huge cost and would go against the K.I.S.S. approach of Omni Notes.

I'm actually a great fan of markdown, I always use that format to write my work and daily life complex documents, but ON is made for a different purposes: it relies on simplicity and nicely structured searching and categorization features. Small notes, eventually linked with tags, organized into categories.
