### ISSUE TITLE
TodoLists broken with 5.2.4

### ISSUE THREAD

**Issue by d-faure** [federicoiosue/Omni-Notes#256]
With the 5.2.4 update, trying to manually sort todolists make the application crash.

**Comment by federicoiosue** [comment]
Could you please add more informations [here](https://github.com/federicoiosue/CheckListView/issues/10) letting also me know if that happens **all the times** or just sometime?

**Comment by federicoiosue** [comment]
Eventually, trying [this](https://play.google.com/store/apps/details?id=it.feio.android.checklistview.demo) app, results you in the same error?
