### ISSUE TITLE
I would like to make a dark theme

### ISSUE THREAD

**Issue by james-murphy-dev** [federicoiosue/Omni-Notes#259]
What resources would I need for this?

**Comment by federicoiosue** [comment]
It's already on the readmap (see #70) but I've not looked at nothing about that so I still can't be of any help

**Comment by landry314** [comment]
7 years later! we need a dark theme!

**Comment by landry314** [comment]
oh, this is being discussed in issue #70

**Comment by federicoiosue** [comment]
Yes, let's get the discussion into a single issue
