### ISSUE TITLE
Simple way to split note

### ISSUE THREAD

**Issue by energister** [federicoiosue/Omni-Notes#267]
It's possible to merge multiple notes into one (_Merge_ command in context menu while multiple notes are selected) but there is no simple way to split note by two.
I see it like this: while I'm editing a note I put cursor in the middle of the note, select _Split_ (or may be _Split by two_) in the context menu and as a result get two notes one of which is a content of the initial note that was before the cursor and the other contains the rest part of the initial note.

**Comment by federicoiosue** [comment]
What about attachments?

**Comment by energister** [comment]
There might be several different approaches to attachments and the reminder of the note:
1) ASK USER WHAT TO MOVE. User choose which of the attachments he would like to move to the other note
2) COPY ALL. User then can delete undesired attachments manually.
3) COPY NONE
4) ASK USER WHAT TO COPY (Mix of 1 and 2). User choose which of the attachments he would like to copy to the other note. In the current note attachments are left untouched.

The first one looks like the most user friendly but requires much efforts to implement (because you should definitely offer preview in the dialog).
The second one is the most universal (although it's more suitable for the _Duplicate_ command than for the _Split_). 

As for me I rarely use attachments so the second approach would be good enough.
