### ISSUE TITLE
Strings missing on Crowding

### ISSUE THREAD

**Issue by M2ck** [federicoiosue/Omni-Notes#270]
Strings related to Prettified dates feature (title & summary) are missing on Crowding project.

By the way, could you make a spring cleaning for remove unused strings and add changed strings from Crowding when you have some time please?

**Comment by federicoiosue** [comment]
I've added the missing strings on Crowdin.

About cleaning unused strings well, I'm keeping everything I currently have in case of future needs.

**Comment by M2ck** [comment]
Okay thanks!
