### ISSUE TITLE
Tags with slashes and dots are not recognized

### ISSUE THREAD

**Issue by ssergiienko** [federicoiosue/Omni-Notes#274]
Such tags are not recognized in OmniNotes:

> "#area/ui"

Also, this is true about 

> "#some.tag"

 but it less critical.

P.S. Motivation: this is a very convenient scheme for tag naming that i stole from here https://github.com/kubernetes/kubernetes/issues :)

**Comment by federicoiosue** [comment]
Currently a similar restrictive algorithm to the one used by Twitter is used to validate ON's tags.
Looking at your phrases they're not actually real tags.

Anyhow, thats how things started, but I can't see a reason which prevents me from changing everything and simply accept all the kind of words (without spaces) that start with "#" character.

**Comment by federicoiosue** [comment]
This should work well enough 

![selezione_101](https://cloud.githubusercontent.com/assets/487104/14836124/2a454350-0c0e-11e6-9b5e-6e8b8c7a1ebc.png)

**Comment by ssergiienko** [comment]
> I can't see a reason which prevents me from changing everything and simply accept all the kind of words (without spaces) that start with "#" character

This would be great) The only CONS that I can come up, is that if regexp will be "too wide", then after upgrade people will see in their apps too many new tags. So this feature needs to be well described in release notes, but you know better)

**Comment by ssergiienko** [comment]
v5.2.12 Verified fixed. Thanks!

**Comment by federicoiosue** [comment]
You're very welcome. Thanks for your great feedback!
