### ISSUE TITLE
Bug: search by tag is not working in most cases

### ISSUE THREAD

**Issue by ssergiienko** [federicoiosue/Omni-Notes#277]
OnmiNotes 5.2.10

All tags recognized correctly and present in "search by tag list", but search results are empty if tag is not on the **first** line.

To reproduce bug, create note with content:
(variant 1)
> Some
#tag2

(variant 2)
> \n
> some #tag2

But this will works fine:
Content:
> Some #tag2

Also, if tag in note title - all works fine.

**Comment by federicoiosue** [comment]
It seems to be a regexp issue when querying the database.

**Comment by ssergiienko** [comment]
This case also not covered in tests `public void testGetNotesByTag()`
Maybe something like `note3.setContent("\n some\n #tagged content");` will helps to catch such things

**Comment by ssergiienko** [comment]
Thanks! Looks like fixed in v5.2.11
