### ISSUE TITLE
ON DashClock extension issues

### ISSUE THREAD

**Issue by M2ck** [federicoiosue/Omni-Notes#280]
- Navigation menu button becomes unusable after opening app and then a note from ON DashClock extension.

- I'm using ON DashClock extension via Chronus app and I've seen a new icon in extension list (v5.2.14), this is a nice icon but it doesn't appear on Chronus widget & on DashClock extension list and widget too. See screenshots below
![screenshot_2016-06-04-14-56-31](https://cloud.githubusercontent.com/assets/6850125/15799735/3907f484-2a66-11e6-95ec-2aba0bdd800a.png) 
![screenshot_2016-06-04-14-56-10](https://cloud.githubusercontent.com/assets/6850125/15799738/456ef25e-2a66-11e6-94dd-6b68eaa97a59.png)

**Comment by federicoiosue** [comment]
That's the home launcher shortcut icon to create a new note. 
It's strange to see it there due to the fact that its not declared into the dashclock extension resources

**Comment by M2ck** [comment]
Both bugs fixed with 5.2.15, get back with the ON icon.

**Comment by federicoiosue** [comment]
Perfect, really thanks for your contribution!

**Comment by M2ck** [comment]
You're welcome :smiley:
