### ISSUE TITLE
Image collections in notes get lost

### ISSUE THREAD

**Issue by Robert-Held** [federicoiosue/Omni-Notes#284]
Hi, this happened to me twice now. I had notes with 20 or so images. At one point, the preview of these images is shown, but if you tap them, they are not found (canvas is black). Next, no more images are shown in the note itself and they are nowhere to be found on memory or SD card.

Until now I thought the black canvas is just an error of the app but now I think it indicates that a loss like that is on its way.

Using a Samsung S3 Mini with CyanogenMod 11-20141214 (Android 4.4.4).

**Comment by federicoiosue** [comment]
If you'd be able to provide a logcat that could be very useful!

Many users reported that issue but, due to the fact that no error is thrown, I've never been able to isolate or reproduce it.

Maybe something is logged even if there are no evident errors...

**Comment by Robert-Held** [comment]
Sure, I'll do that.

I don't know any useful apps for that, so unless you have any recommendation, I'm going to try to reproduce this while recording with Logcat Extreme.

**Comment by federicoiosue** [comment]
Every app is the same for that purpose

**Comment by Robert-Held** [comment]
OK, I can finally get this log over to you.
Apparently GitHub's upload is bugged, so here's a link: https://www.magentacloud.de/lnk/0vLipcXd
pass: OmniKnight (insert in the input next to the "Login" button)
You can download it via the arrow down icon at the right.

**Comment by federicoiosue** [comment]
Outdated
