### ISSUE TITLE
Error:(105, 13)failed to resolve  com.github.federico issue:simple gallery:2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by clevermatem** [federicoiosue/Omni-Notes#287]
it looks like there is a problem in this dependency

**Comment by federicoiosue** [comment]
Yes, it seems that Jitpack didn't build it.
I didn't noticed the issue due to the fact that when I built it I've implicitly installed it into my local Maven repo.

I'll give a look to Jitpack to fix.

**Comment by federicoiosue** [comment]
You can use the version 2.0.0 now

**Comment by clevermatem** [comment]
thanks a lot
good work bro
