### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by elioqoshi** [federicoiosue/Omni-Notes#291]
Hi there! I love your app and wanted to offer to help with a new logo in case you are interested :)
Maybe also some UI changes as well.

You can check some of my work at www.elioqoshi.me as well

**Comment by federicoiosue** [comment]
Contributions are welcome. For what concerns UI changes another feature branch contains a complete app overhaul but is still bugged so I'm waiting to release it.

**Comment by familqasimov** [comment]
I'm glad you liked it. I would like to work for logo and other designs in your project.
