### ISSUE TITLE
Re-ordering of items doesn't work with Android N

### ISSUE THREAD

**Issue by dhardtke** [federicoiosue/Omni-Notes#293]
Hey,

since a week or so I am using Android N on my phone and I noticed that re-ordering items by dragging and releasing the handle doesn't work anymore. I can start the dragging, but when I "drop" the handle by releasing my hand the item stays on the same position.

**Comment by federicoiosue** [comment]
Now works correctly on 7.1.x. it seems that was an issue related to framework.

Is this you case @dhardtke?

**Comment by dhardtke** [comment]
Yes, it works now. Good job!

**Comment by federicoiosue** [comment]
Well actually I didn't do anything.

It seemed to me that the cause could have been a framework problem and the
upgrade to Android 7.1 gave me proof of that fact.

Il giorno dom 18 dic 2016 alle ore 15:02 Dominik Hardtke <
notifications@github.com> ha scritto:

**Comment by dhardtke** [comment]
Okay, I got a different device now, that only has Android 7 available.

Are you certain it is related to a bug in the framework you're using and not in the way how you're using it? Maybe Google temporarily changed something in 7.0 and reverted it in 7.1? ...

**Comment by federicoiosue** [comment]
I'm pretty sure about your last phrase. Something has been changed from 6 to 7 and then reverted/fixed from 7 to 7.1.

I made a couple of attempts but didn't digged deeply to really discover what have been changed. 

Also considering the less than 0.4% adoption of Nougat 7.
