### ISSUE TITLE
Lock note text scrambled after password change.

### ISSUE THREAD

**Issue by davepb16** [federicoiosue/Omni-Notes#302]
I only have one locked note (checklist).

I changed my password and checked I could open the locked note. Everything was fine. 

I then decided I wanted a different password and changed it again. 
This time when I opened the locked note, all the text was scrambled. (looked like encrypted text)

I guess the moral of the story would be to backup before changing the omni-note password.

**Comment by tdbe** [comment]
Nice but is it possible to recover the scrambled notes? I know my previous password.

**Comment by federicoiosue** [comment]
@tdbe https://github.com/federicoiosue/Omni-Notes/blob/develop/omniNotes/src/main/java/it/feio/android/omninotes/utils/Security.java#L55
