### ISSUE TITLE
Reminder not working

### ISSUE THREAD

**Issue by andr0n0ss7** [federicoiosue/Omni-Notes#303]
Hello Federico,

I truly love the app. Not in love with it, but almost perfect.
One very troubling and limiting issue I have is that reminders don't work at all.
Not sure why.

Please let me know what data you would need to be able to look into this at any stage.
the phone is a honor6 with android 6.0 and has a custom ui called emui 4.0. This comes with this phone by factory default.

I would be really glad if you could take some time to advise.

and thanks for the great app.

#bug

**Comment by andr0n0ss7** [comment]
With latest update for Nougat it is working fine now.

Thank you very much!

**Comment by federicoiosue** [comment]
Glad to ear that. Kind regards.
