### ISSUE TITLE
No reminders on Huawei devices

### ISSUE THREAD

**Issue by kc853** [federicoiosue/Omni-Notes#305]
Hi, some months ago I reported the problem not getting notifications from ON. Now my Huawei P8 Lite has Android 6 and the problem is still there. So I guess its an issue with the Huawei Emui System. On Google Play someone reported the same for a P9 plus. So no reminders on Huawei devices? In the settings notifications for ON are allowed and ON is in protected apps to run in background. 

Andreas.

**Comment by federicoiosue** [comment]
Fixed on 6.0.5 and later
