### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by andr0n0ss7** [federicoiosue/Omni-Notes#308]
Do you see any chance that a(n optional) folder level structuring could be introduced in Omni-Notes?
I know tagging and categories are there, but I think it would make the layout feel clean with me having a hundred+ notes in there...would look and feel much more organized I think. Would that be difficult to implement? Maybe the pro version could do this?
Category-> Folder-> Note

**Comment by federicoiosue** [comment]
Sincerely not.

That would be a big paradigm change about how the app works and about notes organization and visualization.
