### ISSUE TITLE
commons directory

### ISSUE THREAD

**Issue by arvi** [federicoiosue/Omni-Notes#315]
Hello,

Been studying your app's source code for educational purposes and can't find the commons folder where BaseAttachment and other classes originated e.g
 `import it.feio.android.omninotes.commons.models.BaseAttachment;`.

Just wondering why it's not part of the committed files... it was not even in the .gitignore :smile: 

Thanks!

**Comment by federicoiosue** [comment]
Hi @arvi that classes are on [another project](https://github.com/federicoiosue/Omni-Notes-Commons) to keep separated domain models to that they could be used also for other projects.

**Comment by arvi** [comment]
@federicoiosue I can't thank you enough :smile: , this will help me a lot in studying android devt.

**Comment by federicoiosue** [comment]
You're welcome!
