### ISSUE TITLE
Notification persistence is misleading

### ISSUE THREAD

**Issue by ajvsol** [federicoiosue/Omni-Notes#317]
Various apps have persistent notifications (e.g. Turtl, TinyTravelTracker etc) and these notifications are impossible to remove via swiping or the clear all notifications button.

It doesn't work that way in Omni Notes so I'm not sure how they're persistent notifications if they can just be swiped away.

**How they should work:** Impossible to swipe or clear away. You have to click on each notification individually to enter the note and that will remove the notification.

By the way this is exactly how GTasks persistent notifications works for their reminders too. It helps prevent against accidental swiping or clearing away when all your reminders are urgent and need to be read in full.

**Comment by klawdhfzasjhaa** [comment]
I would like that feature too. It's known as "pinning". See attachment from App "Memorix". This does not require the user to go into the note to remove the pinning. It's done via "Entfernen"-button (remove) below the pin
![screenshot_20170218-123328](https://cloud.githubusercontent.com/assets/2808094/23092967/92cd37ae-f5d6-11e6-874b-a05bcefb4e36.jpg)

Persistent reminders in Omni Notes means, that the reminders are persistent through reboots of the phone.

**Comment by federicoiosue** [comment]
This feature is already on the roadmap: https://github.com/federicoiosue/Omni-Notes/issues/227

For what concerns the current way notifications works they're exactly how they're designed to be. 
Unremovable notifications should only be present if:

- they keep up a service to avoid its killing or as interface to it
- a task is in progress and they're needed to inform the user about its status
- status-bar alternative widget (that's what I'm planning to implement)
