### ISSUE TITLE
Integrate with OpenNoteScanner

### ISSUE THREAD

**Issue by stweller** [federicoiosue/Omni-Notes#321]
First of all, thanks for your great app! To facilitate taking pictures of written notes, it would be great to rely on OCR and some tricks to make the resulting picture more readable. This is exactly done by another great FOSS app: [OpenNoteScanner](https://github.com/ctodobom/OpenNoteScanner). Maybe it is possible to integrate with it so we can use OpenNoteScanner directly to add a note?

**Comment by klawdhfzasjhaa** [comment]
Very nice app recommendation. #OpenNoteScanner. :)
For my usecase it's enough to scan and share the picture with Omni Notes the standard way.

**Comment by federicoiosue** [comment]
@stweller as @klawdhfzasjhaa stated that's the correct way to make Android app interact!

Great app anyway!
