### ISSUE TITLE
Export / Import breaks passwd-protected notes

### ISSUE THREAD

**Issue by github-user-1** [federicoiosue/Omni-Notes#326]
I have Omni-Notes (Google) installed parallel to Omni-Notes-FOSS (F-Droid), exported my notes from ON and imported them into ON-FOSS. The list of notes looks perfectly find, however trying to open a password proteced note in ON-FOSS says the password would be wrong.

I tried everything several times in both ON apps - the password is definitely correct so I reckon there is something broken with Export/Import regarding passwords.

**Comment by callofabir** [comment]
Same problem here. Installed omni note foss, locked a note, backed it up, then uninstalled the app, reinstalled it from f-droid again, and restored from the backup. Now the locked note is note opening even after inserting the right password, and the right forgotten password answer. Its a great note taking app with a lot of functionality, but if the backup doesn't work as expected, it will be frustrating and perhaps dangerous. Currently i didn't locked any important note, so no pain now. But when there will be important info in the note, and locked out forever, that will be painful. So I know you are a busy guy putting a lot of effort and an awesome guy I suppose(the opensource awesome note taking app proves that!), this is a serious issue and I hope you do something about it.

**Comment by paulle** [comment]
I can confirm this issue (Omni-Notes-FOSS (F-Droid)). Android 7.0.
But thank you for Omni-Notes-FOSS on F-Droid.

**Comment by federicoiosue** [comment]
Thanks for the feedback I'll give a look
