### ISSUE TITLE
[Feature Request] 'Title view'

### ISSUE THREAD

**Issue by Rbagman** [federicoiosue/Omni-Notes#327]
A view that only shows titles would be nice.

**Comment by federicoiosue** [comment]
A graphical restyle is going to be done, I'll evaluate this again once it'll be released. Thanks for the feedback!

**Comment by federicoiosue** [comment]
Due to commit https://github.com/federicoiosue/Omni-Notes/commit/4d280c74383634d6a6bcd7c64fb6f5506281ad13 this is no more valid because a note without a title would result as empty text-content note.
