### ISSUE TITLE
Omni Notes FOSS — the title

### ISSUE THREAD

**Issue by alekksander** [federicoiosue/Omni-Notes#328]
hello. first of all thank You for all Your hard work and determination to create this vital application.
personally i'm trying to use only free, open source software, therefore i'm very glad there is FOSS version available. but is the FOSS in the title really necessary? is it going to stay? if not, will i have to export all my notes and move it to next release without suffix in the title, or will it just change name without creating another instance?

**Comment by federicoiosue** [comment]
Hi, I could agree about the fact that it's not so nice where it is right now but I'd like to make very clear what version a user is using.

Currently four builds are already around and not everybody have a clear idea on how to determine which one is using for bug reporting purposes.

**Comment by alekksander** [comment]
Thank You for clarifying.
