### ISSUE TITLE
Crash on startup using version 5.3.1.FOSS from F-Droid

### ISSUE THREAD

**Issue by keunes** [federicoiosue/Omni-Notes#336]
Hi there,
I really like omni notes and use it quite often. Just tried to check on one of my notes, but when I try to open the app, I get only the splash screen and nothing after (return to my Android's homescreen). It did work earlier this week.
- How to save my notes?
- How can I help in debugging this issue?

Device: Fairphone 2;
OS: Android 5.1;
App: Omni Notes 5.3.1 via F-Droid

**Comment by federicoiosue** [comment]
Hi, does this happens all the times?
What about if you try to reinstall the app?

I got the following error
```
java.lang.VerifyError: Rejecting class it.feio.android.omninotes.MainActivity because it failed compile-time verification (declaration of 'it.feio.android.omninotes.MainActivity' appears in /data/app/it.feio.android.omninotes-1/base.apk)
	at java.lang.Class.newInstance(Native Method)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2335)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
	at android.app.ActivityThread.access$900(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5451)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by g12265080** [comment]
I got the same issue after upgrading to 5.3.1.
Yes, it happens every time. How can I save my notes before reinstalling the apps?

**Comment by federicoiosue** [comment]
Device and OS @g12265080?

**Comment by federicoiosue** [comment]
@keunes, @g12265080 to manually backup notes you have to be rooted, is this your case?

**Comment by g12265080** [comment]
My device is Huawei Mate 9 Pro and OS is Android 7.0.
I'm not rooted though.

**Comment by g12265080** [comment]
My notes are just a few and not so important. But I'm afraid for those who have lots of important notes.

**Comment by federicoiosue** [comment]
> But I'm afraid for those who have lots of important notes.

Luckly just a crash from an _Asus Z00ED_ has been reported (maybe @keunes' device, but I have an OS version 6.0.1)

**Comment by g12265080** [comment]
I thought @keunes' device is Fairphone2.

**Comment by federicoiosue** [comment]
@keunes, @g12265080 could you please try to install [this](https://drive.google.com/open?id=0B0nF1sdYwc1lZkZkcFJTaWkxbWs) build?
it's pretty much the same version you already have installed, just built for F-Droid store.

Does this build have the same issue?

**Comment by g12265080** [comment]
Actually I'm using the latest build in F-droid store.

**Comment by federicoiosue** [comment]
Mmmhhh I've installed latest from F-Droid and I got app's hang with following error:

```
03-08 19:42:46.162 E/ACRA    (8643): ACRA caught a RuntimeException for it.feio.android.omninotes.foss
03-08 19:42:46.162 E/ACRA    (8643): java.lang.RuntimeException: Unable to start activity ComponentInfo{it.feio.android.omninotes.foss/it.feio.android.omninotes.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void it.feio.android.analitica.AnalyticsHelper.trackScreenView(java.lang.String)' on a null object reference
03-08 19:42:46.162 E/ACRA    (8643): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2680)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.os.Looper.loop(Looper.java:154)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.app.ActivityThread.main(ActivityThread.java:6169)
03-08 19:42:46.162 E/ACRA    (8643): 	at java.lang.reflect.Method.invoke(Native Method)
03-08 19:42:46.162 E/ACRA    (8643): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
03-08 19:42:46.162 E/ACRA    (8643): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
03-08 19:42:46.162 E/ACRA    (8643): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void it.feio.android.analitica.AnalyticsHelper.trackScreenView(java.lang.String)' on a null object reference
03-08 19:42:46.162 E/ACRA    (8643): 	at it.feio.android.omninotes.BaseFragment.onStart(BaseFragment.java:13)
03-08 19:42:46.162 E/ACRA    (8643): 	at it.feio.android.omninotes.ListFragment.onStart(ListFragment.java:150)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.support.v4.app.Fragment.performStart(Fragment.java:2000)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2051)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:185)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:608)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.app.Activity.performStart(Activity.java:6696)
03-08 19:42:46.162 E/ACRA    (8643): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2643)
03-08 19:42:46.162 E/ACRA    (8643): 	... 9 more
03-08 19:42:46.413 E/ACRA    (8643): Not adding buildConfig to log. Class Not found : it.feio.android.omninotes.foss.BuildConfig. Please configure 'buildConfigClass' in your ACRA config
```

**Comment by klawdhfzasjhaa** [comment]
+1 for the instant crash on LineageOS 14.1 on Nexus 6P with root access.
I was not able to recover my notes by backing up the database files and copying them back after reinstallation of the older version nor the new one.

**Comment by keunes** [comment]
> Hi, does this happens all the times?

Yes, it does unfortunately

> @keunes, @g12265080 to manually backup notes you have to be rooted, is this your case?

Nope, so manual back-up isn't possible :S

> Luckly just a crash from an Asus Z00ED has been reported (maybe @keunes' device, also if I have an OS version 6.0.1)

Nope, @g12265080 correctly noted my device is a Fairphone 2

> @keunes, @g12265080 could you please try to install this build?
it's pretty much the same version you already have installed, just built for F-Droid store.

I also have the app installed via the F-Droid app store

Hope you can find out what the issue is. If somehow I can get you any helpful info, please let me know. I really hope we can save our notes :/

**Comment by federicoiosue** [comment]
Notes are safe where they are for now.

I found the issue and release a bugfix release ASAP.

**Comment by alekksander** [comment]
same issue here, but it seems to be already taken care of.
thanks!

**Comment by krmboya** [comment]
Same issue here. Have you pushed the version with the bugfix to F-droid? 

I'm on version 5.3.1, which appears to be the latest on the F-droid repositories.

**Comment by federicoiosue** [comment]
Still not @krmboya, I've just made a pull request to temporary disable the 5.3.1 build until fixed

**Comment by krmboya** [comment]
Oh, alright @federicoiosue. Also thanks for Omni notes.

**Comment by reno-a** [comment]
Hello,
I have the crash with vetsion 5.3.1 F-Droid deposit.
Can you ask to F-Droid for watch it?

**Comment by reno-a** [comment]
Hello,
I have the crash with version 5.3.1 F-Droid deposit.
Can you ask to F-Droid for watch it?
Thank-you

**Comment by federicoiosue** [comment]
The issue has been fixed and a [merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/2093) to release the new version on F-Droid has been made.

**Comment by reno-a** [comment]
Thank-you Federico for your answer.
...and bravo for this effective application.

**Comment by reno-a** [comment]
Upgrade from F-Droid OK today.
Thanx again.

**Comment by federicoiosue** [comment]
Update should have solved everything.
No manual intervention were needed!
Could you provide a logcat or more info on your device to help me digging into crash reports?

**Comment by federicoiosue** [comment]
Omni Notes [version 5.3.2](https://f-droid.org/repo/it.feio.android.omninotes.foss_233.apk) fixed the issue.

As stated before @klawdhfzasjhaa no manual intervention is needed to restore functionalities. 
Just update to the latest version using F-Droid or by manually upgrading apk.

**Comment by klawdhfzasjhaa** [comment]
I extracted the notes with a SQL viewer and recreated them. Thanks for the app! 👍
