### ISSUE TITLE
Add Opt-out for analytics to the app tour

### ISSUE THREAD

**Issue by mark-orion** [federicoiosue/Omni-Notes#344]
I notice that the collection of anonymous usage data is enabled by default and there is no notice that tells the user about this. It is not only that I oppose this practice personally, it may even violate data protection regulations in some countries. So I request that either this feature is disabled by default and / or as it is common practice a privacy note that explains how to turn the feature off is added to the app tour that shows up on the first run of the application.

**Comment by federicoiosue** [comment]
> privacy note that explains how to turn the feature off is added to the app tour that shows up on the first run of the application.

Approved

**Comment by inson1** [comment]
I would rather see opt in

**Comment by federicoiosue** [comment]
There is no need actually @inson1, because there are no analytics at all!
