### ISSUE TITLE
Password-protected backup broken

### ISSUE THREAD

**Issue by privacy-wolf** [federicoiosue/Omni-Notes#345]
I have both flavours installed (from Google and F-Droid) and wanted to migrated to the FOSS version. Doing a backup and an import is working in principle, however the password protection seems to be broken: the imported notes don't recognize the password to unlock them. I tried everything twice and double-checked every step, so I'm quite sure it's not a mistake on my side.

I suggest to make this a top priority as this might potentially lead to data loss (notes can only be read with the old Google setup; once deleted the note might be locked for good in the F-Droid version).

**Comment by federicoiosue** [comment]
Hi @privacy-wolf,

the fact is that the applications have some structural differences and backups are not completely interchangeables.

To fix your specific problem you have to:
1. Go into your copied backup folder (right into the *Omni Notes Foss* folder)
2. Rename the file *it.feio.android.omninotes_preferences.xml* into *it.feio.android.omninotes**.foss**_preferences.xml*
3. Repeat backup restore process from inside the app

**Comment by privacy-wolf** [comment]
Hmm - I'm a bit puzzled. When I do a backup from Omni-Notes the file generated has the file name (suggested by Omni-Notes like e.g. 2017.03.14-11.11). I move this backup file into the Omni-Notes-Foss folder and can import it from there into Omni-Notes-Foss. All notes do show up (password-protected and unprotected ones). I can open the unprotected notes. If I click the password-protected notes it askes (correctly) for the password. However Omni-Notes-Foss doesn't accept the password - I'm really very much sure the password is correct (I tried several times in Omni-Notes where it workes nicely and Omni-Notes-Foss where the password is rejected).

**Comment by federicoiosue** [comment]
Did you renamed the XML file contained into the backup folder you moved?

**Comment by privacy-wolf** [comment]
Yes, if finally worked out - there was an issue with "amaze" not copying a file (no idea why it skips the xml file) and a type. But now it works and I could uninstall the Google version. Many thanks!

**Comment by federicoiosue** [comment]
Glad it worked @privacy-wolf
