### ISSUE TITLE
Prevent the "App Tour" from appearing after an upgrade

### ISSUE THREAD

**Issue by TheDcoder** [federicoiosue/Omni-Notes#346]
Hello! Today I upgraded Omni Notes FOSS (F-Droid) and I was surprised to see the app tour after launching a shortcut for a note on my home screen. After finishing the tour, Onmi Note created a blank note... I had a heart attack when I saw the blank note, I thought that my note was deleted! 😞

After pressing the back button I was relieved to see my notes 😥. So I think it would be good if the "App Tour" doesn't show up after an upgrade.

**Comment by federicoiosue** [comment]
Quite strange, once app tour has finished a setting is saved to avoid its start on following app's starts.

I'll dig into it, thanks.

**Comment by TheDcoder** [comment]
Looking forward for the fix :)

**Comment by federicoiosue** [comment]
I just made a fast attempt to identify the issue.

It's due to a previous made in the FOSS version of the app. It just happened when upgrading from 5.3.1 but now it's already fixed.

**Comment by TheDcoder** [comment]
Oh, so I guess this issue can be marked as "resolved" and can be closed :)
