### ISSUE TITLE
check list font color

### ISSUE THREAD

**Issue by wintermutecx** [federicoiosue/Omni-Notes#355]
Can you add an option to change the font color/striking for checked items? 

For check lists, I use a check mark for things I need to do or get, not that they are finished. Reverse of actual paper check lists I suppose.

**Comment by federicoiosue** [comment]
This could eventually be suitable for [ChecklistView library](https://github.com/federicoiosue/checklistview) (but will not implemented by me due to too much specific implementation that is not matching material design guidelines)
