### ISSUE TITLE
Where to place backup

### ISSUE THREAD

**Issue by keunes** [federicoiosue/Omni-Notes#360]
Hello,

Before I upgraded Android from 5 to 6, I made a backup of Omni Notes data - luckily as indeed something went wrong and I had to do a factory reset. Now: where do I have to put the backup on the phone, so that ON will recognize it when in the menu I choose 'restore backup'. Also, should I have a zip file or the 'files' folder, and the preferences and notes database seperately, or together in a zip file? (I have both on my computer - don't know if I zipped/unzipped it or if it was that way originally).

**Comment by federicoiosue** [comment]
Hi Koen,

you should copy the entire* [sdcard]/Omni Notes* folder with all its
content. Inside it you'll find the database file, the settings xml, and an
inner folder containing all the attachments.

Kind regards,
Federico

Il giorno mar 2 mag 2017 alle ore 00:40 Koen Glotzbach <
notifications@github.com> ha scritto:

**Comment by federicoiosue** [comment]
Hi Koen,

you should copy the entire **[sdcard]/Omni Notes** folder with all its
content. Inside it you'll find the database file, the settings xml, and an
inner folder containing all the attachments.
