### ISSUE TITLE
How it is generated this dialog box once you install de apk release?

### ISSUE THREAD

**Issue by josu09** [federicoiosue/Omni-Notes#367]
Hellow!
I dont know if this part is correct..
I have a question. Does someone know in what class , .xml or how is generated this message box?
![img-20170507-wa0010](https://cloud.githubusercontent.com/assets/28611384/25924597/c59167c8-35a0-11e7-8d6a-68974510cfe5.jpg)

**Comment by federicoiosue** [comment]
Hi @josu09, sorry for the late reply. The dialog is generated by using [this](https://github.com/gabrielemariotti/changeloglib) great library.

**Comment by josu09** [comment]
Thank you very much @federicoiosue !

**Comment by federicoiosue** [comment]
You're welcome!
