### ISSUE TITLE
Note reminder still triggers after it was removed

### ISSUE THREAD

**Issue by alxbalmus** [federicoiosue/Omni-Notes#374]
How to reproduce:
1. Create a note with a reminder
2. Before the reminder set time is reached open the note again and long-press delete the reminder from the note
3. Trash the note via the "three points" menu form inside the note or via selecting it with "long press" from the list and using the "three points" menu from the list
4. The reminder will fire at the set time and the note will show up again in the list

Extra question:
How do I trash a note from the list via sliding? Sliding seems to send the archive?

**Comment by alekksander** [comment]
makes omni notes very unreliable for people who use it as a reminder application (or simply those with simply a lot of reminders)
