### ISSUE TITLE
Recurring reminders, calendar?

### ISSUE THREAD

**Issue by anti-todo** [federicoiosue/Omni-Notes#38]
A nice enhancement to the reminder system would be the ability to select daily, weekly, etc. reminders for notes. Also is there plans for a more built in calendar like Colornote has? I would love to switch from colornote to omni. It would also be nice to change the sorting of categories/colors

And a question, are notes/database encrypted? 

Thanks

**Comment by federicoiosue** [comment]
Recurrent reminders implemented
