### ISSUE TITLE
Wrong restoring from Trash with reminder

### ISSUE THREAD

**Issue by cabagge** [federicoiosue/Omni-Notes#381]
I'm not sure if this is duplicated, but I also found some not standard behaviour with Note with reminder.
Note is not correctly restored from the Trash.

1. Create an Note.
2. Add reminder (to be fired e.g. in 3 minutes)
3. Move note to trash. (Long press, --> Three dot menu --> Trash)
4. After 3 or more minutes, reminder is **not** triggered --> That's **OK**
5. Now look to trash, Note is there.
6. Swipe note --> to restore it from trash. Information bar about restoring the Note is shown. And Note realy disappear from trash. OK.
7. Now immediatelly, reminder is triggered in notifycation android menu. (**Not** really sure if this is ok)
8. Now back to the application, and Note is **still** in Trash. --> **That's wrong.** I suppose it should be restored.

**Comment by federicoiosue** [comment]
Bug confirmed. Thanks for the really detailed workflow to reproduce!

I'm already working on this.
