### ISSUE TITLE
Constants class under utils do not exists

### ISSUE THREAD

**Issue by jackengine** [federicoiosue/Omni-Notes#382]
On develope branch utils.Constants not found

**Comment by federicoiosue** [comment]
You mean [this](https://github.com/federicoiosue/Omni-Notes/blob/develop/omniNotes/src/play/java/it/feio/android/omninotes/utils/Constants.java)?

Pay attention to the fact that this file is under a flavor-package

**Comment by jackengine** [comment]
Yeah, that one.
Thanks to point out.
