### ISSUE TITLE
Feature Request: Calendar view

### ISSUE THREAD

**Issue by Wiredframe** [federicoiosue/Omni-Notes#392]
Hi Federico, 

it would be awesome if we could have a calendar view, so Omni Notes could be used as a Diary. 

Attached is a screenshot from the app "Journey":
![image](https://user-images.githubusercontent.com/13737875/31348546-4e167a9c-ad20-11e7-975a-c3efd38952cb.png)

What do you think?

**Comment by mrAl-x** [comment]
Oh this would be sweet!

**Comment by federicoiosue** [comment]
Is a really good feature, but not actually on the roadmap due to the different goal the two apps have.
