### ISSUE TITLE
android.text.format.Time is deprecated

### ISSUE THREAD

**Issue by frankFic** [federicoiosue/Omni-Notes#396]
Another thing, the [Time class](https://developer.android.com/reference/android/text/format/Time.html) has been deprecated since API 22 due to multiple reasons. It is still in use in DateHelper. As suggested by the document, GregorianCalendar could be an alternative for it.

**Comment by federicoiosue** [comment]
Hi, the problem is that the library currently used to implement recurrent reminders dialog uses that class!
