### ISSUE TITLE
Crash when archiving multiple notes

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#400]
Happens on 5.4.0 internal-only beta.

Problems with multithreading on DB connections?

`11-05 23:10:43.221 E/ACRA    ( 1107): ACRA caught a IllegalStateException for it.feio.android.omninotes
11-05 23:10:43.221 E/ACRA    ( 1107): java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:982)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:678)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:349)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:1032)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:972)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at it.feio.android.omninotes.db.DbHelper.getNotes(DbHelper.java:477)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at it.feio.android.omninotes.db.DbHelper.getNotesActive(DbHelper.java:349)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at it.feio.android.omninotes.extensions.ONDashClockExtension.getNotesCounters(ONDashClockExtension.java:115)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at it.feio.android.omninotes.extensions.ONDashClockExtension.onUpdateData(ONDashClockExtension.java:63)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at it.feio.android.omninotes.extensions.ONDashClockExtension$DashClockUpdateReceiver.onReceive(ONDashClockExtension.java:139)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.os.Looper.loop(Looper.java:154)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at android.app.ActivityThread.main(ActivityThread.java:6311)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at java.lang.reflect.Method.invoke(Native Method)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
11-05 23:10:43.221 E/ACRA    ( 1107): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
11-05 23:10:43.544 E/ACRA    ( 1107): Not adding buildConfig to log. Class Not found : it.feio.android.omninotes.BuildConfig. Please configure 'buildConfigClass' in your ACRA config`

**Comment by inzkhan** [comment]
Why is this issue still opened if it has been fixed in version 4.5.3?
