### ISSUE TITLE
Only plaintext option

### ISSUE THREAD

**Issue by westurner** [federicoiosue/Omni-Notes#405]
When I copy/paste HTML-formatted text from a browser to an Omni Notes note, it preserves some formatting; but there's no way to remove it?

(IIRC, it used to strip formatting; which is great for preparing plaintext emails)

If this is a new feature, is there a way to switch it off either globally or per-note?

**Comment by federicoiosue** [comment]
Actually is just an impression: when you save the note and open it back again the text formatting will be gone.

This happens due to the default behavior of the TextView element.

**Comment by westurner** [comment]
Thanks!

**Comment by westurner** [comment]
Is there a way to strip formatting on paste? (The GitHub textareas seem to do this but not e.g. GMail textareas)

**Comment by federicoiosue** [comment]
There are many methods but all of them are processing consuming and could bring to problems to (for example) url-parsing that actually creates some formatted areas into the text fields.

So I'd just consider this a minor misbehavior without trying to fix it.
