### ISSUE TITLE
Need а new font

### ISSUE THREAD

**Issue by wolf373** [federicoiosue/Omni-Notes#413]
The current font does not align the digits if you write to a column
11-00 First step
20-00 Second step

Need to make as here

**Comment by federicoiosue** [comment]
What you're asking for is a monospaced font.

This is a different goal than the one targeted by this app: Omni Notes actually aims to bring to users a simple and fluid-layout based note taking tool. Monospaced is quite a technical font nowadays, that's why is not on the developments roadmap!
