### ISSUE TITLE
Widget should be top justified not centered.

### ISSUE THREAD

**Issue by yesmar12** [federicoiosue/Omni-Notes#420]
Currently the widget is centered like so: 
![screenshot_20171230-115445](https://user-images.githubusercontent.com/15841504/34455962-8da5debe-ed58-11e7-88d4-24ee95d6eadd.jpg)
The widget should be aligned at the top.
Version: 5.3.2

**Comment by richardzhanguw** [comment]
#423

**Comment by richardzhanguw** [comment]
#423 should solve this issue.

**Comment by federicoiosue** [comment]
Good job @richardzhanguw !
