### ISSUE TITLE
tag need has structure like tree or graph/net

### ISSUE THREAD

**Issue by freelogic** [federicoiosue/Omni-Notes#422]
one flat tag is lack to express more complex of real world situation， same to doc and notes. my suggestion is develop structured tag system, support net topology or cascade tree.
some philosophy use to classification and sort. adding these features 
then,
tobe the next facebook or better.
goodluck

**Comment by federicoiosue** [comment]
This is a nice idea but is far beyond the goals of this app that aims to stay under the [KISS philosophy](https://en.wikipedia.org/wiki/KISS_principle)
