### ISSUE TITLE
Notes deleted on Update

### ISSUE THREAD

**Issue by random11** [federicoiosue/Omni-Notes#424]
OmniNotes auto-updated from Play Store. Upon opening app, all notes were gone. :( I didn't have a backup (I know, stupid and my fault). Is there any way to recover the notes? Thanks.

Device: Blu R1 HD
Android 6.0
OmniNotes: 5.4.1

**Comment by federicoiosue** [comment]
Ok, no panic.

First of all: maybe your boys are still there but the app doesn't shows them to you... is your device rooted (this would help in searching them!)?

**Comment by random11** [comment]
Wow, thanks for the quick response. :) My device isn't rooted.

**Comment by random11** [comment]
If possible, please let me know how I should proceed. I will be checking this thread. Thanks. :)

**Comment by federicoiosue** [comment]
Sorry I can't see any error here (did you kept enabled the sending errors switch into settings?) as you can see from the screenshot.

![20180108_23 50 37](https://user-images.githubusercontent.com/487104/34696416-03d75388-f4cf-11e7-8e64-24c0b8a10e31.png).

I just filtered by OS 6.0, ON version 5.4.1 and date > 1 january... is this right?

**Comment by random11** [comment]
It was disabled. I have enabled it for future reference. I appreciate your help. I will definitely make backups this year. :)

**Comment by federicoiosue** [comment]
Sorry to hear that. Don't exitate in asking help here on Github if you need.
