### ISSUE TITLE
cross to temove line is buggyHi,

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [federicoiosue/Omni-Notes#426]
Hi,

I keep noticing that the cross that appears on the right of an item in a list to remove it doesn't appear for the one at the bottom. It is not systematic and I can't figure out what causes it for now.

Here's a picture emphasizing which cross I'm talking about :
![screen](https://user-images.githubusercontent.com/26625900/34905249-a261c774-f84c-11e7-9c6a-fb734bbd94aa.png)
*And yes in the screen cap the cross is for the penultimate item, not the one at the bottom. My issue is that sometimes the one at the bottom doesn't appear and I have to manually select another one and then comeback to the last one*

**Comment by federicoiosue** [comment]
Hi, actually that's a desired behavior.

There is no sense in deleting the line you're currently writing into. In this case you could just delete the text by using the keyboard.

**Comment by thiswillbeyourgithub** [comment]
Oh how surprising. It's so much *slower* to delete it character by character so i figured it would make sense to use the cross. I'll let that up to you to decide then :)
