### ISSUE TITLE
Three 'trash' strings - two can be merged

### ISSUE THREAD

**Issue by keunes** [federicoiosue/Omni-Notes#428]
We need one verb and one noun string for 'trash'. Verb should be used in the three-dot menu & the category edit screen; the noun should be used only in the hamburger/slide navigation menu. Currently, there are three strings.

https://crowdin.com/translate/omni-notes/all/en-nl#538 ('Prullenbak') -> used in the note and note overview three-dot menu
https://crowdin.com/translate/omni-notes/all/en-nl#566 ('Rommel') -> used in the (slide) navigation menu
https://crowdin.com/translate/omni-notes/all/en-nl#723 ('Verwijderen') -> used in the category edit screen

Please remove either of the string that should be a verb (three-dot menu or hamburger menu). And clearly note what the remaining strings should be noun/verb.

(Maybe introduced with #334.)

**Comment by federicoiosue** [comment]
I've removed https://crowdin.com/translate/omni-notes/all/en-nl#723
The first one has been contextualized as a verb
