### ISSUE TITLE
List auto-complete

### ISSUE THREAD

**Issue by supermamie** [federicoiosue/Omni-Notes#430]
I usually use list for shopping, and I usually buy the same things.
My problem is that this list is quite long and it's a pain to find something in it (and be sure the thing I want to add isn't somewhere down the list, already checked from a previous action).

It would be nice to add some auto-completion from already checked items of the list.

Here is a screenshot of another app that does this (if it can help)
![image](https://user-images.githubusercontent.com/693751/35276675-725f8c46-0044-11e8-8069-b05f622fafdf.png)

**Comment by federicoiosue** [comment]
I close the issue to keep the board clean, but I've added [Help wanted](https://github.com/federicoiosue/Omni-Notes/issues?utf8=%E2%9C%93&q=label%3A%22Help+wanted) label to indicate that contributors are able to work on this task too (even if closed)
