### ISSUE TITLE
Add persian jalali cal

### ISSUE THREAD

**Issue by biomanw** [federicoiosue/Omni-Notes#433]
Please add persian jalali cal to this awesom app i like it 
You can see jalali cal in bamdad cal that is use a fork of omni note 
Thanks

**Comment by biomanw** [comment]
Bamdad persian cal :
https://github.com/soheilnikbin/Bamdad-Persian-Calendar-

**Comment by federicoiosue** [comment]
Hi, you should send me a request to participate to the translation project by using Crowdin (the link is on the README). Thanks for the feedback!
