### ISSUE TITLE
Add timestamp to note content

### ISSUE THREAD

**Issue by azzamsa** [federicoiosue/Omni-Notes#435]
Thank you for this awesome app.

Can we have a feature like adding timestamp to note. e.g : 
- when we write #today. Omni-Notes will replace that with current day and dates
- #now. dates and times

I really miss this feature, because I often need many timestamp in one documents.

Thanks lot for your contribution to community.

PS: *this feature implemented in FiiNote.*

**Comment by federicoiosue** [comment]
I'll leave this opened to check the insterest on the argument

**Comment by federicoiosue** [comment]
@aimanbaharum altro tried here  https://github.com/federicoiosue/Omni-Notes/pull/319

**Comment by federicoiosue** [comment]
I close the issue to keep the board clean, but I've added **Help Wanted** label to indicate that contributors are able to work on this task too (even if closed)
