### ISSUE TITLE
Crash when typing text to the title/content of a new note with Robotium

### ISSUE THREAD

**Issue by destinyfucker** [federicoiosue/Omni-Notes#441]
I am using Robotium to try a test on Omni-Notes, version 5.4.1.However, it crashed when I tried to use method 'typeText' to input title/content for a new note(which uses the method  'sendStringSync' of Instrument).
The crash information given by Robotium is :
longMsg=java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.inputmethod.InputConnection.finishComposingText()' on a null object reference.

I'm wondering why it happened, and is it a bug of Omni-Notes or Robotium?

**Comment by federicoiosue** [comment]
Well actually I should see the whole code you're testing.
Anyway, due to the fact that I migrated Omni Notes to Espresso I reccomend you to do the same!

**Comment by destinyfucker** [comment]
The Robotium test scripts are like these:
        view = solo.getView("it.feio.android.omninotes:id/fab_expand_menu_button");
        solo.clickOnView(view);
        solo.sleep(1000);
        view = solo.getView("it.feio.android.omninotes:id/fab_checklist");
        solo.clickOnView(view);
        solo.sleep(1000);
        view = solo.getView("it.feio.android.omninotes:id/detail_content");
        solo.typeText((EditText)view, "new content");

However, I tried the event with APIs of UiAutomator and Espresso these days, the crash did not happened.I think it may be the problem of Robotium and usage of method 'sendStringSync', i will look into it in the next days.
