### ISSUE TITLE
Can't submit project to Sonarqube

### ISSUE THREAD

**Issue by inzkhan** [federicoiosue/Omni-Notes#442]
Here's the error,i am getting while building the project 
Execution failed for task ':sonarqube'.
> You're only authorized to execute a local (preview) SonarQube analysis without pushing the results to the SonarQube server. Please contact your SonarQube administrator.

**Comment by federicoiosue** [comment]
This depends on where you have your sonarqube instance I suppose!

**Comment by inzkhan** [comment]
I removed sonarqube because it wasn't working for me, Anyways thanks for the reply.
