### ISSUE TITLE
Keyboard covering text

### ISSUE THREAD

**Issue by scoloco2** [federicoiosue/Omni-Notes#443]
When taking a text note, the keyboard (both Swiftkey and Gboard) cover the text where I am typing.

![screenshot_20180305-073713](https://user-images.githubusercontent.com/37063825/36962711-85acbb92-2048-11e8-9476-5bf208ec8d23.png)

The screenshot above has the cursor behind the keyboard and the text can't scroll to see what is being typed.

This is on a Moto G5 running Android 7.0.

**Comment by federicoiosue** [comment]
Tested and confirmed on Moto G4 using Android 7. It doesn't behave the same way using other Motorola devices (like Motorola RAZR HD XT925) or OnePlus, Samsung and LG smartphones so I suppose is something strictly related with the framework included into some models.

Not that easy to fix without a device to work on so I'll label as **wontfix** and **Help Wanted** to look if other developers have easier way to dig further into.
