### ISSUE TITLE
wrong isPasswordAccepted implementation?

### ISSUE THREAD

**Issue by cabagge** [federicoiosue/Omni-Notes#444]
I found, that after app leaving (onBackPressed) app goes to the background.  After second app activation (e.g. tap on icon OmniNotes)  - I don't know why, **isPasswordAccepted** is set to true. 

```
if (!isPasswordAccepted) {
            // This method starts the bootstrap chain.
            checkPassword();
}
```

But it means, `init()` is not called at all.
Then app behaviour is then undefined and on exit (onBackPressed) is null pointer `mFragmentManager ` in `finishActionMode()` raised

```
public void finishActionMode() {
        ListFragment fragment = (ListFragment) mFragmentManager.findFragmentByTag(FRAGMENT_LIST_TAG);
        if (fragment != null) {
            fragment.finishActionMode();
        }
    }
```

It could be fixed in `onStop()` by setting the  **isPasswordAccepted = false**
```
@Override
	protected void onStop() {
		super.onStop();
                isPasswordAccepted = false;    //  FIX *****
		EventBus.getDefault().unregister(this);
	}
```
I don't know if you can reproduce it, I have android 4.4.2 ;)

**Comment by federicoiosue** [comment]
You're right, it's a regression bug due to a (programmatically) untested pull request.

I'll put a patch asap

**Comment by federicoiosue** [comment]
Also I have another related issue just on some devices of the many I tested (Nexus and emulators, that are based on stock Android code): when I leave the app by backpressing I'm not able to see notes' list again when I'm back into the app itself.

**Comment by cabagge** [comment]
Yes, empty list is the issue. 
I test it on Acer Z500 with Android 4.4.2. I checked it under different settings:
Settings -> developer options -> Don't keep activities = true / false
But the error is present in both cases.
The same behaviour is on Note 4, with Android 6.0.1

Thank you very much for the fix. Hopefully it will work now.
