### ISSUE TITLE
keyboard disappears after rotation

### ISSUE THREAD

**Issue by nikoss** [federicoiosue/Omni-Notes#445]
hi,
as the title says...

How to reproduce:
+ Create a text note 
+ Create content with many lines
+ Touch somewhere in the text...
    The keyboard will pop up
+ Rotate your phone...
    The keyboard will vanish.
    You have to find where you were last editing,
     and touch again for the keyboard to reappear
+ That happens every time you rotate your phone

I use version 5.4.3

**Comment by federicoiosue** [comment]
This happens for a serie of implementations made lot of time ago to improve display usage by making the navbar transparent and to dinamically change the available space to write on when keyboard appeared.

This wikk be changed when the new interface will be released but is not applicable right now.
