### ISSUE TITLE
shortcut to search all unfinished task list in all memos

### ISSUE THREAD

**Issue by rifh2000** [federicoiosue/Omni-Notes#458]
Hi Federico,

First, allow me to thank you regarding this useful, simple to use, and working apps.

Second, I would like to request new function that allow us to see all of our unfinished tasks, in all of our memos. 

This way i will able to see my latest unfinished task in one click, unlike now where i have to open each memo to find out.

thx,
Arif

**Comment by federicoiosue** [comment]
Nice idea, I'll add to the roadmap for the next release (not the next bugfix one but the next one that will come with new features). Thanks

**Comment by federicoiosue** [comment]
There is still a problem white coming back to notes list after editing an unfinished checklist: the list itself results to be empty
