### ISSUE TITLE
Change reminders behavior to avoid always asking recurrence

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#464]

**Comment by Dima-1** [comment]
What are you mean "always asking recurrence"? Remove "add reminder" on the notification drawer?

**Comment by federicoiosue** [comment]
I don't use that much recurrent reminders actually, while I use a lot one-time reminders instead. So is quite annoying for to always have to spend one more click just to pass the actually existing recurrence dialog without event enabling it.

One possibility could be to switch to another third party library like [this](https://github.com/vikramkakkar/SublimePicker) **and** to implement in a different way the current management of recurrence.

I should dig a little further into the code to remember how it worked anyway, this was just a placeholder.

**Comment by federicoiosue** [comment]
Also pay attention to implement the new pickers paying attention to [set a minimum date/time](#496)

**Comment by federicoiosue** [comment]
Solved with https://github.com/federicoiosue/Omni-Notes/commit/6f40e1b4a2a3408144b1e27100e56088909692b4
