### ISSUE TITLE
other calendars

### ISSUE THREAD

**Issue by herotux** [federicoiosue/Omni-Notes#466]
we are live in Iran and need Persian calendar we don't use Gregorian we dont understant it commonly.
maybe you can add an option to other calendars like persian jalali cal 
in Bamdad app that use omni notes developers make it availble maybe you can Inspiration them

https://github.com/soheilnikbin/Bamdad-Persian-Calendar-/tree/master/PersianCalendar/src/main/java/com/omninotes

**Comment by federicoiosue** [comment]
I'll give a look to the project you reported but this is actually a too much specific implementation to be included into the app's roadmap.

Just for curiosity: other company-made apps like Google Keep how manage this thing?

**Comment by biomanw** [comment]
Companies are looking for profits and do not care for the community as a whole, so they do not pay attention to Persian speakers, which account for a small percentage of the world's population, which is why we only find this opportunity sometimes in free and open source programs.

**Comment by biomanw** [comment]
maybe this links help us:

https://github.com/mfathi91/persian-date-time


https://github.com/samanzamani/PersianDate

https://github.com/mohamad-amin/PersianMaterialDateTimePicker


https://stackoverflow.com/questions/10378764/is-there-any-library-or-algorithm-for-persian-shamsi-or-jalali-calendar-in-and?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by biomanw** [comment]
hi
Please see this link:
This is a messenger app that support shamsi hijri and gregorian
Maybe can help for add other calendar i hope

https://github.com/RooyeKhat-Media/iGap-Android/search?q=shamsi&type=Code

**Comment by soheilnikbin** [comment]
There is a specific algorithm to convert [Gregorian to Persian](https://github.com/hobby110/PersianCalendar/blob/master/PersianCalendar.java) calendar so in this case you have to read phone calendar and convert based on that, keep in your mind, in some android phones `Calendar.WEEK_OF_MONTH`  start from 0 and some of them from 1.
