### ISSUE TITLE
Travis-CI build fails

### ISSUE THREAD

**Issue by AchrafAmil** [federicoiosue/Omni-Notes#469]
Is it just me or Travis CI is not able to build any more?

I noticed that the latest pull-requests are getting some kind of : 

`
FAILURE: Build failed with an exception.
\* What went wrong:
A problem occurred configuring project ':omniNotes'.
\> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;27.0.3 Android SDK Build-Tools 27.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html`

or 

`
FAILURE: Build failed with an exception.
\* What went wrong:
Execution failed for task ':sonarqube'.
\> You're only authorized to execute a local (preview) SonarQube analysis without pushing the results to the SonarQube server. Please contact your SonarQube administrator.`

Any idea?

**Comment by federicoiosue** [comment]
Missing acceptance of licenses trying to install they latest build tools version.
They have not all the version, I'd have to dig into the documentation to find the most updated they offer.

**Comment by federicoiosue** [comment]
Known issue https://github.com/travis-ci/travis-ci/issues/8874
