### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by familqasimov** [federicoiosue/Omni-Notes#475]
Hi sir. I'm graphic designer. I've looked at your current logo. Simple. But I would like to offer you another logo. If you like its, I send to you free. I hope you like it's one.

![untitled-1](https://user-images.githubusercontent.com/36432269/38831578-da9f67f4-41d0-11e8-9060-1976ae30d536.png)

**Comment by federicoiosue** [comment]
I'll take them in consideration for the UI overhaul of the next major release. Thanks!

**Comment by familqasimov** [comment]
Can I submit a pull request for this logo?

**Comment by federicoiosue** [comment]
Hi, that's a nice work for sure.

I'm not a designer, nevertheless it seems to not respect [Material designing guidelinese](https://material.io/guidelines/style/icons.html) it should eventually be refactored a little in that sense before being capable to be included into the app
