### ISSUE TITLE
Any item of checklist can not move

### ISSUE THREAD

**Issue by NiceFeather** [federicoiosue/Omni-Notes#481]
Maybe this is a bug issue.
Any item of checklist can not move while dragging the gripper in front of the text.

Current version: 5.5.0
OS: Android 7.0
Device: Samsung Galaxy S7 Edge

BTW, My another phone is no problem for this at Android 4.2.1

**Comment by federicoiosue** [comment]
Known problem but due to the fact that few devices with ON installed are on Android 7.0 it has been labeled as wontfix: https://github.com/federicoiosue/checklistview/issues/20
