### ISSUE TITLE
failed fitting my phone's big screen

### ISSUE THREAD

**Issue by acoret** [federicoiosue/Omni-Notes#485]
# phone
  
## redmi note 5
  
- screen 5.99
  
so it happened,a big black block.   

just a longger screen

-------

_Sent from my Redmi Note 5 Pro using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by federicoiosue** [comment]
Hi, a screenshot or something similar would really help to better understand what happened!
