### ISSUE TITLE
Other calendars

### ISSUE THREAD

**Issue by biomanw** [federicoiosue/Omni-Notes#490]
#466

hi
Please see this link:
This is a messenger app that support shamsi, hijri and gregorian date 
i hope can help for add other calendar

https://github.com/RooyeKhat-Media/iGap-Android/search?q=shamsi&type=Code

**Comment by biomanw** [comment]
#  some screenshot of date in the igap messenger:

![screenshot_ -](https://user-images.githubusercontent.com/10483351/39507828-0a8466f6-4df5-11e8-8ebc-d1286130382d.png)


![screenshot_ -](https://user-images.githubusercontent.com/10483351/39507847-1c023994-4df5-11e8-8f62-9a45e548a5d7.png)

![screenshot_ -](https://user-images.githubusercontent.com/10483351/39507870-3a1730ba-4df5-11e8-8123-6f2abef7951c.png)


![screenshot_ -](https://user-images.githubusercontent.com/10483351/39507912-78d83d76-4df5-11e8-9ba9-047041598767.png)

**Comment by biomanw** [comment]
also many persian data pickers availble  like [this](https://github.com/mohamad-amin/PersianMaterialDateTimePicker)

**Comment by federicoiosue** [comment]
Issue marked as [Help Wanted](https://github.com/federicoiosue/Omni-Notes/labels/Help%20wanted) waiting for eventual persian developers available to work on it
