### ISSUE TITLE
Attachment of one or more Date tags in notes

### ISSUE THREAD

**Issue by val24** [federicoiosue/Omni-Notes#491]
Hello,
A feature I'd love to have in Omni Notes is to enable the "attachment" of date +/– time tag to notes (could be done in the attachments menu or in a similar way key words are created) - there could be more than one date for one note (different from creation /modification date).
And create a search function on dates (note contains date tag before search date / at exact search date / between dates 1 & 2 / after search date).
I'm not sure if this is really clear and I don't know how difficult it is to implement. Thanks for your work - your app is great.

**Comment by val24** [comment]
Hello,

Sorry I haven't answered earlier. I've been away for a few days.

The feature I'd like is almost like the insert Timestamp function (which I
think I hadn't seen), but ideally modifiable, and searchable, and maybe
with the possibility to insert it into the title field.

Thanks for your answer - I really appreciate your app and use it a lot.

**Comment by val24** [comment]
Hello again,
To complete my answer, the search function I'd like would be search for
notes containing dates before search-date or after search-date or between
search-date-1 and search-date-2. I can insert dates as text and search for
the them manually, but I can't search over a period of time in one go.
Hope this makes my question clearer.
Thanks




Le mercredi 9 mai 2018, Valérie Barré <v.barre@laposte.net> a écrit :
> Hello,
>
> Sorry I haven't answered earlier. I've been away for a few days.
>
> The feature I'd like is almost like the insert Timestamp function (which
I think I hadn't seen), but ideally modifiable, and searchable, and maybe
with the possibility to insert it into the title field.
>
> Thanks for your answer - I really appreciate your app and use it a lot.
>
>

**Comment by federicoiosue** [comment]
Ok, I got it but it's quite a specifically calendar-like related feature that I'll personally not implement for two reasons:

- ON tries to follow KISS approach so avoids to much specific features
- Search function is not that much used already (looking at anonymous statistics) to no more features will be added to that
