### ISSUE TITLE
Icon/Logo Proposal 

### ISSUE THREAD

**Issue by loydjayme25** [federicoiosue/Omni-Notes#492]
Good day ! this will be my Icon/Logo proposal for Omni-Notes Project. And i am open for any suggestions sir .

![proposal](https://user-images.githubusercontent.com/37318022/39659036-293881ae-5052-11e8-8de8-35d20c590e09.png)

**Comment by federicoiosue** [comment]
Hi, thanks for the contribution, please give a look to the [guidelines](https://material.io/guidelines/style/icons.html) to make your work suitable for inclusion.

**Comment by federicoiosue** [comment]
Please use the main [Logo-related discussion](https://github.com/federicoiosue/Omni-Notes/issues/23) for proposals
