### ISSUE TITLE
Don't allow to set reminders in the past

### ISSUE THREAD

**Issue by econo202** [federicoiosue/Omni-Notes#496]
**Describe the bug**
Omni Notes allows to set reminders in the past, which seems to be pointless and may lead to confusion.

**Context**
 - App version: 5.5.0

**How to reproduce**
1. Create a note
2. Set a reminder
3. Select a date and/or time in the past
4. The reminder is set despite the fact that it will never be triggered

**Expected behavior**
It shouldn't be able to set a reminder in the past.

**Comment by federicoiosue** [comment]
Is not possible to achieve that with the currently used third party library but [is on the roadmap its replacement](https://github.com/federicoiosue/Omni-Notes/issues/464) with another one that actually allows that.
