### ISSUE TITLE
[Suggestion] New Logo Icon For Omni-Notes

### ISSUE THREAD

**Issue by timonss** [federicoiosue/Omni-Notes#497]
Hi, I want to contribute to his project, I want to design a logo, do you want it?

**Comment by federicoiosue** [comment]
Not needed right now actually, but you're free to contribute if you want. Just pay attention to Material Design Guidelines

**Comment by federicoiosue** [comment]
Please use the main [Logo-related discussion](https://github.com/federicoiosue/Omni-Notes/issues/23) for proposals
