### ISSUE TITLE
Assignment of a tag to a multiple selection of notes - expected behavior ?

### ISSUE THREAD

**Issue by val24** [federicoiosue/Omni-Notes#517]
Hello, 

I've just tried to assign a new tag to a multiple selection of notes. Some of these notes already had tags. Assigning the new tag removed all the other tags.
Is that the expected behavior ?

Personally, I use tags when I want more than one "keyword" associated with one note - otherwise I just put my notes in different categories. The thing is, when I want to associate a new tag, it does'nt mean I want to remove other tags I might have associated with it before.

On Android, can a checkbox have 3 states (on/off/undetermined) as in some Windows apps ? That would help set / unset a specific tag leaving the "undetermined" tags untouched. I'm not sure if it's possible to implement this kind of feature, but that would be great. 

Thanks

**Comment by val24** [comment]
Hello, 
I've just thought about 2 solutions that would make setting / unsetting of tags if checkbox can not have 3 states :
- Show 2 columns of checkbox in front of the list of tags instead of 1 (1 to set tag if checked - 1 to unset tag if checked - checking checkbox in first column must unset checkbox in second column) - 1 checked => set / 2 checked => unset / no checkbox checked => leave tag as it is 
Or
- Have a set option and a separate unset option 
I don't know if any of this is possible or helpful. 
Again, thanks

**Comment by federicoiosue** [comment]
You found a quite relevant but there! 
Your desired workflow is absolutely correct: adding a tag should actually **add** a new one without replacing the other ones!

I'll fix asap.

**Comment by val24** [comment]
Thanks

**Comment by federicoiosue** [comment]
Already fixed
