### ISSUE TITLE
May I know the reason of using ParcelableUtil.marshall when passing data to AlarmManager

### ISSUE THREAD

**Issue by yccheok** [federicoiosue/Omni-Notes#518]
Thank you for creating this open source project.

Currently, I try to implement alarms feature in my app. I notice some shortcoming while using latest WorkManager - https://stackoverflow.com/questions/50299814/how-to-schedule-notifications-using-workmanager/50311781?noredirect=1#comment88324853_50311781

Hence, I plan to fall back to traditional `AlarmManager`. However, I notice that when you pass data to AlarmManager, you are using `ParcelableUtil.marshall`.

May I know is there any reason not passing data as Parcelable directly in this case?

Thank you.

**Comment by yccheok** [comment]
Sorry. I have found out the reason from https://stackoverflow.com/questions/39478422/pendingintent-getbroadcast-lost-parcelable-data Thank you very much.

**Comment by federicoiosue** [comment]
Self answers are the best ones ;)
