### ISSUE TITLE
video how to compile distributable files

### ISSUE THREAD

**Issue by BezMan** [federicoiosue/Omni-Notes#526]
readMe file says - "Watch the following terminal session recording on how to compile distributable files."
when is this necessary? why would one compile outside of Android Studio?

**Comment by federicoiosue** [comment]
Hi,  get

actually that's the way Android Studio itself compiles. 
When you use the IDE to perform some operations it just use underneath console line commands so what you see there is just a graphical interface agnostic method to get the same result.

Why would you use this method? When you don't want to open the IDE for example, or you just want to get in a faster way different compiled artifacts (different flavors for example).

Hope this answers you!
