### ISSUE TITLE
[Improvements] "Remove checked elements" button in note edition page

### ISSUE THREAD

**Issue by eauchat** [federicoiosue/Omni-Notes#539]
In checklist note view, maybe an option "remove checked elements" could be nice :)

**Comment by federicoiosue** [comment]
Removing checklist and re-adding it after removing flag to the "keep checked items" option will do the same.

**Comment by eauchat** [comment]
Ok, that's cool, I didn't know it.
Maybe some day it can be useful to make it more intuitive, but there's no hurry also, the feature is there.
Thank you :)
