### ISSUE TITLE
The app closes as soon as "Password Forgotten" is pressed

### ISSUE THREAD

**Issue by Strappazzon** [federicoiosue/Omni-Notes#592]
**Describe the bug**
The app closes immediately after pressing "Password Forgotten". It's not a crash, it just closes.

**Context**
 - Device: Nexus 5
 - OS version: LineageOS 14.1 (Android 7.1.2)
 - App version: 5.5.0 (F-Droid APK)

**How to reproduce**
1. Open the app
2. When asked to insert the password, press "Password Forgotten"

**Expected behavior**
You should be able to type in the answer to the security question and get the password reset.

**Comment by federicoiosue** [comment]
Reproduced also on the Play Store version.
Working on it, thanks for the feedback

**Comment by federicoiosue** [comment]
Working on newcoming release 5.6.0, thanks again!
