### ISSUE TITLE
Deleting password in settings locks notes

### ISSUE THREAD

**Issue by vexusia** [federicoiosue/Omni-Notes#598]
I apologize if this has already been mentioned prior but I was playing around with some settings and found that after saving a  note and locking it with a password, if you remove the password in settings the notes are still locked but with no data record of the password or security question and cant be unlocked. Way around this I see is to set a new password thus inserting a value in the system record and that new password can be used to unlock the note. Not sure if this intentional considering deleting the password in settings requires the password or security answer which one would presume would unlock the notes.

**Comment by federicoiosue** [comment]
Is just a refresh bug. If you exit the app and enter it again notes should appear unlocked.
I'll fix this by forcing notes reload after password removal.

Thanks for the feedback!

**Comment by federicoiosue** [comment]
Fixed in newcoming 5.6.0 version
