### ISSUE TITLE
Omni Notes Desktop Windows platform

### ISSUE THREAD

**Issue by legionpheonix** [federicoiosue/Omni-Notes#600]
Hello. Please add for windows desktop version and sync via wi-fi at home. that is, the phone is added to the client computer, or vice versa.
Add google drive, dropbox, webdav - sync

**Comment by federicoiosue** [comment]
Synchronization will be achived by using a third party application, both on the Android and desktop version. This to avoid including non FOSS libraries into the core code of the apps.

**Comment by SomeDude2** [comment]
Hello, I know this is closed but I don't think opening a new ticket for this would be appropriate. Is there a Windows/Linux app that can be used to open OmniNotes on desktop?
