### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by princekelly1** [federicoiosue/Omni-Notes#601]
Hello, I'm Kelly. 
I think having a privacy policy statement will be a good thing for your project seeing it kind of have functionalities that may lead to data collection on your end or not. It's a good end users are made aware of the safety of their privacy. I could draft a privacy policy statement if you wish. It's my way of contributing to open source projects.
A FAQ document will be a good addition.

**Comment by federicoiosue** [comment]
Hi Kelly, it already exists actually: https://gist.github.com/federicoiosue/8212e2e090e61c0405a85a9d9a4bebd1
