### ISSUE TITLE
This is not a bug report. I only want to know how to change the package name. I would like to reuse your code, I have tried to change the package name but I have found two . Thank you

### ISSUE THREAD

**Issue by vascofornas** [federicoiosue/Omni-Notes#606]
**Describe the bug**

**Context**
 - Device: [e.g. OnePlus 5T]
 - OS version: [e.g. Android 8.1.1]
 - App version: [e.g. 22]

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by federicoiosue** [comment]
https://developer.android.com/guide/
