### ISSUE TITLE
Expanded view - Empty Title 

### ISSUE THREAD

**Issue by Jackson8890** [federicoiosue/Omni-Notes#612]
when a note has no title it appears as a black line in the expanded view. this appears to be a waste of space. it would seem to be a more efficient use of the space and more appealing to the eye if when there is no title the content of the note begin where the title would have been. This is the way it is done in Google Keep. The benefit of this is presenting more information on the page and less of a need to scroll.

**Comment by federicoiosue** [comment]
That's the way Evernote works. Keep's layout changes between notes while in ON and Evernote does not. Is a behavior implemented by design.
