### ISSUE TITLE
Tags - Like Google Keep.

### ISSUE THREAD

**Issue by Jackson8890** [federicoiosue/Omni-Notes#615]
Omni has by far the best tag system and layout than any of the 20+ note apps that I have experimented with. However it is lacking in ascetics. Instead of trying to describe in words what I mean the simplest way to unserstand would be to examine the location and appearance of the Tags in Google Keep. They call it Labels. There is what to improve upon as well but at least for now it would be a huge plus to have the the tabs in a nice box on the bottom instead of hash tags floating around all over the place similar to Google Keep.

**Comment by federicoiosue** [comment]
What Google Keep calls *labels* is something hybrid between the two entities called *category* and *tag* in Omni Notes. 
Keep's labels stay on the left navigation panel and they're used to organize notes that could actually have more than a single label.
Differently in ON categories are used to separate notes in topics (for example) and more tags can be added every single note to add relevant keywords.

Is a different approach, it's not on the roadmap to change the way it works.
