### ISSUE TITLE
Onclick on Imageview on card_layout

### ISSUE THREAD

**Issue by fiftyman** [federicoiosue/Omni-Notes#618]
hello,

i thank you for your responses. personally, i want a that when i tap on the imageview, the application send the title of the note taped on a txt file named file.txt for example. every card_layout taped will be send the title of the note taped on file.txt,

thank you for your disponibilities,

samuel

**Comment by federicoiosue** [comment]
Hi Samuel, 

I'm actually missing the context of your request. Is something related to some personal development of yours or a request?

**Comment by fiftyman** [comment]
Hello federico, escuse me for late, i see this message now,

as you know i'm french, i dont talk very well in english but i will try, in fact i wanted a simple functionnality in this app that i dont arrive to make in java because i have a poor experience, 

i wanted to add an onclick affected to the button where the note is noted, 

because i want to transfer the text of the note to a txt in my sdcard when i tap on the button even if this tap open the note in parrallel

please tell me, do you understand ?

thanks 

samuel

**Comment by fiftyman** [comment]
Hello @federicoiosue , escuse me for late, i see this message now,

as you know i'm french, i dont talk very well in english but i will try, in fact i wanted a simple functionnality in this app that i dont arrive to make in java because i have a poor experience,

i wanted to add an onclick affected to the button where the note is noted,

because i want to transfer the text of the note to a txt in my sdcard when i tap on the button even if this tap open the note in parrallel

please tell me, do you understand ?

thanks

samuel
