### ISSUE TITLE
Creating launcher home screen shortcuts on Android Oreo doesn't work

### ISSUE THREAD

**Issue by Kamul-PL** [federicoiosue/Omni-Notes#619]
**Describe the bug**
When you try to make a shortcut to a note on Android Oreo, there's no error messages, but the shortcut icon simply doesn't appear. On Android Nougat the problem wasn't exist.

**Context**
 - Device: Xiaomi Redmi Note 4
 - OS version: Android 8.1.0 (LineageOS  15.1-20182206)
 - App version: 5.5.2

**Comment by Genis-Sage** [comment]
Hey,

I've got the same problem, that the in-app notification (that a shortcut was created in homescreen) appears, but there is no shortcut.

Device Information:
    Device: Nokia 7 Plus
    OS version: Android 9.0.0 (January Security Patch)
    App version: 6.0.0 Beta 7
    Launcher: Nova Launcher 5.5.4

On my old device ( Blackberry Priv with Android 6, rest is the same), also the notification appears, and as soon as I go to the homescreen, the shortcut appears.
