### ISSUE TITLE
New category html

### ISSUE THREAD

**Issue by Pratiwir** [federicoiosue/Omni-Notes#623]
Please could you add a new note category, html.
I would like to use wget then paste the file into Omni Notes so it can be viewed as html or source code.
The reason being, often saving as pdf from browser doesn't include the full contents of code windows.
I like to be able to keep technical advice I download in a form where I can search for it, label, and reference the advice offline.
If this is difficult then maybe a way to cross link with another html viewer and archive of files?

**Comment by federicoiosue** [comment]
Evernote is HTML base while ON is not. It's not one of the goals of this app.
