### ISSUE TITLE
Percentage of checklist completion

### ISSUE THREAD

**Issue by Rubylion** [federicoiosue/Omni-Notes#624]
Hi. Iike your app very much and think it's quite usefull. Well I'm working on many projects at the same time, so I really would love to have a visual Progress for every task. ideally it should be setable at a 1%  ratio and show up in the tasks list.
If you like this feature, there could also be a sort option for the amount of completion.
Best regards

**Comment by federicoiosue** [comment]
Hi there, 

when you create a checklist on note's info there are some statistics about items

<img width="407" alt="Android_Emulator_-_Nexus_5X_API_28_x86_5554" src="https://user-images.githubusercontent.com/487104/70650955-4fccba80-1c50-11ea-8a36-71be12f4d48d.png">

I could add percentage here, would be useful?

**Comment by Rubylion** [comment]
Hi. sorry, haven't seen, that you answered. yes, this would be nice. I also use the App 'Open Tasks'. There the progress is displayed as a semi- transparent background on top of every task. The progress is calculated from the sub tasks, like you suggested. but it is also possible to adjust it by yourself. if you do so the progress amount is saved and calculation for this task is set off. i think, these two apps combined, yours and open tasks, would be the perfect task manager ever. anyways thank yoj for your work. regards

**Comment by federicoiosue** [comment]
The most affordable solution to get something similar to this without breaking the current goal of checklist is to just add the completion percentage to info dialog inside a note detail

**Comment by Rubylion** [comment]
OK. Of course it makes getting an overview a bit of an effort. Instead of having everything at sight, right at the task-list itself.

**Comment by federicoiosue** [comment]
![Screenshot_20200718-142233.jpg](https://user-images.githubusercontent.com/487104/87852502-b9a5f480-c902-11ea-96dc-0f8dff51c6d5.jpg)
