### ISSUE TITLE
Number of notes in a category not update immediately

### ISSUE THREAD

**Issue by liziwl** [federicoiosue/Omni-Notes#625]
**Describe the bug**
The number of notes in a category does not update immediately.

**Context**
 - Device: Nokia 7 plus
 - OS version: Android 8.1.0
 - App version: 5.2.2

**How to reproduce**
1. Go to a note
2. Click on category button on the top
3. Click "ADD CATEGORY"
4. Click on category button on the top again
6. The number of notes in a category does not update.

**Expected behavior**
The number of notes in a category should update immediately. In this case, It should be plus one.

If I quit the note, then enter the note again. It is updated.

**Screenshots**
Here I have add a category, but the counter has not updated yet.
![screenshot_2018-11-19-20-29-44](https://user-images.githubusercontent.com/23000702/48707311-03c06980-ec3a-11e8-882c-00fdd10756c1.png)

**Comment by federicoiosue** [comment]
Great job thanks! I've fixed the issue on the new version 6.0.0 Beta 3
