### ISSUE TITLE
Minor graphical UI bug

### ISSUE THREAD

**Issue by dag7dev** [federicoiosue/Omni-Notes#628]
Ciao Federico!

Minor graphical UI bug.

 - OS version: [Android 8.0.0]
 - App version: [5.5.2]

1. Tap drawer
2. Select "Settings"
3. Tap on Interface
4. Switch on and off "floating action button"
5. You will see that the "Text Size" is becoming bigger (and bigger, and bigger...) than before selecting the switch button

Thanks for OmniNotes app, is nearly the best app in the app store for taking notes!
Buon lavoro!

**Comment by federicoiosue** [comment]
Hi, thanks for reporting.

Yes, it seems that increasing/decreasing of the **Text Size** setting descriptions depends both from its value and from settings view reloading on every switch changing event.

Giving the fact that you see it becoming bigger I suppose you're currently keeping the **Text Size** value to "big" at least.

I've not been able to recognize the source of the problem with a fast lookup so I'l keep marked as minor problem into the backlog until the time to work on it will come.

**Comment by HungryJoe** [comment]
Hi Federico,

I've used OmniNotes FOSS for a couple years now, and it's the best notes app I've ever used on Android. Since I use it every day, I'd like to volunteer my time to improve it by tackling this bug. Please let me know if that's cool with you so I can get to work!

Sam Kagan

**Comment by federicoiosue** [comment]
> Hi Federico,
> 
> I've used OmniNotes FOSS for a couple years now, and it's the best notes app I've ever used on Android. Since I use it every day, I'd like to volunteer my time to improve it by tackling this bug. Please let me know if that's cool with you so I can get to work!
> 
> Sam Kagan

Thanks Sam, but this feature has been deprecated and removed on bf3f5862411fe58bb6d5fb6d5a656c83b2f711c9
