### ISSUE TITLE
[Suggestion] Sticky Notes UI

### ISSUE THREAD

**Issue by dag7dev** [federicoiosue/Omni-Notes#629]
Well, thinking about giving a "Google Keep-like" feeling...it's currently awesome.
Also would be nice if we could change the note background since the notes would become more readable and manageable!

**Comment by federicoiosue** [comment]
[This](https://github.com/federicoiosue/Omni-Notes/issues/227) is what is on the roadmap, but actually not that much similar to what Google Keep currently has.
