### ISSUE TITLE
Reminder not working

### ISSUE THREAD

**Issue by poulpoulsen** [federicoiosue/Omni-Notes#632]
Hello,
i had issues with the stable release, because no reminder pops up. Therefore i installed the beta.
Now the program reminder is shown up ONLY if the smartphone comes out of sleep (energy saving).
If the smartphone wakes up the reminder rings.
Possible problem with the energy saving mechanism under Android 8 ?
I use Moto G6 plus with Android 8.1.

Regards Poul

PS: I had similar behaviour with Orgzly App. After installing the Beta there, now reminder works. It seems, that anything similar with Omninotes.

**Comment by federicoiosue** [comment]
Did you checked already the beta version of ON too?

**Comment by pascalfr** [comment]
Hi,

Same problem here, on my samsung A3 2017, reminder is not working :-(

I think the problem could be the alarmManager.setExact() method. Like suggest on https://stackoverflow.com/questions/33260851/alarmmanager-not-working-as-expected-in-sleep-mode-on-s5-neo , alarmManager.setAlarmClock() could be use now like this :
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
  AlarmManager.AlarmClockInfo alarmClockInfo = new AlarmManager.AlarmClockInfo(nextAlarm.getTimeInMillis(), pendingIntent);
  alarmManager.setAlarmClock(alarmClockInfo, pendingIntent);
}else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
  alarmManager.setExact(android.app.AlarmManager.RTC_WAKEUP, nextAlarm.getTimeInMillis(), pendingIntent);
}else {
  alarmManager.set(android.app.AlarmManager.RTC_WAKEUP, nextAlarm.getTimeInMillis(), pendingIntent);
}
```

The differences between the methods are explicited here : https://stackoverflow.com/questions/36110812/difference-between-setexact-and-setalarmclock

Pascal

**Comment by federicoiosue** [comment]
@pascalfr did you checked latest 6.0.4?
Because (shame on me, I've skipped adding a test on previous release for this) I introduced a regression bug trying to fix widget's visualization issues.
Now everything should work correctly

**Comment by pascalfr** [comment]
No, it doesn't work with the 6.0.4

**Comment by federicoiosue** [comment]
I tried to replicate with Samsung Galaxy A3 2017 and maybe I found the reason.

**App Version Under Test**
Name from APK: Omni Notes
Version from APK: 6.0.4
Version code: 279
Your version name: 6.0.4
Package: it.feio.android.omninotes
Uploaded: November 12, 2019 — 05:36 PM (UTC)
Real Device Cloud ID: 53

**Device**
Name: Samsung Galaxy A3 2017
Android version: 8.0.0
API level: 26
Resolution: 720 x 1280 (xhdpi)
Screen size: 4.7"
CPU: ARM | octa core | 1600 MHz
RAM: 2048 MB
Internal storage: 16000 MB
Model number: SM-A320FL
Detailed specification: http://www.gsmarena.com/results.php3?sName=SM-A320FL
Real Device Cloud ID: Samsung_Galaxy_A3_2017_real
Location: Europe
Live Testing: https://app.testobject.com/#/fiosue/omni-notes/manual/viewer?device=Samsung_Galaxy_A3_2017_real&dc=EU

**Issue Details**
https://app.testobject.com/#/fiosue/omni-notes/issues/5
