### ISSUE TITLE
“%” need to be escaped when searching

### ISSUE THREAD

**Issue by liziwl** [federicoiosue/Omni-Notes#633]
**Describe the bug**
“%” need to be escaped when searching.
If searching "%", it gives all the notes.

**Context**
 - Device: Nokia 7 plus
 - OS version: Android 9.0.0
 - App version: 5.2.2

**Expected behavior**
Should be showing the notes just includes "%".
Maybe need to add some condition when generating SQL.

**Screenshots**
![image](https://user-images.githubusercontent.com/23000702/49638119-3512a500-fa42-11e8-87d8-10e613c6f0dd.png)

**Comment by federicoiosue** [comment]
Thanks for reporting, solved both for special chars **%** and **_**. Will be released into the latest beta version
