### ISSUE TITLE
Tag text removal bug by using checkbox

### ISSUE THREAD

**Issue by liziwl** [federicoiosue/Omni-Notes#634]
**Describe the bug**
Tag text removal bug
**It seems like it will remove all tags with the same header as the deleted tag.**

**Context**
 - Device: Nokia 7 plus
 - OS version: Android 9.0.0
 - App version: 5.2.2

**How to reproduce**
1. Add some tag like this
* ![screenshot_2018-12-09-23-52-44](https://user-images.githubusercontent.com/23000702/49699586-e1ed4d80-fc0d-11e8-8c8f-dc54c5c66fa1.png)
2. Remove "test" tag by unchecking the box in this case.
* ![screenshot_2018-12-09-23-52-54](https://user-images.githubusercontent.com/23000702/49699597-106b2880-fc0e-11e8-8ed3-5e58079f9089.png)
3. Remove all tag contain "test"
* ![screenshot_2018-12-09-23-53-13](https://user-images.githubusercontent.com/23000702/49699600-16610980-fc0e-11e8-9158-4b9e731bdd22.png)

**Expected behavior**
Should remain "#testa", "#testb" in the previous case.

**Comment by federicoiosue** [comment]
Fixed!
