### ISSUE TITLE
Highlight search string in the result & category-wise sort

### ISSUE THREAD

**Issue by aabm197** [federicoiosue/Omni-Notes#657]
Hello,
Highlighting the search term in the found notes will be a great help.
So also saving the sorting category-wise.
After trying many Notes apps, I find Omni Notes to be extremely good. Bloatfree customizing options of the app are just to my liking.
I am experiencing some bugs though, specially regarding the reminders. But I will come back to them later after a longer period of trying out the app.
Thanks and Regards for a great App

**Comment by chpravallika** [comment]
I am going to fix that issue

**Comment by aabm197** [comment]
Thank you for the reply. Looking forward to it.
