### ISSUE TITLE
Dialog Box For Discard Changes Confirmation

### ISSUE THREAD

**Issue by iadeelzafar** [federicoiosue/Omni-Notes#662]
**Describe the bug**
There should be a dialog box for Discard changes confirmation.

**Context**
Galaxy Nexus API 24

**How to reproduce**
1. Create a note
2. Click on menu and select Discard Changes
3. No confirmation dialog box is present.

**Expected behavior**
There should be a discard changes confirmation dialog with positive and negative buttons. Otherwise, it can be very expensive if a user has accidentally clicked on the Discard Changes menu icon.
Often times, we click on such options i.e. "Discard Change" but after seeing the choice of "YES" or "NO", we often change our mind and click on "NO" instead.
Hence, user should be given a choice to choose.

**Screenshots**
<img src = "https://user-images.githubusercontent.com/36811908/53760334-65a09880-3ee4-11e9-8eff-1d213406cd20.gif" height="700" width="394">

**Comment by jatinkumarg** [comment]
Hey, can I work on this issue?

**Comment by iadeelzafar** [comment]
Go ahead. Good Luck!

**Comment by jatinkumarg** [comment]
@iadeelzafar I have been trying to set up this project for last week but I have been getting following error
![image](https://user-images.githubusercontent.com/20503830/55270821-4e05c700-527a-11e9-9fcd-5230ffdffaca.png)
 More detailed error

![image](https://user-images.githubusercontent.com/20503830/55270829-637af100-527a-11e9-88c6-a3d20d71088d.png)

Can you please help me with that?

**Comment by iadeelzafar** [comment]
I don't know what this indicates. Never faced this. Maybe you can stackoverflow this.
