### ISSUE TITLE
Text Cut In No Tags Available Message

### ISSUE THREAD

**Issue by iadeelzafar** [federicoiosue/Omni-Notes#663]
**Describe the bug**
Text cut in the last line in no tags available message.

**Context**
Galaxy Nexus API 24

**How to reproduce**
1. Have no Tags.
2. Click on the Tags icon

**Expected behavior**
Text should not cut at the end.

**Screenshots**
<img src="https://user-images.githubusercontent.com/36811908/53760973-27a47400-3ee6-11e9-888c-0148723aa103.gif" height="700" width="394">

**Additional context**
Also, it's difficult to read all of the text in the message within the duration as it is very less. So, the duration of the message should be increased or the text should be reduced. Personally, I think a better solution would be to reduce the text which will solve both the issues.

**Comment by federicoiosue** [comment]
Fixed with #747
