### ISSUE TITLE
While compiling annoying error is occured.

### ISSUE THREAD

**Issue by kashifansari786** [federicoiosue/Omni-Notes#664]
when i launch this app in my real device then i got error(inner element must either be a resource reference or empty.) which is not resolved can you resolved this issue.

**Comment by federicoiosue** [comment]
Hi, you should elaborate a little more:

- which device are you using?
- which version of the app?

**Comment by kashifansari786** [comment]
Error occurs before install the app in compile time... So i m not be able
to install the app

**Comment by tux0n** [comment]
i get this error too when try to compile and install app on android studio emulator

**Comment by federicoiosue** [comment]
The error reported by @tux0n is a different one and should be now solved on develop branch due to latest dependencies switches.

For what concerns yours @kashifansari786 I've not enough informations to reproduce.
