### ISSUE TITLE
Adding shortcut to home screen - clicking on shortcut results in "App isn't installed" error

### ISSUE THREAD

**Issue by overbarg** [federicoiosue/Omni-Notes#679]
Device Information:
Device: Samsung Galaxy S10
OS version: Android 9.0.0 (May Security Patch)
App version: 6.0.0 Beta 10
Launcher: Nova Launcher 6.1.6

Also tried with Samsung One UI Home launcher with similar results.

**Comment by federicoiosue** [comment]
Merged with #695
