### ISSUE TITLE
[Feature Request] Zooming into sketches

### ISSUE THREAD

**Issue by ManDay** [federicoiosue/Omni-Notes#685]
WIthout a stylus, a feature which allows to (pinch-) zoom into sketches would be helpful to fit more meaningful content than what is possible by drawing on the screen with your finger.

**Comment by federicoiosue** [comment]
Skecth feature is really marginal into Omni Notes: specific apps are great for draw, their artifacts can then be shared with ON for categorization and context addition with text or whatever.
