### ISSUE TITLE
Promemoria

### ISSUE THREAD

**Issue by Alessandra-Omni** [federicoiosue/Omni-Notes#688]
Dopo l'ultimo aggiornamento di due giorni fa, non funzionano più i promemoria. Ho provato anche sul cellulare di mio figlio, Samsung Galaxy S9 plus, con app appena scaricata.

**Context**
 - Device: [Samsung Galaxy S10 plus]
 - OS version: [Android 9]
 - App version: [5.5.3]

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by federicoiosue** [comment]
Grazie mille della segnalazione, ho corretto nella ultima release che uscirà a breve (già disponibile come beta)
