### ISSUE TITLE
ERROR: No such property: dir for class: org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection

### ISSUE THREAD

**Issue by SagarShubh** [federicoiosue/Omni-Notes#694]
**Describe the bug**

**Context**
 - Device: [e.g. OnePlus 5T]
 - OS version: [e.g. Android 8.1.1]
 - App version: [e.g. 22]

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by federicoiosue** [comment]
This is not very clear, I'm sorry but I can't help.
Eventually add more details.
