### ISSUE TITLE
"Add shortcut" failed to execute and gave wrong hints

### ISSUE THREAD

**Issue by sjl872964789** [federicoiosue/Omni-Notes#695]
**Describe the bug**
The application does not request permission from the user when performing the "Add shortcut"operation, there is no shortcut generated after execution, but it prompts the user that the execution has been successful. I can only successfully generate shortcuts when I try to open "Display on lock screen" permissions.

**Context**
 - Device: [vivo X9]
 - OS version: [Android 7.1.2]
 - App version: [5.5.2]

**How to reproduce**
1. Install Omni Notes and open
2. Click on plus button in the lower right corner
3. Click on "Checklist'
4. Fill in any string in the title field
5. Click on three points in the upper right corner
6. Click on "Lock"
7. back
8. Click on three points in the upper right corner
9. Click on "Add shortcut"

**Expected behavior**
App prompt “SHORTCUT ADDED TO  HOME SCREEN”, But nothing actually happened. 

**Screenshots**
Recorded video see attachment
[20190813122226.zip](https://github.com/federicoiosue/Omni-Notes/files/3500140/20190813122226.zip)

**Comment by federicoiosue** [comment]
Correct, waiting for a solution the feature will be removed starting from Android 8 (on previous versions still works). Thanks for the feedback
