### ISSUE TITLE
Arbitrary creation date

### ISSUE THREAD

**Issue by Wilker-a** [federicoiosue/Omni-Notes#698]
hello :3

i would like to import the notes that i currently have in my device, but i don't have root privileges to just import everything, and while they're old, i still want to keep the creatíon time of each one, but i don't want to keep so many tags, one for each date/time, and let it become disorganized.

can there be a feature to set an arbitrary creation date/time for these notes? possibly with a mark on them indicating that the date/time set was set by the user, too (or not)

thank you for reading \^-\^

**Comment by federicoiosue** [comment]
Hi, that's actually really out of the scope of the creation date marking of the notes so, I'm sorry but that'll not be implemented.

Anyway, I'm missing the point of "import the notes that i currently have in my device". What would you like to do exactly?

**Comment by Wilker-a** [comment]
i would like to import all of them from the preinstalled notes app in my phone, and that includes the creation date, as that is relevant to me in the contexf of what i have written, but i cannot do so without root, thing i don't have conditions to get at this moment.

but thank you anyway \^\^

**Comment by randomshell** [comment]
Hello @Wilker-a,

you can do it like this:
1. Import every note you need in Omni Notes, ignore the creation date
2. Export them with the backup option
3. Use any sqlite gui editor to select the omni-notes file in the backup directory and go to the notes table
4. Find your notes and edit the creation date by using [this](https://www.epochconverter.com/) website for the date conversion. Use the Human date to Timestamp and copy the Timestamp in milliseconds, the longer one with 000 at the end.
5. Save the database and after importing it in Omni, restart the app and check the results. If it doesn't work but the database is correctly edited, reset the app and import again.

Let me know if it worked or if you have any questions.

**Comment by Wilker-a** [comment]
cool, thank you :3

are there any editors in f-droid or another open source..source.. that i can use? :3

**Comment by randomshell** [comment]
Try aSQLiteManager on fdroid, the only one I found.
To edit the fields, after you open the database and select notes, click on DATA, and the small Edit button at the start of each row. Wasn't obvious for me.

Otherwise I suggest doing it on a computer.

**Comment by Wilker-a** [comment]
thank you a lot for the help, it helps a lot \^-\^

**Comment by randomshell** [comment]
@Wilker-a with the new 6.0.0 version, backups are in json and not in sql format. Now you just need a text editor :smiley:.
Don't know why this change but it's much appreciated.

**Comment by Wilker-a** [comment]
oh cool :3 @randomshell

are the date formats changed to a simpler version? :3

**Comment by federicoiosue** [comment]
I arrived too late, @randomshell  already answered about version 6.0.0 😄

**Comment by Wilker-a** [comment]
it's okay :3

thank you both in any case \^_\^
