### ISSUE TITLE
IllegalStageException: not allowed to start service Intent

### ISSUE THREAD

**Issue by nicofrand** [federicoiosue/Omni-Notes#699]
**Describe the bug**
I regularly get crash reports from OmniNotes, even though the app is not open.
My reminders also do not work anymore.

I sent crash reports through another email, but I can't find a way to actually extract the stack trace etc so you'll find a screenshot below.

**Context**
 - Device: Nexus5X
 - OS version: Android 8.1.0
 - App version: 5.5.3

**How to reproduce**
1. Add reminders
1. Let the app run in the background

**Expected behavior**
No error and a notification when a reminder is scheduled.

**Screenshots**

![Screenshot_20190916-193515](https://user-images.githubusercontent.com/3419050/64980813-edffed00-d8ba-11e9-9b1d-04031f937f07.png)

**Comment by federicoiosue** [comment]
Solved in latest newcoming build, thanks!
