### ISSUE TITLE
Clarify "prettified dates" setting

### ISSUE THREAD

**Issue by Wilker-a** [federicoiosue/Omni-Notes#700]
just a minor change suggestion.

instead of showing the setting as "detailed" and "simplified" or "prettified", having it named as "Use absolute date-time formats" or "Use relative date-time formats" would be more straightforward,

while the description of the settings could be just the format being shown as an example like  
**"Current: ''Tuesday, 24 Sep 2019, 14\:00'' "**\*  
and  
**"Current: ''5 hours ago'' "**.  
###### \*  `(current time) -(an arbitrary amount of time)` for the example

what do you think? :3

**Comment by federicoiosue** [comment]
It's a desired abstract description due to face the possibility of changing the exact format. Or think about the fact that that format itself does change when you change the country, so I'd have to create dinamically the label depending on the currently set language.
