### ISSUE TITLE
Recursive notes (move notes to inside of other notes)

### ISSUE THREAD

**Issue by Wilker-a** [federicoiosue/Omni-Notes#701]
i sometimes make a couple of notes which are referencing the same thing, but with that, they may end up occupying a lot of space in the list with entries like "thing-part(1|2|3)” as i still want to keep them separated from the main note, but it woudn't be good to keep a category for these.

one solution that i would think of would be having some notes referencing others, but i believe that would be complicated to make using SQLite. so i think that the simplest solution would be to implement a way to transfer notes to attatched txt files, and make them editable directly via the note editor. and i think the date-time of the creations and edit can be simply the first two lines of the file (with the separator at the third for readability), so that these properties can still be a thing...

what do you think? :3

**Comment by doctor-owl** [comment]
This is actually a simple yet incredibly useful idea.

**Comment by federicoiosue** [comment]
This is out of the scope of the app. Relationship between notes must be achieved by grouping them into categories and by linking then through tags.
