### ISSUE TITLE
No Persian in Language settings

### ISSUE THREAD

**Issue by ahangarha** [federicoiosue/Omni-Notes#707]
I am currently running v5.5.2. For verifying translation, I changed the language from default (persian) into English and now, I cannot go back to Persian.

I guess this is a bug.

Any more information do you need?

**Comment by federicoiosue** [comment]
Would you mind trying Beta? It's quite ready to be released as stable and it's the best version to use for translations checking right now

**Comment by ahangarha** [comment]
I can try. let me know how

**Comment by federicoiosue** [comment]
I tried on latest beta code: your translation does work there, maybe I did't updated something on stable yet.
