### ISSUE TITLE
txt (ASCII) import

### ISSUE THREAD

**Issue by hman2** [federicoiosue/Omni-Notes#708]
Either it's missing or I'll have this as a feature request. I have lots of notes on my employers Outlook (Exchange) system. While I see that syncing is not available at the moment, an import of plain ASCII should pose no problem?

Copy&Paste does not work satisfactorily. Omni-Notes ignores hard line breaks, thus breaking pre-formatted ASCII text, making notes that do not use the entire length of a line very hard to read... Omni-Notes CAN, however, export ASCII (although not with an "export" functionality, but when sharing a text note via K-9 mail, text gets exported to ASCII.

But on the recipient, there would be no counterpart? Mail with ASCII note arrives, but cannot be processed, not even manually?

Thanks for looking into this.
hman2

P.S.: Syncing could be made easier if storage location of Omni-Notes DB files could be chosen. OwnCloud could then handle the syncing...

**Comment by federicoiosue** [comment]
Hi, actually sync is not available in realtime but a feature branch is under development to auto-backup data while using the app so that a user can decide which app to use to perform just files synchronization.

What you're proposing is not achivable because of security mechanism of Android platform.

**Comment by federicoiosue** [comment]
Plain text import could be achived right now by "wrapping" your plain text into JSON structure available since version 6.0.0 and performing a backup restore into Omni Notes

**Comment by hman2** [comment]
Not really intuitive, to "wrap plain text into a JSON structure".  I have about 3 dozen notes to import now, and they get updated every other day. Why not have a simple "import" feature that reads ASCII? Cannot be that hard to implement...
