### ISSUE TITLE
AGPBI Issue

### ISSUE THREAD

**Issue by saveendhiman** [federicoiosue/Omni-Notes#710]
Got issue while compiling. Please check and update Gradle too. 

AGPBI: {"kind":"error","text":"Program type already present: com.afollestad.materialdialogs.AlertDialogWrapper$Builder$2","sources":[{}],"tool":"D8"}

**Comment by federicoiosue** [comment]
That's a very old version and must be updated. Moving to latest version would be a big change in terms of refactoring but would also help to solve #669 and F-Droid build chain

**Comment by federicoiosue** [comment]
I'll keep opened the other issue to track and work on this problem too.
