### ISSUE TITLE
Version available on F-Droid behind Play Store

### ISSUE THREAD

**Issue by billie80** [federicoiosue/Omni-Notes#713]
I am using Omni-Notes from F-Droid. Is there any reason versions newer than 5.5.2 are not available there?

**Comment by federicoiosue** [comment]
Related to #669

**Comment by billie80** [comment]
Okay thanks. I already found this issue however it was not clear to me how the F-Droid build is concerned.

**Comment by federicoiosue** [comment]
Because their build pipeline fails for the same reason. 
It seems that I'm currently the one able to build the code, maybe for some historical dependencies available locally on my machine ![bitmoji](https://render.bitstrips.com/v2/cpanel/8fc50cb6-a2c5-4996-94d8-a8462cf5b66e-c98f03dd-32bb-4736-8d96-67ffd0c19496-v1.png?transparent=1&palette=1&width=246)

**Comment by licaon-kter** [comment]
@federicoiosue Umm, what am I missing: https://gitlab.com/snippets/1946400 ?

**Comment by federicoiosue** [comment]
> @federicoiosue Umm, what am I missing: https://gitlab.com/snippets/1946400 ?

Now the build should work, but I've some problems trying to run the complete test suite. Furthermore the current version will have to be release as a Beta before proceeding with the stable version for everyone so that will only be available for Play Store users.

**Comment by licaon-kter** [comment]
> Specifically, the problem with their pipeline is due to the fact that the code they're trying compiling is the one from the master branch, that is still not updated with the modifications above.

It's tagged as 6.0.5 hence I guess it's ok to build.

Will retry with HEAD

**Comment by licaon-kter** [comment]
@federicoiosue Looks like it builds fine from HEAD, do @ -me when 6.1.0 is Tagged ;)

**Comment by uraza** [comment]
The app looks really nice.
I got here from F-Droid, but the version there is two years old.
Will it be updated on F-Droid with the next release, like the comment above suggests?
Thanks a lot for your work!

**Comment by federicoiosue** [comment]
Yep, the latest code (version 6.1.0) should compile correctly on F-Droid pipeline. 
When tests will have full success it will be released both on Play Store and F-Droid platforms. And as GitHub release too, of course.

**Comment by licaon-kter** [comment]
In app, Settings Privacy
* error reporting in ON by default, this mean for F-Droid we'd add `AntiFeature: Tracking`
* share anonymous data ON by default, same as above
* where's the data sent? That might need another `NonFreeNet`
* ACRA bug reporting works how? Auto-submission? email?

**Comment by 2Belette** [comment]
Is this the reason why F-Droid version is from 09/2018? Was wondering if the project is dead but it seem more this issue?

**Comment by federicoiosue** [comment]
> Is this the reason why F-Droid version is from 09/2018? Was wondering if the project is dead but it seem more this issue?

The latter one

**Comment by Dunedan** [comment]
Any update on this? I'd love to see an up-to-date Omni-Notes version on F-Droid.

**Comment by licaon-kter** [comment]
@federicoiosue so https://github.com/federicoiosue/Omni-Notes/commit/6a300da871d360298364a86e873d5ce43e767e04 will finally fix this?

6.2.0(302) builds fine here, but still has Google Permissions: https://www.virustotal.com/gui/file/21a6cd504ccdcb5967e6d031280eac86b111bbb0acb502cfe49061d11cd0600b/details

**Comment by federicoiosue** [comment]
I'm testing with removed com.google.android.apps.photos.permission.GOOGLE_PHOTOS and android.permission.WRITE_EXTERNAL_STORAGE (no more needed due to migration to scoped storage).

If everything works as expected I'll prepare a release and a pull request to F-Droid

**Comment by smaragdus** [comment]
Any news about the F-Droid release?

**Comment by federicoiosue** [comment]
The ACRA backend I was using discontinued so I'm trying to replace it to continue having something that collects anonymous crash reports to analyze app's errors. 
As soon as ready I'll release the new 6.2.0 version for both Play Store and F-Droid.

**Comment by licaon-kter** [comment]
Bugsnag?

**Comment by federicoiosue** [comment]
> Bugsnag?

Never heard of it, it seems nice, but I'm exploring the option to use my own [Acrarium](https://github.com/F43nd1r/Acrarium) backend instance for ACRA to keep full control. 
It should fit FOSS approach, I'd not have any cap of reports (staying on free tier is mandatory for this project) and I'd be able to provide a public access to guests to enforce transparency.

**Comment by federicoiosue** [comment]
[Here](apps.iosue.it:8080) an example (still missing SSL) using guest both as username and password @licaon-kter

**Comment by licaon-kter** [comment]
Looks nice, as usual, hope it's opt-in ;)

**Comment by federicoiosue** [comment]
Yes, it depends from Settings->Privacy->Error Reporting flag

**Comment by linsui** [comment]
The short_description is too long. F-Droid only take 80 characters so that it's truncated. Could you please make it shorter?

**Comment by federicoiosue** [comment]
@linsui thanks for pointing out
