### ISSUE TITLE
Notes location

### ISSUE THREAD

**Issue by omirobarcelo** [federicoiosue/Omni-Notes#715]
Hi.

Recently my phone screen got unusable and I want to save my notes. Where are the notes saved in Android, so I can take them and save them in my computer?
I checked Android/data/it.feio.android.omninotes/files but is empty.

Thank you.

**Comment by federicoiosue** [comment]
There you'll be able to find eventual attachments. 
If you don't have any backup you'll have to save the whole database and to do that you'll need to have root access because it's into a folder not publicly accessible!

**Comment by omirobarcelo** [comment]
Thanks for the quick reply! And what would be the location of the database, when I have root access?

**Comment by federicoiosue** [comment]
/data/data/it.feio.android.omninotes/databases.

Would be useful to also have settings if you ever changed anything. You'll find them at /data/data/it.feio.android.omninotes/shared_prefs/it.feio.android.omninotes_preferences.xml
