### ISSUE TITLE
Error Depedencies

### ISSUE THREAD

**Issue by messidiq** [federicoiosue/Omni-Notes#716]
I've downloaded last release version, Everything alright till i test to run app

Program type already present: com.afollestad.materialdialogs.AlertDialogWrapper$Builder$2

**Comment by federicoiosue** [comment]
Hi there, 

the issue should be fixed, now the builds on develop branch are [back to work](https://travis-ci.org/federicoiosue/Omni-Notes/builds/623261614?utm_medium=notification&utm_source=email)!
