### ISSUE TITLE
Asynchronous long running calls

### ISSUE THREAD

**Issue by nasrilg7** [federicoiosue/Omni-Notes#734]
I'm using OmniNotes open source app as a case study for my University.
I see that the App has a couple of implementations of Asynchronous code where some tasks run in the background. 
I'm wondering, are there any long-running asynchronous tasks that have a human-noticeable delay?

**Comment by federicoiosue** [comment]
Please provide a more specific block of code or reference to it. Generally speaking async tasks should be used to avoid data I/O, network connections, and more on the main thread. It's not just a matter of user waiting but the fact that the entire UI would be blocked by that process!
