### ISSUE TITLE
Implementing Dark Theme

### ISSUE THREAD

**Issue by AdmiralOwl** [federicoiosue/Omni-Notes#736]
Hello,
a Dark theme for this application would improve effectively the readability. 
A toggle button in the Settings of the app would allow switching between a Light (Default) and Dark theme.

Let me know your opinion, thank you.

**Comment by federicoiosue** [comment]
Yes I agree, but I'll wait for the whole app graphical overhaul before start working on the dark theme to avoid doubling the work.

Duplicate of https://github.com/federicoiosue/Omni-Notes/issues/70
