### ISSUE TITLE
Restoring the app from the background can cause data loss

### ISSUE THREAD

**Issue by Instagit** [federicoiosue/Omni-Notes#739]
When restoring the app from the background with the android app switcher, you sometimes get an old version of the document. If you make any changes to that, all other recent changes will be overwritten and lost.

How to reproduce the problem:

1) Open a note (in my case from the widget).
2) Change something.
3) Press the home button to minimize the app.
4) Open the android app switcher. You will notice that sometimes the preview picture does not reflect the latest changes.
5) Open the app.
6) Instead of loading with the latest changes you made, you get the old note version from the app switcher preview.

**Comment by federicoiosue** [comment]
Hi there, 

I've not been able to reproduce the issue, both by starting the note editing from apps launcher or widget.

What device and OS/app version are you using, to try reproducibility on your specific configuration?

**Comment by Instagit** [comment]
Hi federicoiosue,

I'm using a Sony Xperia XZ2 Compact with Android 9 (Build 52.0.A.11.32, Kernel 4.9.112-perf+).

I'll try to make screenshots when I see the problem again.

**Comment by federicoiosue** [comment]
This if what I got by trying to reproduce on a Sony Xperia XA2 (I tried to search for a similar device to yours)
![Uploading Kapture 2020-01-07 at 17.13.24.gif…]()

**Comment by federicoiosue** [comment]
I'm going to close the issue for now, please fell free to re-open it if you have more informations about it!
