### ISSUE TITLE
Map View

### ISSUE THREAD

**Issue by thejeshgn** [federicoiosue/Omni-Notes#742]
We can explore the notes by tags or categories. Can we also get a map view.  Where in notes can be pinned to a location on map and i can browse through that list.

**Comment by federicoiosue** [comment]
Would be a nice feature, but this would for sure require more accesses to Google's map APIs. 
Due to the fact that free tier has a limited number of requests/day I'd have to pay to keep this feature working so, for now, it'll stay out of the roadmap.

**Comment by P-Luca** [comment]
How about giving the possibility to enter a personal Google Maps API key in the settings?  That way requests would not be added to your Google Maps API key.  What do you think?  Does it break any rule in the API key terms?
