### ISSUE TITLE
Cannot restore backups in current develop

### ISSUE THREAD

**Issue by tappdesign** [federicoiosue/Omni-Notes#746]
If you try to restore notes previously backuped as JSON (no old [legacy] backup), nothing happens.
There is no crash of app, dialog for choosing the backup directory simply disappear after tap on it, but no action is taken. So the choosen backup is not restored at all.

**Comment by Trigga6974** [comment]
I do not know how to restore my notes on my old phone to the new one please help

**Comment by federicoiosue** [comment]
This could have been fixed as side effect by 5a88b24a990367c9567b2a4a1aeece057d50fbc4, a3fe880c618b91a1665b27afb69522544828cd2f and 1e4f4bd828282d49b81b170cd5365503117ad46a
