### ISSUE TITLE
Note body does not work with barcode scanner keyboards

### ISSUE THREAD

**Issue by tanius** [federicoiosue/Omni-Notes#748]
We have a use case of adding notes to barcoded items. Since Omni Notes does not include a barcode scanner (yet …) but is a very lovable note-taking app, I tried multiple different Android custom keyboard apps that can act as a barcode scanner, providing the barcode text as keyboard input to the field in another app where one is typing.

In all cases, it was possible to scan barcodes as characters into the title field of Omni Notes text notes, but not into their text body field. When trying, simply zero characters are entered. There is no error message or anything.

Since the barcode scanner keyboards work in title fields (and also in other apps like Chrome), I consider this an issue in Omni Notes and not of the barcode scanner keyboard apps, so I'm provisionally reporting it here.

The keyboard apps I tested:

- [Ucom Free Barcode Scanner](https://play.google.com/store/apps/details?id=hk.ucom.barcodecamera)
- [Barcode & QR code keyboard](https://play.google.com/store/apps/details?id=com.nikosoft.nikokeyboard)
- [Barcode/NFC/OCR Scanner Keyboard](https://play.google.com/store/apps/details?id=com.tecit.android.barcodekbd.demo)

This is Android 6.0.1 on a Nexus 7 tablet.

**Comment by federicoiosue** [comment]
Hi there, thanks for the feedback.
Unfortunately this is a so much specific issue and by simply touching on the note's body field the barcode number actually appears after all so I'm not going to work on this that much soon.

This could be for to the custom component used for that field, and everything could be solved indirectly when I'll finish the work on the new interface.

**Comment by tanius** [comment]
Thank you for having a look! :slightly_smiling_face: 

> by simply touching on the note's body field the barcode number actually appears after

Good find! Cannot reproduce that behaviour, but probably my Android version is too old for it. Admittedly the issue is minimal then on new Android versions. Like you say, let's see if the rest is automatically resolved in the new interface you're working on,
