### ISSUE TITLE
May God bless you, God bless Italia

### ISSUE THREAD

**Issue by travellers** [federicoiosue/Omni-Notes#751]
Hi, Federico Iosue,
Are you OK? 
COVID-19 is striking Europe, and it's very dangerous.
I'm from Hubei province of China, we understand deeply the COVID-19 is very infectious, and Isolation is the only way for a city.
Take care, if you need our help please tell me. Thanks for your open source software!

**Comment by federicoiosue** [comment]
Quite OT but thanks, we're managing that 😄
