### ISSUE TITLE
Unable to restore backup

### ISSUE THREAD

**Issue by Dimitri-UNHCR** [federicoiosue/Omni-Notes#754]
Help! I am unable to restore the notes I backed-up to change my phone.
The sqlite DB exists, but When I restore and refresh, no notes appear

I will try to restore by trying to dive into the sqlite DB. Hope it is easy...

I tried with SQLite browser, ant it seems there are no tables or data. I believe my data is lost :(

**Comment by federicoiosue** [comment]
Most issues with backups are solved in the Beta version based on JSON files. This should not apply anymore.
