### ISSUE TITLE
[Feature Request] Be able to instantly write new item while ToDo file is still loading

### ISSUE THREAD

**Issue by tdbe** [federicoiosue/Omni-Notes#755]
Let me explain: Now if you open a todo / checklist / note, you have to:
- click open
- wait for file to load
- manually scroll all the way down until you reach the end (can take a long while if you have say a long travel log)
- then click on item
- then start typing

If I want to write down my thoughts fast, this is what has to be implemented:
- click on a note
- it opens up and is instantly showing the bottom with a new line or a new checklist item and I can instantly tap it to show the keyboard
- I can start typing right away and when I press enter, it will get appended to whatever the end of the file is.
- In the meantime, in a separate thread, or on the same thread but as an async operation, The actual notes file loads up and when is done loading it automatically scrolls to the bottom.
- While the async operation loads the file, have a loading dots animation showing on the empty body of the file, above the box into which I can type.

Sound cool? It shouldn't be that hard to implement. Because right now I'd rather make a new file than open one that's 100+ lines. And this is otherwise a perfect note taking app, great for your thoughts, or logs, or todo ideas for your code etc.

Thanks!!

**Comment by federicoiosue** [comment]
Thanks for you great feedback.

That sounds interesting but it's a little bit beyond ON'goal to provide KISS paradigm as note editor.

Moreover I tested with the following really long text and the timing is not that bad to require all that parallel/background/async work. Of course facing the same behavior as you do with your usage could be frustrating but not enough to change the current mobile app way.

![Screenshot_20200804-174155.jpg](https://user-images.githubusercontent.com/487104/89314643-31ea1500-d67a-11ea-8aca-13c68d7bfc6f.jpg)

But I'll keep this in mind for desktop version, that could move a little further by introducing a more complex interface.

**Comment by tdbe** [comment]
@federicoiosue Your test is not accurate. Make that note into a CHECKLIST, of at least 250 items. Then try to open it and write something at the bottom of this 250 list. Also doesn't help if you have 10 of these checklist files in omni notes.

I'm a game developer and when I write code I make the data streamable and infinitely scalable, I would never rely on "well the user is never gonna do x" :P 
But of course you define your scope of your project however you want 👍

**Comment by federicoiosue** [comment]
Maybe some kind of "reach the bottom of the note" would help, leaving apart the performances topic?

**Comment by tdbe** [comment]
Yes, that should be good too. Or the option to sort checklist notes in the reverse order. So that the new entry box is always in the beginning / top of the file, and each time you add a new entry it is inserted at the top of the stack.

Because when you think about it, the most recent items are often the ones that are most urgent and you need to read most often. Now the least urgent tent to bubble to the top since you typically never insert a new item anywhere other than on the bottom, and for the rest of the list body you either delete an entry or do nothing.

But even an auto-scroll-to-bottom button is good as at least I'll avoid flicking my finger really fast 10 times to scroll down.
