### ISSUE TITLE
Making OMNI notes for Medical records

### ISSUE THREAD

**Issue by prashneuro** [federicoiosue/Omni-Notes#756]
I am Neurosurgeon from India, I have seen many applications used for medical records in overseas and some developing software within India. 

I literally love the way google keep and Omni notes work. 

I was trying to convince some developers to make something like OMNI notes for IN-PATIENT database management for resident doctors.

Can anyone help me with this?

**Comment by federicoiosue** [comment]
Not very clear actually, and not strictly related to this specific version of the app.
But ON's code is licensed under GPLv3 so it would be great to have a fork designed for that!
