### ISSUE TITLE
Checklist item cannot be reordered in Android 7

### ISSUE THREAD

**Issue by rruizt** [federicoiosue/Omni-Notes#758]
Hello, 

I'm using Omni-notes in a phone with Android 7 and unfortunately reordering checklist items doesn't work. This works without any issues in Android 10

*Steps to reproduce*
1. Install the app in an Android 7 phone
2. Create a new checklist note
3. Create two checklist items
4. Try to move the last one up

Thank you for your work!

**Comment by federicoiosue** [comment]
Yes it's a known problem but I've decided to not fix that because that would require to rewrite [this library](https://github.com/federicoiosue/checklistview) used for that just for Android 7 because later versions are working fine again.
