### ISSUE TITLE
Insert text through share intent

### ISSUE THREAD

**Issue by KnIfER** [federicoiosue/Omni-Notes#763]
I'd like to put serveral web paragraphs into one note through share or send to intent. 
But it will create new notes every time I send a text. 

It's neater to put them togather.

What about a lock icon so that if it's locked, paragraphs will be put togather otherwise new note will be created?

**Comment by federicoiosue** [comment]
Hi there, and thanks for your feedback on the argument.
I'm one of the users that really do something similar a lot of times and what I do is the following:

1. I search what I need and share images (mostly, in my case), links, text to ON
2. Multiple notes are created for every single share action
3. When finished I just merge them together, when you're doing this the notes' selection order is respected by merging

Having more simple workflows really helps to keep the app under the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle), and this is on of the Omni Notes' strongest claims.

**Comment by KnIfER** [comment]
Merge is fancy feature though, didn't know that before!
