### ISSUE TITLE
Cannot add location when device's location mode is device only

### ISSUE THREAD

**Issue by sjl872964789** [federicoiosue/Omni-Notes#764]
**Describe the bug**
The location cannot be added, and there are no explanations and reminders for the user. After investigation, I found that the problem is caused by the "device only" mode. Omni notes should prompt the user to switch the location mode just as it prompts the user to open the location. Otherwise, the user may not know why the location cannot be added

**Context**
 - Device: galaxy a6s
 - OS version: Android 8.1.0
 - App version: 6.0.5

**How to reproduce**
1. Change location mode to "device only"
1. Install Omni Notes and open
2. Click on plus button in the lower right corner
3. Click on "Text note'
4. Click the paper clip button
5. Click on "Location'
6. See "LOCATION NOT FOUND"

**Expected behavior**
The user should be prompted that the current positioning mode cannot be located and needs to switch to high accuracy  mode

**Screenshots**
Recorded video see attachment
[record.zip](https://github.com/federicoiosue/Omni-Notes/files/4744201/record.zip)

**Comment by federicoiosue** [comment]
First of all thanks for the great bug reporting!

I'll dig further into asap, meanwhile, when you say "device only" it means that you're using only GPS isn't it?

**Comment by sjl872964789** [comment]
Thank you for your kind reply. Yes, "device only" means that I'm using only GPS. There are two ways to make your device in "device only" location mode. The first way is to turn on location setting and turn off the network. The second way is to select "device only" mode through a special setting, which is available in my mobile phone(galaxy a6s-android8.1.0) and the Android simulator I often use (pixel2-android8.0). At this time, no matter whether your network is turned on or not, you can only use GPS for positioning. The way to turn on this setting is as follows:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15941953/84368892-bb481280-ac08-11ea-9ef4-815ba42ea714.gif)

**Comment by tingsu** [comment]
Simiar issue here. Any plan to resolve this problem? Thanks.

**Comment by sachin-0102** [comment]
Can I work on this issue?

**Comment by federicoiosue** [comment]
@sachin-0102 of course you can. Please give a look to README to follow code contribution guidelines!

**Comment by sachin-0102** [comment]
I've made a PR on this issue...Check it out and let me know if something needs improvement

**Comment by federicoiosue** [comment]
Fixed by https://github.com/federicoiosue/Omni-Notes/pull/778 and https://github.com/federicoiosue/Omni-Notes/commit/9388e244b56ab3a3322ef3e893050c988292bdd3
