### ISSUE TITLE
Widget can create empty notes; Empty notes can't be deleted

### ISSUE THREAD

**Issue by ManDay** [federicoiosue/Omni-Notes#766]
Contrary to the application where adding a note fails to create it without content, tapping (+) on the widget creates a note instantly and possibly without content. Such an empty note can not be trashed - the application complains "Can't save an empty note" just like during creation.

**Comment by ManDay** [comment]
FWIW I'd opt for removing the limitation of not being able to save empty notes (unless there is a technical reason such as uniqueness). If someone wants to create empty notes, why not let them?

**Comment by federicoiosue** [comment]
Hi there, thanks for your feedback.

I've not been able to reproduce the behavior. Here my attempt: https://dl3.pushbulletusercontent.com/rttt9OL3q5NuuHfleCYyLTiWOEKHU7Db/20-07-15-23-54-05.mp4

**Comment by federicoiosue** [comment]
Still irreproducible, maybe something has changed from there during the lated bugfixes/rewriting of legacy code.
