### ISSUE TITLE
Android beam support

### ISSUE THREAD

**Issue by rugk** [federicoiosue/Omni-Notes#769]
It would be nice to support Andrid beam, so I could:
* open a note on phone A
* hold phone B against it
* tab on phone A to confirm sending
* phone B gets the same note transferred

(if both have the app open, of course.)

Currently, without special implementation, it just opens or installs this app… :smile:

**Comment by federicoiosue** [comment]
Nearby Sharing is already coming so starting an implementation on a technology that will be soon deprecated doesn't sound that good.
Apart from that I didn't really ever used NFC due to its slowness to share data. I don't think that functionality has ever had many admirers sincerely
