### ISSUE TITLE
Some text on the page has not been translated

### ISSUE THREAD

**Issue by sjl872964789** [federicoiosue/Omni-Notes#776]
**Describe the bug**
Some text on the page has not been translated

**Context**
 - Device: [MI CC 9e]/[PIXEL XL]
 - OS version: [MIUI 10.2.10]/[Android 10.0]
 - App version: [6.0.5]

**How to reproduce**
Steps to reproduce screen1:
0. Change the language to Chinese in the system settings
1. Install Omni Notes and open
2. Skip former five welcome screens

Steps to reproduce screen2:
0. Change the language to Chinese in the system settings
1. Install Omni Notes and open
2. Skip the welcome screens
3. Click on plus button in the lower right corner
4. Click on "Checklist'
5. Fill in any string in the title field
6. Click on three points in the upper right corner
7. Click on "Discard changes"

**Expected behavior**
The text is translated correctly

**Screenshots**
screen1:
<img src="https://user-images.githubusercontent.com/15941953/90253087-2fa26a80-de73-11ea-8681-9f5c6add5d0d.jpg" width="270" height="600"/>

screen2:
<img src="https://user-images.githubusercontent.com/15941953/90253112-38933c00-de73-11ea-8982-db92c780b4c9.jpg" width="270" height="600"/>

**Comment by federicoiosue** [comment]
Thanks for pointing my attention to that. Feel free to apply for helping in translating the app [here](https://crowdin.com/project/omni-notes)
