### ISSUE TITLE
crash while switching the note layout

### ISSUE THREAD

**Issue by tappdesign** [federicoiosue/Omni-Notes#785]
while switching the note from expanded layout to "simple" application crash.

in **NoteAdapter.java** is always **expanded** layout created

 ```
public NoteViewHolder onCreateViewHolder (@NonNull ViewGroup parent, int viewType) {
    View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.note_layout_expanded, parent, false);
    return new NoteViewHolder(view);
  }
```
maybe has to be changed this way:

````
@NonNull
  @Override
  public NoteViewHolder onCreateViewHolder (@NonNull ViewGroup parent, int viewType) {
    View view;
    if (expandedView) {
      view = LayoutInflater.from(parent.getContext()).inflate(R.layout.note_layout_expanded, parent, false);
    } else {
      view = LayoutInflater.from(parent.getContext()).inflate(R.layout.note_layout, parent, false);
    }
````

**Comment by federicoiosue** [comment]
Hi there, 

I didn't tested but your solution is fine to me. Would you like to contribute by making a pull request on your own, following the [guidelines](https://github.com/federicoiosue/Omni-Notes#contributing)?

**Comment by tappdesign** [comment]
Do I need permission for it? Pushing to new created branch returned 403 - denied to tappdesign

**Comment by federicoiosue** [comment]
> Do I need permission for it? Pushing to new created branch returned 403 - denied to tappdesign

You've done well by creating a pull request instead of directly pushing your feature branch to my remote
