### ISSUE TITLE
Removing tag removes special characters

### ISSUE THREAD

**Issue by WildOrangutan** [federicoiosue/Omni-Notes#786]
Removing a tag from a note, can remove special characters like "new line", "comma", "minus", etc.

Reproduce: [video](https://user-images.githubusercontent.com/5972966/94736575-be5c3f80-036c-11eb-98f9-4bcd5b259d0c.gif)

**Comment by WildOrangutan** [comment]
If you don't have any other plans, I would also like to fix this issue.

**Comment by federicoiosue** [comment]
Hi Peter,

thanks for reporting. 
Of course feel free to work on that but please pay attention to required contributions steps (code style, unit-test...) stated into the README!

**Comment by WildOrangutan** [comment]
Don't worry, will try my best to maintain code standards.

I have a minor question tough. I'm a bit confused with constant `TAG_SPECIAL_CHARS_TO_REMOVE`. Is that intended to determine, where tags ends? For example, if content text is `text (#tag) more text`, parsed tag value should be `#tag`?
