### ISSUE TITLE
"Erase all data" does not clear sharedpreferences

### ISSUE THREAD

**Issue by tappdesign** [federicoiosue/Omni-Notes#790]
After click --> **settings** | **Data** | **Erase all data** 
are all data erased except settings in sharedpreferences
(Android 8.0)

Issue could be possibly solved by changing from 
prefs.edit().clear().**apply()**;
to 
prefs.edit().clear().**commit()**;

in `SettingsFragment.java`
```
 Preference resetData = findPreference("reset_all_data");
    if (resetData != null) {
      resetData.setOnPreferenceClickListener(arg0 -> {

        new MaterialDialog.Builder(getContext())
            .content(R.string.reset_all_data_confirmation)
            .positiveText(R.string.confirm)
            .onPositive((dialog, which) -> {
              prefs.edit().clear().apply();
.....
```

**Comment by federicoiosue** [comment]
Actually I completely forgot to do that!! Thanks for reaching me with the issue!
