### ISSUE TITLE
Checklist corrupted if a tag is selected

### ISSUE THREAD

**Issue by ronriley** [federicoiosue/Omni-Notes#791]
1.  have a checklist and some of the items have #tags
2. close the checklist
3. open the checklist, select a tag from the tags button
4. checklist is corrupted

**Comment by federicoiosue** [comment]
Hi there, have you tried if the Alpha version, available on Play Store with latest changes from development, works?

**Comment by ronriley** [comment]
Hi

Thanks for getting back to me.

In the alpha version it throws an exception, says that is reported to the
developer, did this a couple of minute ago.

So different behaviour but still an issue.

Regards

Ron
