### ISSUE TITLE
[Feature Request] Manually trigger "move checked items to the end"

### ISSUE THREAD

**Issue by tillfoo** [federicoiosue/Omni-Notes#792]
First of all, thank you for the work all of you are putting into Omni Notes, I use it every day!

A new feature that would be helpful for me is the following:
In checklists, checked items keep their position. Only once you tap a button (/swipe/other interaction), checked items move to the end.
Ideally, you'd even be able to set the checklist behaviour per note.

For example, with my daily to-do list, it is nice to see at a glance what I accomplished so far that day. If checked items move to the end instantly, that's not possible. Still, at some point the items need to move down, that's when I'd use the proposed feature.

**Comment by federicoiosue** [comment]
Thanks for the feedback, it totally makes sense to me!
The underlying library already supports moving items so I'll start working on an option to move them down on user's request.
