### ISSUE TITLE
when you rotate the device to landscape orientation, the title on the top app bar shrinks

### ISSUE THREAD

**Issue by vvzuev** [federicoiosue/Omni-Notes#799]
Frequency: Everytime

Envoronment: Samsung Galaxy A70 - Android 10

Actions Performed:
1. Launch Omni Notes
2. Turn the device to landscape orientation

Expected Results: The size of the title on the top app bar has not changed

Actual Results: The title on the top app bar shrinked

Attachments:  

![omni_bug__3_screen_1](https://user-images.githubusercontent.com/51853424/99886529-49abd000-2c4e-11eb-8712-d05103e418e4.jpg)

![omni_bug__3_screen_2](https://user-images.githubusercontent.com/51853424/99886533-53353800-2c4e-11eb-8c07-62fe8fe526fb.jpg)

**Comment by federicoiosue** [comment]
IT seem to work correctly to me by looking latest beta


https://user-images.githubusercontent.com/487104/107969369-fbd60800-6faf-11eb-8217-2b1d3bd59f17.mp4
