### ISSUE TITLE
By swiping a locked note (left or right) on the screen "Notes" and closing the app, the note is deleted

### ISSUE THREAD

**Issue by vvzuev** [federicoiosue/Omni-Notes#801]
Envoronment: Samsung Galaxy A70 (Android 10)

Version: 6.0.5

Steps to reproduce: 
    1. Launch app;
    2. Tap the  [FAB] button and select "Text note";
    3. Write any text in the field "Title";
    4. Tap the Overflow menu and select "Lock";
    5. Fill in all the fields in the dialog that appears and tap the action "ok";
    6. Tap the [Back] button;
    7. Swipe the created note (left or right);
    8. Close app;
    9. Launch app;

Actual Result: The created locked note is missing

Expected Result: The created locked note should be located in the list notes of the screen "Notes" content area

Attachments: 

![omni_bug_5](https://user-images.githubusercontent.com/51853424/100647495-aa26c580-3350-11eb-8489-eeaa50128ef9.gif)

**Comment by federicoiosue** [comment]
Thanks, you're doing a really great job as issues reporter!!

**Comment by federicoiosue** [comment]
Fixed on 91d39669683cd91b942fa5c5ce16c7e4f2ecbe74
