### ISSUE TITLE
[Feature Request] Option for changing app navigation bar colour

### ISSUE THREAD

**Issue by samuelsarao** [federicoiosue/Omni-Notes#804]
Can we have a option where we can change the colour of the navigation bar in the app? I could like to have it to be of yellow colour personally, because I often associate yellow with notes and blue with contacts and messaging apps i.e they look very similar and cause confusion ( XD ) 

Note: 
This is not something very important and it would be better if the developers could treat this has their least priority.

**Comment by federicoiosue** [comment]
Hi Samuel,

thanks for your feedback but I'm going to label this request as "wontfix" and this is the reason: the colors are choosen for "brand consistency". 
Currently both app's icon and theme are (strongly) blue-oriented, this could change when the whole design will be revamped but even then the colors will be choosen to keep consistency. I'm greatly open to any contribution about the redesign, I'm actually a developer and not a designer and any help would be welcome!

**Comment by samuelsarao** [comment]
> Hi Samuel,
> 
> thanks for your feedback but I'm going to label this request as "wontfix" and this is the reason: the colors are choosen for "brand consistency". 
> Currently both app's icon and theme are (strongly) blue-oriented, this could change when the whole design will be revamped but even then the colors will be choosen to keep consistency. I'm greatly open to any contribution about the redesign, I'm actually a developer and not a designer and any help would be welcome!
> 
> 

I totally agree with you with the brand consistency. I am quite interested in the redesigning of the app. I have some design skills and would love to create some designs for this app! Will try! Thanks :)
