### ISSUE TITLE
minor UI bug

### ISSUE THREAD

**Issue by tappdesign** [federicoiosue/Omni-Notes#807]
Hi Federico, 

There is a small UI bug regarding Mr. Jingel. 
If you remove last note from archive, listview is empty, but no Mr. Jingel appears.

I think it could be fixed by just additing one line to the `ListFragment.java` in `trashNotes()`

**listAdapter.notifyDataSetChanged();** 

 ```
 
  public void trashNotes(boolean trash) {
    int selectedNotesSize = getSelectedNotes().size();

    // Restore is performed immediately, otherwise undo bar is shown
    if (trash) {
      trackModifiedNotes(getSelectedNotes());
      for (Note note : getSelectedNotes()) {
        listAdapter.remove(note);
        ReminderHelper.removeReminder(OmniNotes.getAppContext(), note);
      }
    } else {
      trashNote(getSelectedNotes(), false);
    }

    listAdapter.notifyDataSetChanged();    
    finishActionMode();

```

I'm not sure if this is a correct solution. 

I have a trouble to create a test for it, so I give it up for now ;-)
Maybe it is because toolbar items are changed dynamically while executing the test.....
Or it is a espresso bug, or something like that, but when the overflowmenu has to be displayed, it will crash with exception 
```
androidx.test.espresso.AmbiguousViewMatcherException: '((is displayed on the screen to the user and with content description text: is "More options") or (is displayed on the screen to the user and with class name: a string ending with "OverflowMenuButton"))' matches multiple views in the hierarchy.
Problem views are marked with '****MATCHES****' below.
```

here is a non functional test:
```

  @Test
  public void EmptyListViewTest() {

    createNote("A Title", "Note A to archive");

     // make sure overflow menu is displayed, this time it will not crash, it runs smoothly
     openActionBarOverflowOrOptionsMenu(getInstrumentation().getTargetContext());

    // hide overflow menu
       Espresso.pressBack();

   // select first note by longtap on it  - this will change overflow menu items for managing the notes
    onView(withId(R.id.list)).perform(RecyclerViewActions.actionOnItemAtPosition(0, longClick()));

   // try open overflowmenu --> EXCEPTION: AmbiguousViewMatcherException
     openActionBarOverflowOrOptionsMenu(getInstrumentation().getTargetContext());

}
```

**Comment by federicoiosue** [comment]
Hi, if added a test [here](https://github.com/federicoiosue/Omni-Notes/commit/5d2870bd35a20aefcea8cd7cc1c40ecff60e31cc) both to reproduce and to add code coverage but I've not been able to verify the misbehavior.

**Comment by tappdesign** [comment]
Hi Federico, 

Thank you very much for tests and analysing! 
But I forgot to mention, Bug appears only after **swiping** the note. Please see attached video. If you trash the note by toolbar menu items, it looks ok.

https://user-images.githubusercontent.com/59613279/102889831-a2dc6e80-445b-11eb-9ec6-5e049e40b1cc.mp4

Device: HONOR7AHO
Android: 8.0

**Comment by federicoiosue** [comment]
This test should work and should put in evidence the misbehavior by resulting broken:

```
 @Test
  public void mrJingle_displayedOnArchiveWhenEmptiedBySwiping() {
    createNote("title", "content");
    List<Note> notes = dbHelper.getAllNotes(false);
    archiveNotes(notes, true);

    navigateTo(1);

    onView(withId(R.id.list)).perform(
        RecyclerViewActions.actionOnItemAtPosition(0, new GeneralSwipeAction(
            Swipe.SLOW, GeneralLocation.BOTTOM_RIGHT, GeneralLocation.BOTTOM_LEFT,
            Press.FINGER)));

    onView(allOf(withId(R.id.empty_list), withText(R.string.no_items_in_list),
        withParent(withParent(IsInstanceOf.instanceOf(android.widget.FrameLayout.class))),
        isDisplayed())).check(matches(isDisplayed()));
  }
```

You can add it to the **MrJingleLifecycleTest** class and verify if your fix works correctly!

**Comment by tappdesign** [comment]
Your test **mrJingle_displayedOnArchiveWhenEmptiedBySwiping()** failed, after fix it is passed ok.
I've created pull request, you can review it. Thanks for extending the tests.

**Comment by federicoiosue** [comment]
Fixed by https://github.com/federicoiosue/Omni-Notes/pull/809
