### ISSUE TITLE
[Feature Request] Text size optimization

### ISSUE THREAD

**Issue by Lancelotiwaba** [federicoiosue/Omni-Notes#810]
Please bring back the text size optimization feature. That was one of the most important feature of the App UI. Having only one font size in a notes app makes makes it user unfriendly...

**Comment by federicoiosue** [comment]
Hi there, sorry but that was a really bad UI anti-pattern developed by me at the time when custom fonts or sizes were still a good idea.
If needed the whole OS interface should be zoomed-in with apposite global settings.

But you're still free to reintroduce it into your own fork Lance!
