### ISSUE TITLE
Create sub-list from a checkbox

### ISSUE THREAD

**Issue by mikjsmith** [federicoiosue/Omni-Notes#820]
[Feature request] Ability to create a sub-list from an existing checkbox within a list. Google Keep does this  by allowing you to indent a checkbox which then becomes the child of its immediate above neighbour. Moving the parent, moves all the children with it.

**Comment by federicoiosue** [comment]
Sorry but that's beyond of the goals of the app. Furthermore it would require to heavily change the mechanisms on which the used [library](https://github.com/federicoiosue/checklistview) is based on.
