### ISSUE TITLE
Feature Req: Biometrics note unlock

### ISSUE THREAD

**Issue by tdbe** [federicoiosue/Omni-Notes#824]
It's great that we can lock individual notes behind a password. But I find that having to type in the password every time I have to open that one note again, dissuades me from for example keeping my "journal" etc. Either that or have a very shitty very short password.

So it would be amazing, if there was an option to, on top of the password, have a layer that allows you to just unlock the note with android's biometrics / fingerprint.

**Comment by federicoiosue** [comment]
I completelly agree with you: https://github.com/federicoiosue/Omni-Notes/issues/275

**Comment by federicoiosue** [comment]
I'm closing to keep just one request per feature

**Comment by tdbe** [comment]
> I'm closing to keep just one request per feature

I swear I searched for existing issues before posting, but I must have not used the "fingerprint" keyword 🙂 ✌
