### ISSUE TITLE
Crashed On Notification Click

### ISSUE THREAD

**Issue by NaitikKundalia** [federicoiosue/Omni-Notes#827]
Crash in Notification Click

When clicked on notification the application is crashed on some device due to notesObjs get null. Line no 90 on SnoozeActivity

Object[] notesObjs = (Object[]) getIntent().getExtras().get(INTENT_NOTE);

I had uploaded my code with customization on 

https://github.com/NaitikKundalia/Omni-Notes-develop

Code works in pixel & redmi device but not in samsung. I had tested in M31 or M51.

**Comment by federicoiosue** [comment]
Hi there, 

I've tried both on emulator and on a real Samsung Galaxy S10+ (I did not found the devices you reported, maybe they're for oriental market only) and it works correctly.
Moreover I found no changing commit on your source code so, for now I'm going to close this issue but feel free to open it again if you have more informations.

**Comment by NaitikKundalia** [comment]
I will replicate it and give you the problem in details. I had tried that in Samsung M51.

**Comment by federicoiosue** [comment]
stacktrace would be helpful too
