### ISSUE TITLE
Settings icon being smaller than other entries in the sidebar

### ISSUE THREAD

**Issue by Lurux** [federicoiosue/Omni-Notes#829]
**Edit:** And the text is in caps. To summarize, the entry is not styled like the others.

Lol sorry but this is triggering me:

![Screenshot_20210805-183122_Omni_Notes](https://user-images.githubusercontent.com/35870988/128387273-2fd35435-7654-44ce-8b0b-0f24b7fda109.png)

I know I'm nitpicking here, but this is the best FOSS notes app IMO, so why not make it even better ? :slightly_smiling_face: 

Also speaking of icons, I second using adaptive icon.

**Comment by federicoiosue** [comment]
Thank you for the feedback, you're right, but they're separated things: the caps are actually token from a previous version of Google Keep, but I agree that now really seems old and ugly; the icon could have followed the same path, but I can't really remember right now.

**Comment by federicoiosue** [comment]
Better? 

<img width="308" alt="Schermata 2021-08-16 alle 15 26 17" src="https://user-images.githubusercontent.com/487104/129571323-fc4c2661-5c29-4359-b13b-de704097b75d.png">

**Comment by Lurux** [comment]
Cool, thanks ! This is very minor, so I didn't expect it to be changed so fast.

Also when will the app be updated on f-droid ? I think I had seen an issue about this but it's closed now

**Comment by federicoiosue** [comment]
The build on F-Droid was broken due to a couple of dependencies. Now it should be fixed but I'm waiting to release the stable 6.1.0 on Play Store (that provides different distribution channels) before coming back to F-Droid build management.
