### ISSUE TITLE
Omni Notes web application

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#84]
Hi, i am going to start working on a web application for Omni Notes, I am going to use either flask or django, before I started to design the UI and the application I wanted to ask for any suggestions as to how I should design and structure the app so that it will be easy to code it for the android app

**Comment by aimanbaharum** [comment]
Is this feature already available? Sounds like a very useful feature as I'm moving from Gnotes (they have IAPs now).

**Comment by federicoiosue** [comment]
@aimanbaharum currently under development [here](https://github.com/federicoiosue/omni-notes-desktop)

**Comment by thewhitetulip** [comment]
This is interesting @federicoiosue, does this allow sync with the android version?

**Comment by federicoiosue** [comment]
@thewhitetulip it actually shares the same data source (json files) as [this feature branch](https://github.com/federicoiosue/Omni-Notes/tree/feature/autobackup) does

**Comment by thewhitetulip** [comment]
@federicoiosue If this is the case, then maybe we can write something to sync between the LAN between mobile and laptop, for those who use the app like me and don't want to go through the Internet

**Comment by federicoiosue** [comment]
@thewhitetulip that's quite beyhond my intensions. 
I'm actually using FolderDroid to sync and it works even with WebDAV/FTP.

**Comment by thewhitetulip** [comment]
@federicoiosue How would I transfer the JSON file from android app to desktop app without any manual process?

**Comment by federicoiosue** [comment]
I setup a scheduled sync job following this scheme:
```
Device <-(FolderDroid)-> Google Drive <-(Insync)-> Desktop
```
You could perform something similar without leaving your own LAN

**Comment by thewhitetulip** [comment]
Thank you! (Now a stupid question, how do I export to JSON? manually?)

**Comment by federicoiosue** [comment]
Currently only alpha version use that export format. You could try to install that (it works aside of regular Omni Notes) and check-out its output.

If you build on your own the app's develop branch that will work too but due to many bugs I still have I've but made a build yet.

**Comment by thewhitetulip** [comment]
I'll wait for the final version then :-)
