### ISSUE TITLE
Version on F-Droid is 5.5.2. from Sept. 2018

### ISSUE THREAD

**Issue by petrarca-arezzo** [federicoiosue/Omni-Notes#841]
The version on F-Droid seems to not get any updates since a few years - it's on version 5.5.2. (Sept. 20118). Any specific reason why Omni Notes doesn't get updates any longer on F-Droid?

**Comment by federicoiosue** [comment]
Hi there, yes the reason is [this one](https://github.com/federicoiosue/Omni-Notes/issues/841). I've already closed the issue but I'm going to reopen it as reminder for the time when the 6.1.0 version will finish the rollout on Play Store
