### ISSUE TITLE
Omni-Notes Alpha data restore on Android 11 issue.

### ISSUE THREAD

**Issue by testordie** [federicoiosue/Omni-Notes#842]
Hello. 

I like your app and for some time now I was using its sister version Omni-Notes-Alpha. Several days ago, I upgraded to Android 11 and tried to restore a backup from previous OS Android 10. But after restoring, no previews of attached files are available, and you can't open these files by clicking on them (the app that is supposed to open them is launched, but says that it can't read the file or just crushed altogether). But if you create a note with an attachment anew, you can open the attachment just fine. I tried to restore this backup to Omni-Note (not Alpha) and attachments work just fine there. So, I guess, it has something to do with "scoped storage enforcement" in Android 11 (attachments are stored in /mnt/runtime/write/0/Android/data/it.feio.android.omninotes.alpha on my device under Android 11). Could you look into that issue? 

Thanks.

**Comment by federicoiosue** [comment]
Hi there, actually switching between the two versions of the app is not supported. They're really made to stay separated to avoid behaving too much into the Alpha version to keep daily notes!

I've performed many times the migration but some manual editing is needed to prepare attachments to work on the other flavor. Not reccomended if you ask me!
