### ISSUE TITLE
AsyncTask is deprecated

### ISSUE THREAD

**Issue by phucbao2k** [federicoiosue/Omni-Notes#843]
i came across this app, overall i think the app has a pretty good structure, however there are many constructors that are deprecated on android 11 or later. Typically AsyncTask has been replaced by ExecutorService. So does anyone have an alternative to AsyncTask? What statements or classes do we need to add or replace? Thank you so much for reading this post

**Comment by federicoiosue** [comment]
Hi there, 

maybe [Coroutines](https://developer.android.com/kotlin/coroutines?gclsrc=aw.ds&gclid=Cj0KCQiA15yNBhDTARIsAGnwe0VAexlg1YuPA82t0oC7W7qIxYFCR17I7QOYNsNPFU_i7V66HaLiIPMaAiBYEALw_wcB) are the best deal to replace older async processing methods. Native threads are another alternative.
Keep in mind, anyway, that deprecating doesn't actually mean that they'll not work, at least in a short time.
