### ISSUE TITLE
Post-it style widgets

### ISSUE THREAD

**Issue by onlycparra** [federicoiosue/Omni-Notes#849]
The "post-it" widget would be an amazing addition. 
One important aspect of "note-taking" is to remember things that you will probably forget. So it is fundamental **to be exposed** to that info rather than needing to go and open it by your own initiative.

So having a note "always open in the home screen" is precisely that: ensuring exposition to that prone-to-be-forgotten information. 

@TheDcoder commented about this in issue #759

**Comment by federicoiosue** [comment]
I'm merging both the requests. This could be done.
