### ISSUE TITLE
Cannot rename category missing ok button

### ISSUE THREAD

**Issue by MansonLuo** [federicoiosue/Omni-Notes#852]
cannot rename category, because there is only a delete button without ok button.

btw, there is no way to forbid the use of # sign even use /# or \#,  I wanna use normal # sign instead of create a no need category.

thanks.

**Comment by federicoiosue** [comment]
Hi there, 

Does the firt problem always happen, or just with that specific category?
I'm not sure to got your second point correctly anyway. Are you referring to tags (words starting with # symbol) or something else?

**Comment by MansonLuo** [comment]
yes, alway happen after long click category
![Screenshot_2022-05-09-15-08-45-383_it feio android omninotes](https://user-images.githubusercontent.com/19282278/167358269-730f6d71-490c-484e-a61b-e8e8e161b062.jpg)


and the tag that is made with symbol # is hard to use, i cannot use common symbol #

**Comment by MansonLuo** [comment]
and cannot sort items within the same category through sliding up and down

**Comment by federicoiosue** [comment]
Should be related to #860
