### ISSUE TITLE
update advice

### ISSUE THREAD

**Issue by MansonLuo** [federicoiosue/Omni-Notes#857]
adding pictures always in bottom of article, thats not good idea.:)

**Comment by federicoiosue** [comment]
Hi there, actually there is an options from **Settings -> Interface -> Attachments at bottom** to choose where to add pictures

**Comment by federicoiosue** [comment]
> Is there any way to add image in anywhere in an article? its not enough to only add pics in bottom or top of articles

Nope, this feature works as the Google Keep's one. Is not html/markdown based so positioning can only be done in the two ways above.

**Comment by MansonLuo** [comment]
thanks.

**Comment by federicoiosue** [comment]
No worries!
