### ISSUE TITLE
Add category interface lacks OK button

### ISSUE THREAD

**Issue by Masterfans** [federicoiosue/Omni-Notes#860]
![add category interface lacks OK button](https://user-images.githubusercontent.com/13980892/178431253-9993a441-0103-440d-9404-e07202dab99f.png)

**Comment by federicoiosue** [comment]
I'm sorry but I really have no idea about what this means.

Would you mind elaborating?

**Comment by federicoiosue** [comment]
I'm not reproducing both on emulator or my own phone.
What device are you using?

![Screenshot_20220713_133514 Media](https://user-images.githubusercontent.com/487104/178725032-f804aa87-816f-48bb-9b31-12710a4bcc6a.jpeg)

**Comment by Masterfans** [comment]
There is abnormal device information
![device info](https://user-images.githubusercontent.com/13980892/178765694-571088c7-24e0-4983-bb00-2712421902ce.png)

**Comment by federicoiosue** [comment]
Fixed on [@https://github.com/federicoiosue/Omni-Notes/pull/861](https://github.com/federicoiosue/Omni-Notes/pull/861)
