### ISSUE TITLE
Pin note crash

### ISSUE THREAD

**Issue by WildOrangutan** [federicoiosue/Omni-Notes#862]
Pinning note crashes the app.

**Reproduce:**

1. Create new note
2. Pin note -> crashes

**Versions**

App: 6.1.0
Android: 12

**Comment by federicoiosue** [comment]
Hi there, 

I'm sorry but I've not been able to replicate the issue on both the emulator (API 30, latest develop code), my OnePlus device or Pixel 6

**Comment by federicoiosue** [comment]
Reproduced, checking how to fix.

**Comment by WildOrangutan** [comment]
Yeah, play store version. Let me know if there's anything I can help you with, tough it seems you already fixed it 👍
