### ISSUE TITLE
Compatibility issue when calling method

### ISSUE THREAD

**Issue by PSDroid2022** [federicoiosue/Omni-Notes#863]
We confirm a compatibility issue which might threaten the robustness of your app and give a detailed suggestion for you.

In ''it.feio.android.omninotes.services.NotificationListener", you invoke the API "<android.service.notification.StatusBarNotification: java.lang.String getPackageName()>" and "<android.service.notification.StatusBarNotification: int getId()>"  in "onNotificationRemoved" method as shown in following. But actually, those APIs are introduced after API level 18(
https://developer.android.google.cn/reference/android/service/notification/StatusBarNotification?hl=en#getPackageName()
).
```java
 @Override
  public void onNotificationRemoved(StatusBarNotification sbn) {
    if (getPackageName().equals(sbn.getPackageName())) {
      EventBus.getDefault().post(new NotificationRemovedEvent(sbn));
      LogDelegate.d("Notification removed for note: " + sbn.getId());
    }
  }
``` 
So when the app try to invoke this API on devices before API level 18, your app will run with an unpredictable results. So we suggest you add an "if(SDK_INT >= 18)" to fix this potential issue. 

## Android device

 - Device: [e.g. Emulator]
 - OS: [e.g. API 16~17]
 - Omni-Notes Version: [6.0.5]

**Comment by federicoiosue** [comment]
Thanks for pointing out this: actually the [latest code on develop branch](https://github.com/federicoiosue/Omni-Notes/blob/develop/gradle.properties#L20) has a minimum SDK version 21 so this issue should not apply anymore.
