### ISSUE TITLE
"Add Attachment" menu without scrolling in landscape mode

### ISSUE THREAD

**Issue by PinkRay7** [federicoiosue/Omni-Notes#865]
I can't scroll down when I click "Add Attachment" in landscape mode. There is no scrollbar for the menu while some options are not displayed.
Plus, when I open the menu then rotate the screen, the menu will disappear.

### Expected behavior
Scroll up and down like version 5.3.1.
Menu does not disappear when switching between portrait and landscape modes.
Screenshots from 5.3.1 with a scrollbar:
![F549E9C3582EC424F70010B4319EF7CF](https://user-images.githubusercontent.com/53887881/187010385-77ebfb56-57ad-4d81-b321-0cd9792da229.jpg)

https://user-images.githubusercontent.com/53887881/187011180-2435065e-a9ff-4b47-a268-a68550c5da4b.mp4

### Actual behavior
You can't scroll downwards and the menu will disappear when you rotate the screen.

https://user-images.githubusercontent.com/53887881/187011188-ee8dc27c-232b-4dc7-af7f-adbb39ad25cf.mp4

### Steps to reproduce
1. Open a note in portrait mode.
2. Click "Add Attachment".
3. Switch to landscape mode and see the menu disappeared.
4. Click "Add Attachment" in landscape mode.
5. See the menu broken.

### Environment
Omninotes Version: 6.1.0
Google Pixel 2 Android Version 8

**Comment by PinkRay7** [comment]
I can reproduce it on HONOR 20 Lite too.

https://user-images.githubusercontent.com/53887881/187013454-1a3dac1d-efb2-4a3f-a639-a8848b8b1239.mp4

**Comment by XYIheng** [comment]
I have encountered the same problem, it really annoyed me. I usually use omininotes in the landscape. Hope it can be fixed!

**Comment by federicoiosue** [comment]
Thanks for reporting!

https://user-images.githubusercontent.com/487104/189779700-64dc6410-a7be-4e9d-9516-bc00c3e884c4.mov
