### ISSUE TITLE
Widget Errors

### ISSUE THREAD

**Issue by terry9873** [federicoiosue/Omni-Notes#869]
I love this app, used it for a year or two now. 

I use a Widget to add the "Add Note" (red icon) to my homescreen for quick creation of reminders and notes. For the past few months it's buggy though, as the widget changes to the standard Omni Notes icon (in appearance). So I now have two Omni Notes next to each other. The right hand one still behaves properly as it did before it changed appearance, but I thought I would report it anyway. 

If i delete the widget and add it again, it looks fine for a day or so, then it reverts to the appearance of the Omni Notes app icon. 

Thanks

**Comment by federicoiosue** [comment]
Hi Terry, I don't know which version were you using but the commit referenced above could solve. Im keeping thing monitored, thanks for your feedback!

**Comment by terry9873** [comment]
Hi, thanks for replying. 
My version says 6.1.0. 
I am not sure how to update, assuming there are updates, can you please advise?
Also I don't understand github at all, no idea what a commit is :) 
thanks again

**Comment by federicoiosue** [comment]
It's still not released, it'll be packed into the next beta release (opt-in through Play Store)

**Comment by terry9873** [comment]
I don't use play store. How else can i get it? (I use Droidify for apps)
thanks

**Comment by federicoiosue** [comment]
I've updated right now the latest alpha [here](https://github.com/federicoiosue/Omni-Notes/releases/tag/6.2.0_alpha) (it'll be installed as a separate app from the normal Omni Notes)

**Comment by terry9873** [comment]
Thanks. So I can just download that APK?
If so, will it be updatable in Droidify in the future? 
Also, if I install it, will it keep all my stored reminders/notes?
thanks

**Comment by federicoiosue** [comment]
Whenever the next stable will be ready it'll be published on F-Droid (and consequently suitable from all its third party clients like Droidify).

In the meantime the alpha version I've add as stub release will install aside to the normal Omni Notes (FOSS or not) app but it'll not share any data with the other one. It's meant to be used as test app for contributors to checkout latest changes without putting their original data at risk.

**Comment by terry9873** [comment]
i see thanks.
