### ISSUE TITLE
ON does not exit on back button

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#87]
When you press the back button it toggles the navigation drawer and doesn't exit the app at all

**Comment by LeonardKoenig** [comment]
There's a setting for that. Maybe it got disabled by an update?

**Comment by federicoiosue** [comment]
On a second back-button pression it should exit even with that option activated, could you provide a feedback on this @thewhitetulip?

**Comment by thewhitetulip** [comment]
Actually it might have been a temporary glitch because now I can't seem to replicate it. Btw @federicoiosue what is the ETA on the material update? waiting for it :)

**Comment by federicoiosue** [comment]
Beta releases are already materially designed

**Comment by thewhitetulip** [comment]
I can't seem to find the beta releases anywhere

**Comment by federicoiosue** [comment]
You have to subscribe the Google+ community and then opt-in for beta testing @thewhitetulip

**Comment by thewhitetulip** [comment]
Sure thing.
