### ISSUE TITLE
Think about omitting settings file backup/restore

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#871]
Currently settings are exported to allow users to restore all their app's preferences on backup restore.

This currently causes two issues, in ascendent order of criticality:

1. Storage Access Framework url in set right into settings, and would be overridden when restoring settings file
2. There is no way to check correctness of a password trying to decode data on restoration, only if it's actually set or not. Importing settings would also override current password with the one from settings file itself, with still not much explorated side effects

**Comment by andr222** [comment]
I agree that restoring settings could be problematic.
I have a concern about importing/merging data so it does not replace/wipe out existing data.  Would this work now, or is it intended to be added?  Sorry if this is off topic, I thought it might be related.
