### ISSUE TITLE
Feature request: pin to top

### ISSUE THREAD

**Issue by Chrizzle** [federicoiosue/Omni-Notes#874]
I would like to be able to pin notes to the top of the notes list. How: within a note there could be an option 'Pin to top'. Multiple pinned-notes should be able to rearrange manually.

Regards Chris

**Comment by federicoiosue** [comment]
Hi Chris, actually notes management in lists should be done by sperating them by categories, and sorting just with currently active filters. Search moreover, by tags or checklists status, is available for sieving.

That's the way the flow was been implemented, by design.
