### ISSUE TITLE
cut function =bug

### ISSUE THREAD

**Issue by andr222** [federicoiosue/Omni-Notes#883]
Omni version 6.1.0

The cut function deletes the value in the old location, but does not write to the new location.  Instead the buffer contains a value from a previous copy.
A workaround is using copy, but then one has to explicitly delete after moving the text. 

This may be intermittant, but it occurred many times and at no occasion did it seem to work.  I have only been using Omni for a few hours, but during this time cut works on several other smartphone apps.  I was able to cut from other note apps and copy the data to Omni without problem.  But not cut from Omni to another location in Omni.  I tried closing and reopening Omni, but the problem persisted.

**Comment by federicoiosue** [comment]
Hi there, is that not much clear to be what you mean.
You mean "when I cut some text from a note"?
Would you mind providing a video example eventually?

**Comment by andr222** [comment]
By cut I mean selecting a text, then cut to remove the text from the source location, to be able to paste it in another location.
At the time it was a persistant problem, occurring only with Omni notes, and not my other applications.
But now (a few days later) it works  properly.
It was shortly after installing Omni notes, maybe somehow it wasn't finished installing ?

**Comment by federicoiosue** [comment]
Nope, all apps actually installs all at once, you have no way to open then until finished installing.
ON actually performs some checks and internal upgrades is you updated it recently, but nothing having impact on its usage.

Feel free to reopen if it happens again, eventually trying to record it.
