### ISSUE TITLE
Deleted items can still be searched outside the Trash

### ISSUE THREAD

**Issue by sjl872964789** [federicoiosue/Omni-Notes#886]
**Describe the bug**
Deleted items can still be searched outside the Trash

**Context**
 - Device: OnePlus 8T
 - OS version: Android 11.0
 - App version: 6.1.0 and 6.2.0_alpha

**How to reproduce**
1. Install Omni Notes and open
2. Skip all welcome screens
3. Add a note and add a checklist to the note
4. Delete the note
5. Search the note
6. Unable to search (it is reasonable, because the note has been deleted)
7. Click "checklist"
8. Deleted notes can be searched

**Expected behavior**
The deleted content can only be found in the "Trash"

**Video**
https://user-images.githubusercontent.com/15941953/211970481-7ad5feed-73b0-4a0e-b241-962a9f0b2b77.mp4

**Comment by federicoiosue** [comment]
Nice point, thanks for reporting!
