### ISSUE TITLE
Data loss error that may reduce user ecperience

### ISSUE THREAD

**Issue by Chou95** [federicoiosue/Omni-Notes#888]
Hi, developers.

I find that there exist some errors on UI after screen rotation. I think that screen rotation shouldn't do damange to the UI state. The re-created UI should be the same as before rotation so that user experience can be imporved. DO you think so?

Details are as follows ( in total).
No.1:  The color of category changes after rotation.
![NO2-BEFORE](https://user-images.githubusercontent.com/111506060/215256977-01fee443-f085-43ea-885f-2e2df572cf84.png)
![NO2-AFTER](https://user-images.githubusercontent.com/111506060/215256981-e51abe9b-94f0-4518-bd18-02d33b4ba638.png)

No.2: The previous input text is lost after rotation.
![NO3-BEFORE](https://user-images.githubusercontent.com/111506060/215257013-2897194e-f459-4520-ae13-3df507c03993.png)
![NO3-AFTER](https://user-images.githubusercontent.com/111506060/215257018-499ec789-1b4c-473f-ad0f-8588c8d46f30.png)

No.3: The searching process will close after rotation.
![NO4-BEFORE](https://user-images.githubusercontent.com/111506060/215257064-ba7d34d9-f088-4318-9354-db1bea291102.png)
![NO4-AFTER](https://user-images.githubusercontent.com/111506060/215257072-74e2b652-ecc3-49be-b8ac-4a4962d9d917.png)

No.4: Some dialogs that are shown on UI will close after rotation, and here give one example.
![NO11-BEFORE](https://user-images.githubusercontent.com/111506060/215257159-27f86a0c-73fc-404b-a7c6-cf753c88f7ae.png)
![NO11-AFTER](https://user-images.githubusercontent.com/111506060/215257167-391ddeb7-ccfb-4863-92bd-fa5084e99eb2.png)

**Comment by federicoiosue** [comment]
Hi there, 

thanks for the feedback. Yes, it should retain state between screen rotation. 
I'll mark this as a minor bug because it's not that much blocking or frequently happening behavior (depending on user's typica usage of course)

**Comment by Burhan7777** [comment]
i will try to fix this. Can we make these 4 as separate bugs ?

**Comment by federicoiosue** [comment]
> i will try to fix this. Can we make these 4 as separate issues?

Of course you can, any help is welcome! Be sure to follow [contributing guidelines](https://github.com/federicoiosue/Omni-Notes/blob/develop/CONTRIBUTING.md).
Probabily the solution is the same for all of thhe fragments/modals above: its a matter of saving restore fields' values. If you want you could manage them on different branches (surely on separated commits) but it's perfectly fine to keep them all together here in the same issue to avoid fragmenting.

**Comment by Burhan7777** [comment]
ok will try to solve them all together

**Comment by Burhan7777** [comment]
I solved No 2, No 3 and No 4 issue. Can i make a pull request and we would make the first issue separate ?

**Comment by federicoiosue** [comment]
Feel free to manage all at once.
If you have any change to perform a test that would be great too!

**Comment by federicoiosue** [comment]
I'm going to close this because the latest issue is being addressed into this separated issue: #890
