### ISSUE TITLE
Screen rotation changes the colour of category.

### ISSUE THREAD

**Issue by Burhan7777** [federicoiosue/Omni-Notes#890]
Whenever screen rotation happens the colour of the category changes.

![Screen1](https://user-images.githubusercontent.com/25124269/217292671-f054b209-9175-4215-9cc3-271bbd668db0.png)
![Screen2](https://user-images.githubusercontent.com/25124269/217292710-f9c3446b-4a16-4a5b-a282-0b19eaded744.png)

**Comment by shalenMathew** [comment]
hey there i'm new to open source , looking to contribute can u assign this to me

**Comment by shalenMathew** [comment]
hey there is this issue closed

**Comment by shalenMathew** [comment]
??

**Comment by federicoiosue** [comment]
Hi there, it's not closed.
I don't know if @Burhan7777 is still working on it

**Comment by Burhan7777** [comment]
Currently not working on it but the issue exists and anyone can work on it.

**Comment by shalenMathew** [comment]
I am currently new to android, from what I observed that, the onCreate() gets recreated when the orientation is changed,
so I saved the selectedColor value in the onSaveInstanceState method and restored it in the onCreate method using the savedInstanceState bundle, but its still not worjing can u guide me , what am I doing wrong?

**Comment by Burhan7777** [comment]
Are you sure the selectedColor value is the color of the category ? Maybe category color value is assigned to some other variable. Please check what the selectedColor points to.

**Comment by tgmiller5** [comment]
@shalenMathew I do not believe so. I tested this yesterday and the issue still appears.
