### ISSUE TITLE
Toolbar doesn't update

### ISSUE THREAD

**Issue by vikasseervi** [federicoiosue/Omni-Notes#896]
Go to "_Settings_"(Toolbar shows "**Settings**") and click on any of the _preferences settings_ and come back then you will find that preferences setting text on the toolbar instead of "**Settings**".
for example: If you click on _DATA_ in preferences and come back you will see "**DATA**" on the toolbar instead of "**Settings**".

**Comment by federicoiosue** [comment]
Updated build with fix will be available [here](https://play.google.com/store/apps/details?id=it.feio.android.omninotes.alpha&hl=en&gl=US) shortly
