### ISSUE TITLE
pls add view mode and edit mode for notes

### ISSUE THREAD

**Issue by surlh** [federicoiosue/Omni-Notes#897]

**Comment by federicoiosue** [comment]
Hi there, this argument has been discussed already previously.
The app has been designed like this for a specific reason: unintentional edits are quite rare, while explicit editing is required for about 1/4 of the time spent on the app. To help on the former situation the option to "discard changes" has been added.

**Comment by surlh** [comment]
sorry, I didn't check the previous issues before starting this one. xD

**Comment by federicoiosue** [comment]
No problems at all! 😅
