### ISSUE TITLE
Notification showing full backup url

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#907]
Should show a more table path instead

![Screenshot_2023-04-17-12-35-28-821_it.feio.android.omninotes-edit.jpg](https://user-images.githubusercontent.com/487104/232460465-a334b736-fa3c-4d0b-97ef-baac106384bd.jpg)

**Comment by AnkitThakur98** [comment]
Hi @federicoiosue , I'd like to work on this. Could you please add the workflow for this issue? Also for the sake of clarity, what do we mean by table path? Thanks!

**Comment by federicoiosue** [comment]
> Hi @federicoiosue , I'd like to work on this. Could you please add the workflow for this issue? Also for the sake of clarity, what do we mean by table path? Thanks!

It may be an outdated bug.

Trying the last stable version on Android 13 gives back the correct path to the user to make it easier to find the backup files. 
The same algorithm should be also used into the settings to show where the next backups will be saved, and it seems to work fine. 

I'll double check also on previous Android versions before deciding for green light or closing the issue.

**Comment by federicoiosue** [comment]
Done

![Immagine_incollata_09_12_23__14_41](https://github.com/federicoiosue/Omni-Notes/assets/487104/255a18c8-fac2-489c-9314-dff685e9a08e)
