### ISSUE TITLE
Feature Request: Add a context menu to quickly make notes

### ISSUE THREAD

**Issue by Qutue** [federicoiosue/Omni-Notes#910]
![Screenshot_2023_0421_093408_Mosaic_9_34_42.png](https://user-images.githubusercontent.com/61310881/233520012-456b1d58-90e1-40bd-99c8-9eff07749db7.png)

**Comment by federicoiosue** [comment]
Hi there,

If I got the point: let a contextual menu option appear everywhere/everytime in the device some text is selected.

It's like this?

**Comment by federicoiosue** [comment]
That would be more an action to let users always keep in mind Omni Notes existence than something useful to them for at least two reasons :

- what if all the apps develops something like that? The selection contextual action would be really bloated
- there is already an easy generic way to do that: just "share" the selected text with Omni Notes and a new note will be created (I always do like this to use snippts from here and there on the web)

**Comment by Qutue** [comment]
Thank you for your reply. "share" is so convenient, I forgot about it .
