### ISSUE TITLE
Adding windows equivalent command for building

### ISSUE THREAD

**Issue by Tvank** [federicoiosue/Omni-Notes#911]
The command "export" works only in the bash terminal. 

"Enter the command $export ANDROID_HOME=/home/fede/Android/Sdk" 

Just ran into this issue when building on my machine. I suggest the window equivalent could be added to the build instructions. 

"Enter the command $set ANDROID_HOME=/home/fede/Android/Sdk"

**Comment by federicoiosue** [comment]
Hi there,

You're perfectly right, I supposed every developer was working on a some kind of Linux subsystem on Windows or native Unix terminal.

Feel free to add a merge request to modify the readme!

**Comment by federicoiosue** [comment]
Closed on [request merged](https://github.com/federicoiosue/Omni-Notes/pull/912)
