### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [federicoiosue/Omni-Notes#924]
ref: https://monitor.f-droid.org/builds/log/it.feio.android.omninotes.foss/323#site-footer

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/b13fcd87f7af7749e7359d1a5db70c7146a6dec5

**Comment by federicoiosue** [comment]
Thanks for pointing my attention to that! Should be fixed by https://github.com/federicoiosue/Omni-Notes/compare/6.2.8...6.2.9
