### ISSUE TITLE
Old versions missing

### ISSUE THREAD

**Issue by A-7666** [federicoiosue/Omni-Notes#928]
I've been trying to find the last pre-5.0.0 version of the program, however it turned out to be impossible.
Releases contain only 5.0.0+ versions, and websearching didn't help.

Where can I get the last pre-5.0.0 version?
Would be really great to find it finally, and have a download link.

(Additional request: please either make the releases collection complete, or make an archive where all versions can be available)

**Comment by federicoiosue** [comment]
Hi, there's really no way to get them back.

Until few time ago I used to keep an archive on a cloud drive (it was originally used to self update the app without play store) but later I switched to GitHub releases.

Given that there 5.x versions started since the fast 2015 I'm also asking why you need older versions.

**Comment by federicoiosue** [comment]
Sadly I don't keep binaries for all the versions, I'm sorry.

Which would be the purpose, anyway?

**Comment by federicoiosue** [comment]
I found out a reeeeally old 4.7.2 binary and created a "new" release for it [here](https://github.com/federicoiosue/Omni-Notes/releases/tag/4.7.2). I hope this suits your needs!

**Comment by federicoiosue** [comment]
The more evident graphical upgrade will come with version 7.
Avoiding upgrading you will use not only the previous UI overhaul but also all the other benefits in terms of features and fixes: this makes the usage of this app useless for you, in my opinion. 

![Screenshot_2023-09-01-09-58-45-815_it.feio.android.omninotes.jpg](https://github.com/federicoiosue/Omni-Notes/assets/487104/1c8b7f57-3efe-4f01-a618-cd3dc67ca059)

![Screenshot_2023-09-01-09-58-33-084_it.feio.android.omninotes.jpg](https://github.com/federicoiosue/Omni-Notes/assets/487104/3deda9b1-11d6-4d5d-866c-e83649060f6b)

![Screenshot_2023-09-01-09-58-52-463_it.feio.android.omninotes.jpg](https://github.com/federicoiosue/Omni-Notes/assets/487104/9b504dcd-a946-4f54-8e1a-2d0b36dd9af0)
