### ISSUE TITLE
Pinned note overwritten 

### ISSUE THREAD

**Issue by dbell154** [federicoiosue/Omni-Notes#929]
Pinned note is overwritten by another note when returning from background. 

Reproduced with the following steps:

Create Pinned Note and Unpinned Note.
Close Omni Notes and remove from memory. 
Using notification open pinned note.
Navigate to unpinned note. Do not edit.
Switch to another app without leaving note or closing Omni.

Use browser, Facebook etc for a while.

Using icon open Omni.
Make change to already open Unpinned note and back out to save.
Changes are saved to pinned note.

**Comment by federicoiosue** [comment]
I've not been able to reproduce during my attempts. I believe it could depend on OS's memory management. 
Would you mind adding more details about Android version and device?
