### ISSUE TITLE
Floating Button disappears (v5b3)

### ISSUE THREAD

**Issue by LeonardKoenig** [federicoiosue/Omni-Notes#93]
So here's my bugreport:
when archiving a note the 'note archived'-banner removes the (+) floating button, permanently, until you eg. swipe in and out the menu.
Actually I dont think ON should make also use the "virtual" home and back-button etc. for displaying notrs etc. No application does that and it creates nasty bugs like the before mentioned banner being half displayed on my home button :/﻿

**Comment by federicoiosue** [comment]
Hi Leonard, 
that's a wanted behavior: when you perform an action that make the undo bar pops up you more relevant action (by default the floating action button) is replaced by the undo bar itself until you choose to undo or dismiss it by interacting in any way (opening the navigation panel on the left or scroll the notes list).

What differs with other apps is that ON doesn't trigger undo bar hiding on time basis but on interaction basis.

**Comment by federicoiosue** [comment]
The only thing I need to change is the useles (and confusing) FAB hiding animation when the navigation drawer is opened

**Comment by LeonardKoenig** [comment]
Couldn't answer so fast ;-)

My problem with this is that when archiving a note you need to swipe in order to be able to create a new one. Isn't that annoying?
