### ISSUE TITLE
Photo note is not supported?

### ISSUE THREAD

**Issue by hieu-van** [federicoiosue/Omni-Notes#930]
I wonder how is a device determined as supporting photo note?

**Comment by federicoiosue** [comment]
Hi there, 

it performs a feature support check against `PackageManager.FEATURE_CAMERA` [here](https://github.com/federicoiosue/Omni-Notes/blob/5c9265b72e74ccd775544f419b21792b09777553/omniNotes/src/main/java/it/feio/android/omninotes/utils/IntentChecker.java#L51).
It may not work into emulators tho.

**Comment by hieu-van** [comment]
I'm using LOS 18.1 on a Xiaomi phone, with Open Camera as the sole camera app (I've disabled stock camera). I think I might be able to help debug this. For now I think that we can instead send an intent to take photo.

**Comment by federicoiosue** [comment]
A quite unofficial condition, unluckly I cannot test it anyway.

As last resource I may try to use a [different camera feature check](https://developer.android.com/reference/android/content/pm/PackageManager.html#FEATURE_CAMERA_ANY) and release a new alpha version to let you try it and report eventually.
