### ISSUE TITLE
Restoring backup infinite load

### ISSUE THREAD

**Issue by Ioana80** [federicoiosue/Omni-Notes#933]
I've been trying to restore a backup on a new Android 13 phone, but I only get a "Working..." notification that never ends. No notes are imported, even after a couple of hours. I also deleted all passwords, so that locked notes are unaffected. Can you please assist?

**Comment by federicoiosue** [comment]
Hi there!

I'm not operative at the moment, but could you provide your device's model name. And a time window to let me check logs?

**Comment by federicoiosue** [comment]
I also supposed we were talking about the latest Play store version, is that true?

**Comment by Ioana80** [comment]
Hi, @federicoiosue . Thanks for replying so quickly! I just tried it again. A report has been sent to the developer message came up. I'm using RealMe 11 Pro+. And the latest Google Play version.

**Comment by federicoiosue** [comment]
Thanks, I'll give a look to it as soon as possible but unlucky not before September, 4.

**Comment by federicoiosue** [comment]
The backup has been created with a different Android/app configuration I suppose also.
Any info about that too?

**Comment by Ioana80** [comment]
Hi again, @federicoiosue . 4th September is okay for me. I lost access to my old phone, unfortunately. It operated on Android 12 (device RealMe GT 5G). I had downloaded the app from F-droid. Restoring the backup also failed to load on the F-droid version, although it was recognized by the app.

**Comment by federicoiosue** [comment]
Keep in mind that F-Droid and Play Store versions are not fully compatible and are meant to eventually coexist. Given the above a backup made with one of them will never be restorable with the other one.

**Comment by Ioana80** [comment]
Thanks for the heads-up! I have re-installed the F-droid version (last updated by you 4 months ago), as I used that one on my old phone. I will wait until you're available on the 4th of September to help out with the restoration.

**Comment by Ioana80** [comment]
Hi there! Are you available to help out right now? The old phone had OmniNotes installed from F-droid. And I did the same for my new phone. Any idea why the loading keeps spinning and no notes are recovered?

**Comment by federicoiosue** [comment]
write my to support@omninotes.app to dig further into the thing, thanks!
