### ISSUE TITLE
Add context menu option to open selected text in Omni Notes in Android.

### ISSUE THREAD

**Issue by rahulpower2012** [federicoiosue/Omni-Notes#934]
**Feature | Adding a context menu option to the existing options when some text is selected in android. Following are the screenshots of the flow.**

1. User selects some text.
2. Under the context menu an option to open the text in the Omni Notes app will appear.
3. When the user selects the option the text is opened as a new note in the app.
4. The title will be empty and should be added by the user.

![Screenshot_20230903-005233](https://github.com/federicoiosue/Omni-Notes/assets/10810713/df85c290-8136-4bab-8843-e951e2175576)

![Screenshot_20230903-005242](https://github.com/federicoiosue/Omni-Notes/assets/10810713/af7344ca-a8ca-42dd-a13f-87b217a0603f)

![Screenshot_20230903-005254](https://github.com/federicoiosue/Omni-Notes/assets/10810713/8a0c7887-04f2-4a5a-8840-9113a3f34e29)

**Comment by rahulpower2012** [comment]
I need this small feature so I have worked on it. I would like it to be part of the official release. I will raise a PR shortly. @federicoiosue

**Comment by rahulpower2012** [comment]
@federicoiosue  I have raised a PR. Please review and let me know https://github.com/federicoiosue/Omni-Notes/pull/935

**Comment by federicoiosue** [comment]
Closed and released within the alpha version of the app on play store
