### ISSUE TITLE
Feature Request: allow cloning checklists

### ISSUE THREAD

**Issue by AaronM04** [federicoiosue/Omni-Notes#936]
It would be nice to be able to duplicate checklists.

PS: kudos to all who worked on this app. It's incredibly useful!

**Comment by federicoiosue** [comment]
Hi Aaron!

What do you mean by "duplicate checklist"? Duplicating the whole note?

**Comment by AaronM04** [comment]
@federicoiosue correct.

**Comment by federicoiosue** [comment]
You get obtain that goal just by sharing the note with the Omni Notes itself and then re-enable the "checklist" mode though options
Il 17 ott 2023, 21:44 +0200, Aaron Miller ***@***.***>, ha scritto:

**Comment by federicoiosue** [comment]
Just to be sure the process is clear before closing the issue https://github.com/federicoiosue/Omni-Notes/assets/487104/b00f27e0-890d-495e-9024-1f88a695d04b
