### ISSUE TITLE
Bug in 6.2.8: Incorrect Search Results Displayed When Searching for Untagged Notes

### ISSUE THREAD

**Issue by XYIheng** [federicoiosue/Omni-Notes#937]
Thanks for developing the awesome app!
When performing a search for untagged notes, the search results incorrectly display tagged notes instead of only untagged ones.

### Reproduce steps:
1. click the FAB 
2. click "Text note"
3. enter the title "C"
4. click the content (enter some text or not)
5. click the button "Add tags"
6. choose any tag
7. click ok
8. back to the note list
9. click search
10. click the button "Tags"
11. just click ok without choosing any tags

### Expected behavior:
The search results should only display untagged note "B" that match the search query.

### Actual behavior:
The search results include both untagged note "B" and tagged note "C",

### Bug video:

https://github.com/federicoiosue/Omni-Notes/assets/31406320/336222f2-5998-46f3-9a45-67bad3dd03ad

### Additional Information:
I find the step 4 is crucial for reproducing the bug. 
If without step 4, the app works well.

### Environment:
Omninotes Version: 6.2.8

**Comment by federicoiosue** [comment]
Thanks for pointing that out to me, I've addressed the misbehavior by allowing the "search by tags" only when at least one tag has been selected.

![Screenshot 2023-10-30 alle 11 07 52](https://github.com/federicoiosue/Omni-Notes/assets/487104/abaf322f-854f-4c61-87a4-5da4c09a873f)

![Screenshot 2023-10-30 alle 11 08 00](https://github.com/federicoiosue/Omni-Notes/assets/487104/189af1fe-663a-4e9c-a597-14edf8bc2ad0)

**Comment by XYIheng** [comment]
Thank you for promptly fixing
