### ISSUE TITLE
Bug Report: Incorrect Count of Notes in Current Category

### ISSUE THREAD

**Issue by XYIheng** [federicoiosue/Omni-Notes#938]
When I click the category in the note, I find the note count for current note's category is wrong

### Reproduce steps:
1. create a note with category A
2. open the note
3. click the button "category"

### Expected behavior:
the note count of category A is 1

### Actual behavior:
the note count of category A is 2. (Actually, I only have one note with this category)

### Bug video:

https://github.com/federicoiosue/Omni-Notes/assets/31406320/fcb838ea-c508-49cf-9a24-54bca3f8890c

### Environment:
Omninotes Version: 6.2.8

**Comment by federicoiosue** [comment]
Impressive error reporting @XYIheng thank you very much!

**Comment by XYIheng** [comment]
Thank you for promptly fixing the bug @federicoiosue 
I really enjoy OmniNotes in my daily life!
