### ISSUE TITLE
[Support request] Internet permissions

### ISSUE THREAD

**Issue by pejakm** [federicoiosue/Omni-Notes#94]
Could someone please explain why do Omni Notes need internet permissions?
Thanks

**Comment by thewhitetulip** [comment]
Which build are you using? If you are using 4.7.2 or above then the permission might be because the creator is planning a sync feature, so that needs internet. Probably.

**Comment by federicoiosue** [comment]
For many reasons.

1. Update syncing (it works also for users without Play Store)
2. Sending bug reports
3. Exchanging analytics data useful to me to decide language translations, API versions support, RTL support, various other things
4. Sync feature (when it'll be ready)

**Comment by pejakm** [comment]
Thanks for clarifications.
