### ISSUE TITLE
Bug Report: Disabling Dynamic Menu in Settings Causes FAB to Appear in Trash

### ISSUE THREAD

**Issue by XYIheng** [federicoiosue/Omni-Notes#941]
### Description:
When disabling the dynamic menu feature in the settings, the Floating Action Button (FAB) erroneously appears in the Trash section (expected: shouldn't appear in the Trash).

### Reproduce steps:
1. disable dynamic menu in Settings
2. back
3. open trash

### Expected behavior:
The FAB shouldn't appear in the trash

### Bug video:

https://github.com/federicoiosue/Omni-Notes/assets/31406320/dfa054c6-45ae-417c-a8a7-7798720462ec

### Environment:
Omninotes Version: 6.2.8

**Comment by federicoiosue** [comment]
It seems to work correctly on 6.3.0 Alpha

**Comment by XYIheng** [comment]
@federicoiosue It is still wrong on 6.3.0 Alpha. I have tested it.
