### ISSUE TITLE
Bug Report: Note tag cannot be removed

### ISSUE THREAD

**Issue by XYIheng** [federicoiosue/Omni-Notes#942]
### Description:
Fail to remove a tag from the note

### Reproduce steps:
1. open a note 
2. add a tag to the note
3. remove a note

### Expected behavior:
the tag successfully removed from the note

### Actual behavior:
The tag still exists in the note content

### Bug video:

https://github.com/federicoiosue/Omni-Notes/assets/31406320/245fd8f5-086d-4536-a124-4f3b7ad03cc2

### Additional Information:
I find if there is no content in the note, it works well.

### Environment:
Omninotes Version: 6.2.8

**Comment by federicoiosue** [comment]
![Alt Text](https://media.giphy.com/media/fem4oy4LOfbL4G64ie/giphy.gif)

**Comment by XYIheng** [comment]
Thanks for your quick fix!
