### ISSUE TITLE
Hashtags starting with number not recognized

### ISSUE THREAD

**Issue by XYIheng** [federicoiosue/Omni-Notes#947]
![image](https://github.com/federicoiosue/Omni-Notes/assets/31406320/e0c79ebf-f063-4c46-ab23-f86131c48eb3)

## Environment:
Omninotes 6.3.0

**Comment by federicoiosue** [comment]
That's actually a desired behavior, the original algorithm was made to mimic Twitter's hashtag recognition.

**Comment by XYIheng** [comment]
I got it! Thanks for your explanation

**Comment by XYIheng** [comment]
@federicoiosue How about a hashtag with a single character? e.g., #d
![image](https://github.com/federicoiosue/Omni-Notes/assets/31406320/7b7c0824-a47a-47fd-8873-4341456dd462)
It seems Omninotes doesn't recognize it. But it is a valid hashtag in Twitter

**Comment by federicoiosue** [comment]
Yes, hashtag recognition could be improved a little bit but I'd avoid introducing all the complexity of the [Twitter's validation library](https://github.com/twitter/twitter-text/blob/master/java/src/main/java/com/twitter/twittertext/Regex.java).
For what concerns my personal usage I always use tags to improve the notes classification, side by side with categories, and usually their value is a complete and readable word.
