### ISSUE TITLE
Bug Report: Deleting One Tag in a Note Affects Another Tag in the Same Note

### ISSUE THREAD

**Issue by XYIheng** [federicoiosue/Omni-Notes#949]
### Description:
When deleting a tag from a note, it erroneously impacts another tag within the same note, leading to unintended changes in the tag.

### Reproduce steps:
1. Click FAB to add a note
2. Add two tags to this note: #tag1, #tag2
3. Move the cursor inside #tag2, e.g., after '#' and before 't' (That step is important to reproduce this bug)
4. Delete #tag1
5. See the error: "#tag2" turns to "# tag2" 

### Bug video:

https://github.com/federicoiosue/Omni-Notes/assets/31406320/612f4ec3-3367-4a71-9a3c-2d5f73ea3326

### Additional details:
The bug only occurs when you put the cursor inside the #tag2. I guess that can help fix the bug

### Environment:
Omninotes Version: 6.3.0

**Comment by federicoiosue** [comment]
The fact that the "tags" are managed just as normal text content pretty much everywhere instead like something more special than that brings to many hard to predict misbehaviors.

I'll check it, thanks for reporting

**Comment by XYIheng** [comment]
fixed in 6.3.2 alpha

**Comment by XYIheng** [comment]
Sorry, my mistake. The bug still exists in 6.3.2 alpha
