### ISSUE TITLE
feature request allow us to pin a note

### ISSUE THREAD

**Issue by devtool15424** [federicoiosue/Omni-Notes#958]
Hi,
It can be great if you allow us to pin a note like Google keep
Have a nice day
Alexander

**Comment by federicoiosue** [comment]
Hi there!

There is actually a way to keep notes pinned into notifications, useful for very urgent things that you want to be sure will stay there until the task is done.

For what concerns your requirement this can easily be obtained just by creating a specific category that will work as "Favorites". I do myself exactly like this, moreover keeping this category ad a widget on my home launcher.
