### ISSUE TITLE
feature request allow us to show note as small block

### ISSUE THREAD

**Issue by devtool15424** [federicoiosue/Omni-Notes#959]
Hi,
It can be great if you allow us to show our note as block instead line like in Google keep
![Screenshot_20231228-090331](https://github.com/federicoiosue/Omni-Notes/assets/93858796/0f48b417-3117-4137-a2b3-0e96298230ae)
Thanks for this great app

Have a nice day
Alexander

**Comment by federicoiosue** [comment]
Hi Alexander, 

that's one of the planned changes when switching to the latest Material You interface. Here you have the milestone's issues: [link](https://github.com/federicoiosue/Omni-Notes/milestone/7).
