### ISSUE TITLE
Error creating Backup

### ISSUE THREAD

**Issue by BDCAPA** [federicoiosue/Omni-Notes#963]
"Something went wrong" (translated from my original system language)

I am moving from my old phone to the new and its really frustrating.

When I press Data/Synch and Backup/Backup the app closes and the error message appears.
I am able to get back to the app at "Recent Apps" but the backup does not start.

First time I was able to choose the backup folder and after that the app closed itself.
I see the folder which I chose under button "Backup".

Version: 6.3.1

**Comment by federicoiosue** [comment]
Sorry for the late reply, not all the Github notifications were been able to reach me late times.
If you still read this a more recent attempt and some more information would appreciated (ex. device brand and model, approximative issue timing appearence).

Thanks!

**Comment by BDCAPA** [comment]
Hi,
It was Xiaomi Redmi 9A.
I manually migrated everything to Google keep with the share function so I
no longer use OmniNote. However as my time allows, I will try to share you
the informations you need to avoid future users experience the same.

What do you mean by approximative issue timing appearance?

Federico Iosue ***@***.***> ezt írta (időpont: 2024. márc.
8., P, 14:36):

**Comment by roeschter** [comment]
Problem solved: Manually giving "Storage" permission to Omni Notes solves the problem.
- Go to Android Settings
- Search for "permission"
- App permissions
- Storage
- Activate permission for Omni Notes

I encountered the same issue on a 5 year old Sony XA2. Trying to move to a new phone. 
I'm changing the backup folder to /storage/emulated/0/Download/Omni Notes - It will immediately crash when trying to execute the export. Creating another subfolder of "Download" shows the same effect.

**Comment by federicoiosue** [comment]
Thanks for the feedback @roeschter !

Actually the app should check for app storage permission and eventually the path selection should be shown.
An alternative approach, useful to arbitrary change the destination of backups after the first selection, is to use the "Change folder" option.
