### ISSUE TITLE
F-droid badge isnt visible

### ISSUE THREAD

**Issue by inson1** [federicoiosue/Omni-Notes#964]
![brave_nqmDOVLUQU](https://github.com/federicoiosue/Omni-Notes/assets/75314629/cf4c6c81-e2bb-483d-8415-c3672d341ee4)

**Comment by federicoiosue** [comment]
Hi there, actually both the image and the link work correctly. Tested both on README and on omninotes.app

**Comment by inson1** [comment]
@federicoiosue now it works, so idk what was the problem
