### ISSUE TITLE
[Bug]: Elements are being overlapped when selected then unselected

### ISSUE THREAD

**Issue by amczuboka** [federicoiosue/Omni-Notes#969]
How to reproduce:
```
Launch OmniNotes
Select a note from homepage
Click the paper clip icon in the top menu
Select the 'Files' option
Select some chip items such as 'Images' or 'Audio'
Unselect some chip items such as 'Images'
Chips will overlap on each other and create an indent within the options
```
Actual Behaviour:

https://github.com/federicoiosue/Omni-Notes/assets/94947740/2adaa260-75a1-45cc-9d0d-45eebf2df86a

Expected Behaviour:

![Screenshot 2024-04-01 at 9 54 15 PM](https://github.com/SOEN345-Winter24OtherSection/alldiscussion/assets/94947740/46cb834e-e095-4301-bae0-a4f4761ea52b)

The elements should always be visible when selected or not selected.

Device information: Pixel_3a_API_34_extension_level_7_x86_64

App version=6.3.1
Android Studio Hedgehog | 2023.1.1 Patch 2
Build #AI-231.9392.1.2311.11330709, built on January 18, 2024
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by federicoiosue** [comment]
Hi there, 

thanks for the bug reporting (I love when the issues are shown that way, so clear and Infraintendible), but that's actually not part of Omni Notes: that's the OS's file picker that most of the apps show when they have to pick media.
Moreover that's the Android "open source" version that may be different on real devices, most of whom brings their own Android modificated version's one.
