### ISSUE TITLE
Cannot cancel the checklist filtering condition to continue searching

### ISSUE THREAD

**Issue by liushuqi-2022** [federicoiosue/Omni-Notes#980]
**To Reproduce**
	1. Go to the search page
	2. Enter the keyword for search
	3. Click on the 'checklist' filtering button
	4. Clicking the 'checklist' button again has no response
	5. Re enter keywords in the search box, but the results are still filtered through a checklist
	
**Expected behavior**
The conversion between checklist filtering and unfiltering should be set. I cancelled "Search: Incomplete checklists", but Omni Notes returned to the homepage.  I hope to continue searching globally on the search page after removing the checklist filtering. It is inconvenient to return to the homepage to conduct a global search again.

**Record**
[untitled1.webm](https://github.com/federicoiosue/Omni-Notes/assets/111285450/310e9a40-0e45-4000-9c2a-af4e70a8101b)

**App Version: 6.3.1**

**Comment by federicoiosue** [comment]
You're right, thanks for bringing that up.
