### ISSUE TITLE
Bug Report: Search Filter does not apply

### ISSUE THREAD

**Issue by XYIheng** [federicoiosue/Omni-Notes#981]
### Description:
The search filter doesn't apply to the note list if click the "Expanded view" or "Reduced view" button

### Reproduce steps:
1. search for a note
2. click to enter the note
3. back to the note list
4. click more option on the right-up corner
5. click "Reduced view" button
6. see error: the filter text still exists, but the filter doesn't apply to the note list anymore.

### Bug video:

https://github.com/federicoiosue/Omni-Notes/assets/31406320/4f2ca6d7-3d9a-435f-bdbb-7dce6596ab48

### Environment:
Omninotes Version: 6.3.2 alpha, 6.2.8

**Comment by DustinKong** [comment]
Hi, I’m experiencing the same issue as described. Could the developers please look into this when possible? Thank you!
Thank you for looking into this issue.

**Comment by XYIheng** [comment]
@federicoiosue hi, do you think this is an issue?
If you agree, I can look into it and I think this should be easy to fix

**Comment by DustinKong** [comment]
@federicoiosue 
Hi! Certainly, I agree that while it might be an issue, it’s still worth addressing. If you could look into fixing it, that would be ideal. Thank you for bringing this to attention!

**Comment by federicoiosue** [comment]
@DustinKong solved successfully.
Actually what I'd expect to be happening here is that the top toolbar should still be in "search mode" or, alternativelly, the search mode is deactivated when a node is entered.
But this specific issue can be considered as solved.

**Comment by DustinKong** [comment]
@federicoiosue Hi~ Glad to see your further reply. The current situation is that in search mode, after reduced or enlarge the view, it is still in search mode and the node lists is still in a searched state. I'm a bit confused about the ideal state or function you're looking for. Can you describe it detailly? I can try to further improve the code.
