### ISSUE TITLE
Expanded view erratic behaviour

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#99]
I just installed the beta 1 and the behaviour of expanded notes is erratic, sometimes it shows the note content and sometimes it doesn't. PFA screenshots.

![screenshot_2015-01-05-20-05-37](https://cloud.githubusercontent.com/assets/6261877/5614386/9a3f8fbe-9516-11e4-94d8-0ce511ba1d78.png)
![screenshot_2015-01-05-20-05-30](https://cloud.githubusercontent.com/assets/6261877/5614384/9a3d0758-9516-11e4-80f5-6d9fb361dc5c.png)

![screenshot_2015-01-05-20-05-44](https://cloud.githubusercontent.com/assets/6261877/5614400/b697b7fe-9516-11e4-8dd3-29c0d3fc249e.png)

**Comment by federicoiosue** [comment]
Closed because the issue you're reporting should actually been fixed. 

Update to the current last released version!
