### ISSUE TITLE
Gone from Google Play Store?

### ISSUE THREAD

**Issue by wKovacs64** [federicoiosue/Omni-Notes#994]
Omni Notes doesn't appear to be in the Play Store anymore. Is this intentional @federicoiosue?

Thanks for your work.

**Comment by federicoiosue** [comment]
Hi Justin,

actually Google Developers program triggered me to fill more personal data to prove my existence and I waited too much, so they removed all my apps from the store. 

I'm waiting for them to evaluate the information I sent to restore them!
